# Generated by Django 5.2.15 on 2026-06-06 14:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0006_historicalfundtransfer_fundtransfer'),
        ('departments', '0006_budget_budgetline_historicalbudget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRecurringExpense',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='ALLOWANCE', max_length=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('SABBATH', 'Every Sabbath (weekly)'), ('MONTHLY', 'Every month')], default='MONTHLY', max_length=8)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='For monthly schedules: day of the month the payment falls due.')),
                ('claimant', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('MPESA', 'M-Pesa')], default='CASH', max_length=8)),
                ('start_date', models.DateField(help_text='First date the schedule is effective from.')),
                ('end_date', models.DateField(blank=True, help_text='Optional: stop generating after this date.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_generated', models.DateField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical recurring expense',
                'verbose_name_plural': 'historical recurring expenses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='ALLOWANCE', max_length=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('SABBATH', 'Every Sabbath (weekly)'), ('MONTHLY', 'Every month')], default='MONTHLY', max_length=8)),
                ('day_of_month', models.PositiveSmallIntegerField(default=1, help_text='For monthly schedules: day of the month the payment falls due.')),
                ('claimant', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('MPESA', 'M-Pesa')], default='CASH', max_length=8)),
                ('start_date', models.DateField(help_text='First date the schedule is effective from.')),
                ('end_date', models.DateField(blank=True, help_text='Optional: stop generating after this date.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_generated', models.DateField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='departments.department')),
            ],
            options={
                'ordering': ['-active', 'description'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.ForeignKey(blank=True, help_text='If set: the recurring schedule that created this expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated', to='cashbook.recurringexpense'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='recurring',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If set: the recurring schedule that created this expense.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.recurringexpense'),
        ),
    ]
