# Generated by Django 5.2.15 on 2026-06-07 05:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0007_historicalrecurringexpense_recurringexpense_and_more'),
        ('departments', '0006_budget_budgetline_historicalbudget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_from_petty_cash',
            field=models.BooleanField(default=False, help_text='Paid out of the petty cash float (reduces the float, charged to its fund).'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='paid_from_petty_cash',
            field=models.BooleanField(default=False, help_text='Paid out of the petty cash float (reduces the float, charged to its fund).'),
        ),
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Period-end the accrual relates to.')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('settled', models.BooleanField(default=False)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='departments.department')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals_recorded', to=settings.AUTH_USER_MODEL)),
                ('settled_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accrual', to='cashbook.expense')),
            ],
            options={
                'ordering': ['settled', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/expenses/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cashbook.expense')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccrual',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Period-end the accrual relates to.')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('settled', models.BooleanField(default=False)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settled_expense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense')),
            ],
            options={
                'verbose_name': 'historical accrual',
                'verbose_name_plural': 'historical accruals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayable',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date the liability was incurred.')),
                ('vendor', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('settled', models.BooleanField(default=False)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settled_expense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense')),
            ],
            options={
                'verbose_name': 'historical payable',
                'verbose_name_plural': 'historical payables',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPettyCashTopUp',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical petty cash top up',
                'verbose_name_plural': 'historical petty cash top ups',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrepayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date paid.')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('months', models.PositiveSmallIntegerField(default=12, help_text='Number of months the prepayment is spread over.')),
                ('start_date', models.DateField(help_text='First month the benefit applies.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_expense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense')),
            ],
            options={
                'verbose_name': 'historical prepayment',
                'verbose_name_plural': 'historical prepayments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date the liability was incurred.')),
                ('vendor', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('settled', models.BooleanField(default=False)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='departments.department')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables_recorded', to=settings.AUTH_USER_MODEL)),
                ('settled_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable', to='cashbook.expense')),
            ],
            options={
                'ordering': ['settled', 'due_date', '-date'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date paid.')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('months', models.PositiveSmallIntegerField(default=12, help_text='Number of months the prepayment is spread over.')),
                ('start_date', models.DateField(help_text='First month the benefit applies.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepayments', to='departments.department')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepayments_recorded', to=settings.AUTH_USER_MODEL)),
                ('source_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayments', to='cashbook.expense')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
