# Generated by Django 5.2.15 on 2026-06-07 13:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0010_expenseattachment_link_expenseattachment_text_and_more'),
        ('departments', '0009_budgetline_source_fund_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStaffAdvance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_issued', models.DateField()),
                ('purpose', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('MPESA', 'M-Pesa')], default='CASH', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTLY', 'Partly settled'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], db_index=True, default='ISSUED', max_length=8)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical staff advance',
                'verbose_name_plural': 'historical staff advances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StaffAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_issued', models.DateField()),
                ('purpose', models.CharField(max_length=200)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('MPESA', 'M-Pesa')], default='CASH', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTLY', 'Partly settled'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], db_index=True, default='ISSUED', max_length=8)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='departments.department')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_issued', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='advance',
            field=models.ForeignKey(blank=True, help_text='If this expense settles a staff cash advance, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cashbook.staffadvance'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='advance',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If this expense settles a staff cash advance, link it here.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.staffadvance'),
        ),
    ]
