# Generated by Django 5.2.15 on 2026-06-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0011_historicalstaffadvance_staffadvance_expense_advance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort', 'label'],
            },
        ),
    ]
