# Generated by Django 5.2 on 2026-06-21 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0013_historicalremittancedeadline_remittancedeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='charge_for',
            field=models.ForeignKey(blank=True, help_text='If this is an M-Pesa/bank transaction charge, the expense that incurred it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='cashbook.expense'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='charge_for',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If this is an M-Pesa/bank transaction charge, the expense that incurred it.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense'),
        ),
    ]
