from django.urls import path
from . import views

urlpatterns = [
    path("queue/sabbath/", views.SabbathConfirmQueueView.as_view(), name="sabbath_queue"),
    path("transactions/", views.TransactionListView.as_view(), name="transaction_list"),
    path("transactions/pending-receipt/", views.PendingReceiptView.as_view(),
         name="pending_receipt_view"),
    path("transactions/<int:pk>/reverse/", views.TransactionReverseView.as_view(), name="transaction_reverse"),
    path("transactions/<int:pk>/history/", views.TransactionHistoryView.as_view(), name="transaction_history"),
    path("transactions/<int:pk>/send-to-review/", views.TransactionSendToReviewView.as_view(), name="transaction_send_to_review"),
    path("transactions/bulk-reverse/", views.TransactionBulkReverseView.as_view(), name="transaction_bulk_reverse"),
    path("queue/", views.ReviewQueueView.as_view(), name="queue"),
    path("queue/bulk-allocate/", views.BulkAllocateView.as_view(), name="queue_bulk_allocate"),
    path("queue/run-rules/", views.RunRulesOnQueueView.as_view(), name="queue_run_rules"),
    path("queue/fetch-unallocated/", views.FetchUnallocatedView.as_view(), name="queue_fetch_unallocated"),
    path("queue/export/", views.QueueExportView.as_view(), name="queue_export"),
    path("queue/import/", views.QueueImportView.as_view(), name="queue_import"),
    path("transactions/mark-processed/", views.MarkProcessedImportView.as_view(), name="mark_processed_import"),
    path("campaigns/", views.CampaignListView.as_view(), name="campaign_list"),
    path("campaigns/sample/", views.CampaignTemplateView.as_view(), name="campaign_template"),
    path("campaigns/new/", views.CampaignCreateView.as_view(), name="campaign_create"),
    path("campaigns/<int:pk>/members/", views.CampaignMemberImportView.as_view(), name="campaign_members"),
    path("campaigns/<int:pk>/delete/", views.CampaignDeleteView.as_view(), name="campaign_delete"),

    path("queue/<int:pk>/claim/", views.ClaimResolveView.as_view(), name="queue_claim"),
    path("cash/new/", views.CashEntryCreate.as_view(), name="cash_new"),
    path("cash/", views.CashEntryListView.as_view(), name="cash_list"),
    path("cash/<int:pk>/delete/", views.CashEntryDeleteView.as_view(), name="cash_delete"),
    path("transactions/<int:pk>/edit/", views.TransactionUpdateView.as_view(), name="transaction_edit"),
    path("transactions/<int:pk>/split/", views.TransactionSplitView.as_view(), name="transaction_split"),
    path("transactions/<int:pk>/shift-sabbath/", views.TransactionShiftSabbathView.as_view(), name="transaction_shift_sabbath"),
    path("rules/", views.RuleListView.as_view(), name="rule_list"),
    path("rules/archive-expired/", views.RuleArchiveExpiredView.as_view(), name="rule_archive_expired"),
    path("rules/<int:pk>/archive/", views.RuleArchiveView.as_view(), name="rule_archive"),
    path("dev-patterns/", views.DevPatternListView.as_view(), name="dev_patterns"),
    path("allocation-settings/", views.AllocationSettingsView.as_view(),
         name="allocation_settings"),
    path("dev-patterns/<int:pk>/toggle/", views.DevPatternToggle.as_view(), name="dev_pattern_toggle"),
    path("dev-patterns/<int:pk>/delete/", views.DevPatternDelete.as_view(), name="dev_pattern_delete"),
    path("rules/import/", views.RuleImportView.as_view(), name="rule_import"),
    path("rules/new/", views.RuleCreateView.as_view(), name="rule_create"),
    path("rules/<int:pk>/delete/", views.RuleDeleteView.as_view(), name="rule_delete"),
    path("rules/<int:pk>/edit/", views.RuleEditView.as_view(), name="rule_edit"),
    path("debits/", views.DebitQueueView.as_view(), name="debit_queue"),
    path("debits/<int:pk>/resolve/", views.DebitResolveView.as_view(), name="debit_resolve"),
]
