# Generated by Django 5.2.15 on 2026-06-04 03:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('members', '0001_initial'),
        ('statements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('source', models.CharField(choices=[('SEED', 'Seeded'), ('LEARNED', 'Learned')], default='LEARNED', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sabbath_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('BANK', 'Bank / M-Pesa'), ('CASH', 'Cash'), ('ENVELOPE', 'Envelope')], max_length=8)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit (giving)'), ('DEBIT', 'Debit (outflow)')], default='CREDIT', max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('payer_name', models.CharField(blank=True, max_length=120)),
                ('payer_phone', models.CharField(blank=True, max_length=12)),
                ('core_ref', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('bank_receipt', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('allocation_status', models.CharField(choices=[('AUTO', 'Auto-allocated'), ('LEARNED', 'Learned rule'), ('MANUAL', 'Manual'), ('REVIEW', 'Needs review')], db_index=True, max_length=8)),
                ('raw_narration', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('claimed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member')),
                ('statement_import', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statements.statementimport')),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sabbath_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('BANK', 'Bank / M-Pesa'), ('CASH', 'Cash'), ('ENVELOPE', 'Envelope')], max_length=8)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit (giving)'), ('DEBIT', 'Debit (outflow)')], default='CREDIT', max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('payer_name', models.CharField(blank=True, max_length=120)),
                ('payer_phone', models.CharField(blank=True, max_length=12)),
                ('core_ref', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('bank_receipt', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('allocation_status', models.CharField(choices=[('AUTO', 'Auto-allocated'), ('LEARNED', 'Learned rule'), ('MANUAL', 'Manual'), ('REVIEW', 'Needs review')], db_index=True, max_length=8)),
                ('raw_narration', models.TextField(blank=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_txns', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('statement_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='statements.statementimport')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date', 'department'], name='giving_tran_date_71b4a9_idx'), models.Index(fields=['allocation_status'], name='giving_tran_allocat_20e9d0_idx'), models.Index(fields=['core_ref'], name='giving_tran_core_re_76e534_idx')],
            },
        ),
    ]
