# Generated by Django 5.2.15 on 2026-06-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_developmentgroup_alter_department_options_and_more'),
        ('giving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='dev_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.developmentgroup'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='mpesa_ref',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa / channel reference from the statement.', max_length=30),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='processed_via_envelope',
            field=models.BooleanField(default=False, help_text='This bank entry was reconciled through a physical envelope; kept out of the review queue to avoid double entry.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dev_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='departments.developmentgroup'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_ref',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa / channel reference from the statement.', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed_via_envelope',
            field=models.BooleanField(default=False, help_text='This bank entry was reconciled through a physical envelope; kept out of the review queue to avoid double entry.'),
        ),
    ]
