# Generated by Django 5.2.15 on 2026-06-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0003_splitfund_alter_allocationrule_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrule',
            name='match_type',
            field=models.CharField(choices=[('EXACT', 'Matches exactly'), ('STARTS', 'Starts with'), ('ENDS', 'Ends with'), ('CONTAINS', 'Contains')], default='EXACT', max_length=8),
        ),
    ]
