# Generated by Django 5.2.15 on 2026-06-06 04:36

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_department_show_in_expenses'),
        ('giving', '0004_allocationrule_match_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAllocationRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('EXACT', 'Matches exactly'), ('STARTS', 'Starts with'), ('ENDS', 'Ends with'), ('CONTAINS', 'Contains')], default='EXACT', max_length=8)),
                ('reference', models.CharField(db_index=True, max_length=60)),
                ('source', models.CharField(choices=[('SEED', 'Seeded'), ('LEARNED', 'Learned')], default='LEARNED', max_length=8)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('split_fund', models.ForeignKey(blank=True, db_constraint=False, help_text='If set, the reference splits across funds.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.splitfund')),
            ],
            options={
                'verbose_name': 'historical allocation rule',
                'verbose_name_plural': 'historical allocation rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
