# Generated by Django 5.2.15 on 2026-06-06 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0005_historicalallocationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='is_reversal',
            field=models.BooleanField(default=False, help_text='A contra entry that reverses another.'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reversal',
            field=models.BooleanField(default=False, help_text='A contra entry that reverses another.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TransactionReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reverses', to='giving.transaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reversal_record', to='giving.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
