# Generated by Django 5.2.15 on 2026-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0007_alter_historicaltransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrule',
            name='valid_from',
            field=models.DateField(blank=True, help_text='First date this rule applies. Blank = no lower bound.', null=True),
        ),
        migrations.AddField(
            model_name='allocationrule',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Last date this rule applies. Blank = no upper bound. Leave both blank for a permanent rule (any period).', null=True),
        ),
        migrations.AddField(
            model_name='historicalallocationrule',
            name='valid_from',
            field=models.DateField(blank=True, help_text='First date this rule applies. Blank = no lower bound.', null=True),
        ),
        migrations.AddField(
            model_name='historicalallocationrule',
            name='valid_to',
            field=models.DateField(blank=True, help_text='Last date this rule applies. Blank = no upper bound. Leave both blank for a permanent rule (any period).', null=True),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=True, help_text='Auto-allocated imports may be held unconfirmed until a treasurer reviews them; unconfirmed rows do not affect balances or the ledger.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed',
            field=models.BooleanField(db_index=True, default=True, help_text='Auto-allocated imports may be held unconfirmed until a treasurer reviews them; unconfirmed rows do not affect balances or the ledger.'),
        ),
        migrations.AlterField(
            model_name='allocationrule',
            name='reference',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
