# Generated by Django 5.2.15 on 2026-06-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0008_allocationrule_valid_from_allocationrule_valid_to_and_more'),
        ('statements', '0004_bankaccount_statementimport_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Which bank account this entry belongs to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statements.bankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Which bank account this entry belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='statements.bankaccount'),
        ),
    ]
