# Generated by Django 5.2.15 on 2026-06-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0009_historicaltransaction_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='service_sabbath',
            field=models.DateField(blank=True, db_index=True, help_text='The Sabbath this gift is credited to (honours the count cutoff). May differ from the transaction date for late/after-cutoff gifts.)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_sabbath',
            field=models.DateField(blank=True, db_index=True, help_text='The Sabbath this gift is credited to (honours the count cutoff). May differ from the transaction date for late/after-cutoff gifts.)', null=True),
        ),
    ]
