# Generated by Django 5.2.15 on 2026-06-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0011_backfill_service_sabbath'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='excluded_from_income',
            field=models.BooleanField(db_index=True, default=False, help_text='A capital receipt (e.g. asset-disposal proceeds) — real cash in the fund, but not operating income, so it is kept out of the Income & Expenditure statement (only the gain/loss is shown there).'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='excluded_from_income',
            field=models.BooleanField(db_index=True, default=False, help_text='A capital receipt (e.g. asset-disposal proceeds) — real cash in the fund, but not operating income, so it is kept out of the Income & Expenditure statement (only the gain/loss is shown there).'),
        ),
    ]
