# Generated by Django 5.2.15 on 2026-06-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0013_historicaltransaction_sabbath_confirm_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='manual_receipt',
            field=models.BooleanField(db_index=True, default=False, help_text='This bank entry was receipted MANUALLY on paper (e.g. a hand-written envelope) with no link to the ledger. No system envelope is created. Kept out of both the review queue and the receipt-bank-giving pull so it is never receipted again. Reversible — untick to make it eligible for a system receipt.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='manual_receipt',
            field=models.BooleanField(db_index=True, default=False, help_text='This bank entry was receipted MANUALLY on paper (e.g. a hand-written envelope) with no link to the ledger. No system envelope is created. Kept out of both the review queue and the receipt-bank-giving pull so it is never receipted again. Reversible — untick to make it eligible for a system receipt.'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='processed_via_envelope',
            field=models.BooleanField(db_index=True, default=False, help_text="A SYSTEM envelope record exists for this bank entry (it was receipted through the app). Set by the receipt-bank-giving pull and the per-gift receipt action. Kept out of the receipting flow so it isn't receipted twice."),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_via_envelope',
            field=models.BooleanField(db_index=True, default=False, help_text="A SYSTEM envelope record exists for this bank entry (it was receipted through the app). Set by the receipt-bank-giving pull and the per-gift receipt action. Kept out of the receipting flow so it isn't receipted twice."),
        ),
    ]
