# Generated by Django 5.2.15 on 2026-06-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0015_split_manual_receipt_from_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationrule',
            name='match_type',
            field=models.CharField(choices=[('EXACT', 'Matches exactly'), ('STARTS', 'Starts with'), ('ENDS', 'Ends with'), ('CONTAINS', 'Contains'), ('REGEX', 'Matches a pattern (regex)')], default='EXACT', max_length=8),
        ),
        migrations.AlterField(
            model_name='historicalallocationrule',
            name='match_type',
            field=models.CharField(choices=[('EXACT', 'Matches exactly'), ('STARTS', 'Starts with'), ('ENDS', 'Ends with'), ('CONTAINS', 'Contains'), ('REGEX', 'Matches a pattern (regex)')], default='EXACT', max_length=8),
        ),
    ]
