# Generated by Django 5.2.15 on 2026-06-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0016_alter_allocationrule_match_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='processed_via_envelope',
            field=models.BooleanField(db_index=True, default=False, help_text="A SYSTEM envelope record exists for this bank entry (it was receipted through the app). Set by the receipt-bank-giving pull and the per-contribution receipt action. Kept out of the receipting flow so it isn't receipted twice."),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='sabbath_confirm_pending',
            field=models.BooleanField(db_index=True, default=False, help_text="Set by the statement importer when the contribution's service Sabbath had already passed on the day of import; the treasurer confirms whether it stays on that Sabbath or moves to the next."),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='service_sabbath',
            field=models.DateField(blank=True, db_index=True, help_text='The Sabbath this contribution is credited to (honours the count cutoff). May differ from the transaction date for late/after-cutoff contributions.)', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_via_envelope',
            field=models.BooleanField(db_index=True, default=False, help_text="A SYSTEM envelope record exists for this bank entry (it was receipted through the app). Set by the receipt-bank-giving pull and the per-contribution receipt action. Kept out of the receipting flow so it isn't receipted twice."),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sabbath_confirm_pending',
            field=models.BooleanField(db_index=True, default=False, help_text="Set by the statement importer when the contribution's service Sabbath had already passed on the day of import; the treasurer confirms whether it stays on that Sabbath or moves to the next."),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_sabbath',
            field=models.DateField(blank=True, db_index=True, help_text='The Sabbath this contribution is credited to (honours the count cutoff). May differ from the transaction date for late/after-cutoff contributions.)', null=True),
        ),
    ]
