# Generated by Django 5.2.15 on 2026-06-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_resync_is_trust'),
        ('giving', '0017_alter_historicaltransaction_processed_via_envelope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='campaign_group',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='campaign_group',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('triggers', models.TextField(blank=True, help_text='Words that mark a reference as belonging to this campaign — comma- or line-separated (e.g. expense, campexpense). The fallback only fires when the reference contains one of these.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(help_text='Fund these contributions are allocated to.', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='departments.department')),
            ],
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.campaign'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='giving.campaign'),
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=12)),
                ('group', models.CharField(blank=True, max_length=40)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='giving.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'name_key'], name='giving_camp_campaig_05fb35_idx'), models.Index(fields=['campaign', 'phone'], name='giving_camp_campaig_08ca83_idx')],
            },
        ),
    ]
