# Generated by Django 5.2 on 2026-06-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0020_seed_dev_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrule',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived rules are kept for the audit trail but no longer used to allocate new giving.'),
        ),
        migrations.AddField(
            model_name='allocationrule',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalallocationrule',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived rules are kept for the audit trail but no longer used to allocate new giving.'),
        ),
        migrations.AddField(
            model_name='historicalallocationrule',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
