# Generated by Django 5.2 on 2026-07-04 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0020_department_income_account'),
        ('giving', '0021_allocationrule_archived_allocationrule_archived_at_and_more'),
        ('members', '0004_member_members_mem_name_8eb2d0_idx'),
        ('statements', '0009_reconciliationitem_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['direction', 'confirmed', 'date'], name='giving_txn_dir_conf_date_idx'),
        ),
    ]
