# Generated by Django 5.2.15 on 2026-07-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0022_transaction_giving_txn_dir_conf_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='split_of',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Set on every row split_into() creates, pointing at the ORIGINAL entry (which keeps its own id and is never itself split_of anything). The authoritative way to find a split's siblings — see split_siblings() — rather than inferring the relationship from shared reference text, which two different people's unrelated payments can coincidentally share.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='split_of',
            field=models.ForeignKey(blank=True, help_text="Set on every row split_into() creates, pointing at the ORIGINAL entry (which keeps its own id and is never itself split_of anything). The authoritative way to find a split's siblings — see split_siblings() — rather than inferring the relationship from shared reference text, which two different people's unrelated payments can coincidentally share.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_children', to='giving.transaction'),
        ),
    ]
