# Generated by Django 5.2.15 on 2026-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0025_retire_dev_group_extra_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='is_banking',
            field=models.BooleanField(db_index=True, default=False, help_text='A banking/deposit entry: the bank credit that is the OTHER LEG of cash already receipted (e.g. Sabbath cash counted, then deposited). It reconciles the bank statement line so the register matches, but it is NOT income and belongs to NO fund — the income and the fund balance were recognised when the cash was counted, and recognising them again on deposit would double-count. Always department=None, excluded_from_income=True. It counts toward the bank position (the money really is at the bank) but nowhere else.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_banking',
            field=models.BooleanField(db_index=True, default=False, help_text='A banking/deposit entry: the bank credit that is the OTHER LEG of cash already receipted (e.g. Sabbath cash counted, then deposited). It reconciles the bank statement line so the register matches, but it is NOT income and belongs to NO fund — the income and the fund balance were recognised when the cash was counted, and recognising them again on deposit would double-count. Always department=None, excluded_from_income=True. It counts toward the bank position (the money really is at the bank) but nowhere else.'),
        ),
    ]
