# Generated by Django 5.2.15 on 2026-07-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0027_campaignmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmessage',
            name='intended_count',
            field=models.PositiveIntegerField(default=0, help_text='How many were due to receive it when the send began.'),
        ),
        migrations.AddField(
            model_name='campaignmessage',
            name='state',
            field=models.CharField(choices=[('RUNNING', 'Sending'), ('DONE', 'Finished'), ('INTERRUPTED', 'Interrupted part-way')], db_index=True, default='DONE', max_length=12),
        ),
    ]
