# Generated by Django 5.2.17 on 2026-09-05 18:08

from django.db import migrations, models

from core.codes import generate_match_code


def backfill_campaign_member_codes(apps, schema_editor):
    CampaignMember = apps.get_model("giving", "CampaignMember")
    used = set(CampaignMember.objects.exclude(match_code__isnull=True)
               .exclude(match_code="")
               .values_list("match_code", flat=True))
    for m in CampaignMember.objects.filter(
            models.Q(match_code__isnull=True) | models.Q(match_code="")):
        for _ in range(40):
            code = generate_match_code("CM")
            if code not in used:
                used.add(code)
                m.match_code = code
                m.save(update_fields=["match_code"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("giving", "0028_campaignmessage_intended_count_campaignmessage_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignmember",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code supporters put in the bank reference to credit "
                          "this member and their group.",
                max_length=16, null=True),
        ),
        migrations.RunPython(backfill_campaign_member_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="campaignmember",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code supporters put in the bank reference to credit "
                          "this member and their group.",
                max_length=16, null=True, unique=True),
        ),
    ]
