# Generated by Django 5.2.17 on 2026-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0029_match_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='attributed_via_code',
            field=models.BooleanField(db_index=True, default=False, help_text='Gift credited to member via a match code; payer_* is who paid.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attributed_via_code',
            field=models.BooleanField(db_index=True, default=False, help_text='Gift credited to member via a match code; payer_* is who paid.'),
        ),
    ]
