# Generated by Django 5.2.15 on 2026-10-09 11:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0022_developmentgroup_match_codes'),
        ('giving', '0030_member_match_codes'),
        ('members', '0006_member_match_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="The member's match code at the time of the prompt.", max_length=16)),
                ('phone', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('status', models.CharField(choices=[('SENT', 'Prompt sent — waiting for PIN'), ('SUCCESS', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled on the phone'), ('TIMEOUT', 'No response'), ('ERROR', 'Prompt could not be sent')], db_index=True, default='SENT', max_length=10)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=30)),
                ('result_code', models.CharField(blank=True, max_length=8)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('followed_up', models.BooleanField(db_index=True, default=False)),
                ('followed_up_at', models.DateTimeField(blank=True, null=True)),
                ('queried_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(blank=True, help_text='The fund this gift will be booked to, copied from settings when the prompt was sent.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departments.department')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribution_attempts', to='members.member')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_attempts', to='giving.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
