# Generated by Django 5.2.15 on 2026-06-13 05:39

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0012_remove_department_is_split_delete_splittarget'),
        ('giving', '0013_historicaltransaction_sabbath_confirm_pending_and_more'),
        ('members', '0003_memberphone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPledgeCampaign',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, help_text='Overall fundraising goal (optional).', max_digits=12)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], db_index=True, default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, db_constraint=False, help_text='The fund contributions toward this campaign land in. Informational — money still flows through the normal ledger.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
            ],
            options={
                'verbose_name': 'historical pledge campaign',
                'verbose_name_plural': 'historical pledge campaigns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount promised.', max_digits=12)),
                ('frequency', models.CharField(choices=[('ONE_OFF', 'One-off'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='ONE_OFF', max_length=10)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Per-installment amount for recurring pledges (optional).', max_digits=12, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, help_text='When the pledge should be fully paid. Past this, an unpaid pledge is treated as lapsed.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (awaiting approval)'), ('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('LAPSED', 'Lapsed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_opt_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges_approved', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPledgePayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('source', models.CharField(choices=[('AUTO', 'Auto-matched'), ('MANUAL', 'Manually matched')], default='MANUAL', max_length=6)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, help_text='The confirmed contribution matched to this pledge.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction')),
                ('pledge', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pledges.pledge')),
            ],
            options={
                'verbose_name': 'historical pledge payment',
                'verbose_name_plural': 'historical pledge payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PledgeCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, help_text='Overall fundraising goal (optional).', max_digits=12)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], db_index=True, default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, help_text='The fund contributions toward this campaign land in. Informational — money still flows through the normal ledger.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge_campaigns', to='departments.department')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pledge',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pledges', to='pledges.pledgecampaign'),
        ),
        migrations.CreateModel(
            name='HistoricalPledge',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount promised.', max_digits=12)),
                ('frequency', models.CharField(choices=[('ONE_OFF', 'One-off'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='ONE_OFF', max_length=10)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Per-installment amount for recurring pledges (optional).', max_digits=12, null=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, help_text='When the pledge should be fully paid. Past this, an unpaid pledge is treated as lapsed.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (awaiting approval)'), ('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('LAPSED', 'Lapsed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reminders_opt_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pledges.pledgecampaign')),
            ],
            options={
                'verbose_name': 'historical pledge',
                'verbose_name_plural': 'historical pledges',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PledgePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('source', models.CharField(choices=[('AUTO', 'Auto-matched'), ('MANUAL', 'Manually matched')], default='MANUAL', max_length=6)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pledges.pledge')),
                ('transaction', models.ForeignKey(blank=True, help_text='The confirmed contribution matched to this pledge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge_payments', to='giving.transaction')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PledgeReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=8)),
                ('to', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('ok', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pledges.pledge')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['status'], name='pledges_ple_status_d21201_idx'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['campaign', 'status'], name='pledges_ple_campaig_18b040_idx'),
        ),
        migrations.AddConstraint(
            model_name='pledgepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('pledge', 'transaction'), name='uniq_pledge_transaction'),
        ),
    ]
