# Generated by Django 5.2.15 on 2026-06-13 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0013_historicaltransaction_sabbath_confirm_pending_and_more'),
        ('pledges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpledge',
            name='self_submitted',
            field=models.BooleanField(default=False, help_text='Submitted by the member via the public pledge link.'),
        ),
        migrations.AddField(
            model_name='historicalpledge',
            name='submitted_contact',
            field=models.CharField(blank=True, help_text='Name/phone the member entered, for verification.', max_length=120),
        ),
        migrations.AddField(
            model_name='pledge',
            name='self_submitted',
            field=models.BooleanField(default=False, help_text='Submitted by the member via the public pledge link.'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='submitted_contact',
            field=models.CharField(blank=True, help_text='Name/phone the member entered, for verification.', max_length=120),
        ),
        migrations.CreateModel(
            name='PledgeMatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='pledges.pledge')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_suggestions', to='giving.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'pledge'), name='uniq_suggestion_txn_pledge')],
            },
        ),
    ]
