# Generated by Django 5.2.15 on 2026-06-14 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0016_alter_allocationrule_match_type_and_more'),
        ('pledges', '0002_historicalpledge_self_submitted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pledgepayment',
            name='uniq_pledge_transaction',
        ),
        migrations.AddConstraint(
            model_name='pledgepayment',
            constraint=models.UniqueConstraint(fields=('pledge', 'transaction'), name='uniq_pledge_transaction'),
        ),
    ]
