# Generated by Django 5.2.15 on 2026-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0004_alter_historicalpledgepayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpledgecampaign',
            name='show_public_progress',
            field=models.BooleanField(default=False, help_text='Show how the campaign is doing — pledges made, amount pledged and amount received — to anyone who opens its public pledge link. Leave off for an appeal whose running total should stay inside the church.'),
        ),
        migrations.AddField(
            model_name='pledgecampaign',
            name='show_public_progress',
            field=models.BooleanField(default=False, help_text='Show how the campaign is doing — pledges made, amount pledged and amount received — to anyone who opens its public pledge link. Leave off for an appeal whose running total should stay inside the church.'),
        ),
    ]
