# Generated by Django 5.2.15 on 2026-08-26 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_membertag_member_tags'),
        ('pledges', '0005_historicalpledgecampaign_show_public_progress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeMatchAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='An extra M-Pesa / mobile number that may pay this pledge.', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Optional note, e.g. Wife, Husband, Second line.', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledge_match_aliases_added', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, help_text='Another register member whose gifts should count (e.g. spouse on a family pledge).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge_match_aliases', to='members.member')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_aliases', to='pledges.pledge')),
            ],
            options={
                'verbose_name': 'Pledge match alias',
                'verbose_name_plural': 'Pledge match aliases',
                'ordering': ['id'],
            },
        ),
    ]
