# Generated by Django 5.2.17 on 2026-09-05 18:08

from django.db import migrations, models

from core.codes import generate_match_code


def backfill_pledge_codes(apps, schema_editor):
    Pledge = apps.get_model("pledges", "Pledge")
    used = set(Pledge.objects.exclude(match_code__isnull=True)
               .exclude(match_code="")
               .values_list("match_code", flat=True))
    for p in Pledge.objects.filter(models.Q(match_code__isnull=True) | models.Q(match_code="")):
        for _ in range(40):
            code = generate_match_code("PG")
            if code not in used:
                used.add(code)
                p.match_code = code
                p.save(update_fields=["match_code"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("pledges", "0006_pledge_match_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpledge",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code for bank/M-Pesa references. Matched before payer "
                          "identity so gifts can be directed to another member's pledge.",
                max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="pledge",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code for bank/M-Pesa references. Matched before payer "
                          "identity so gifts can be directed to another member's pledge.",
                max_length=16, null=True),
        ),
        migrations.RunPython(backfill_pledge_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="pledge",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code for bank/M-Pesa references. Matched before payer "
                          "identity so gifts can be directed to another member's pledge.",
                max_length=16, null=True, unique=True),
        ),
    ]
