# Generated by Django 5.2.15 on 2026-06-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_developmentgroup_leader_email_and_more'),
        ('envelopes', '0002_countsession_countdenomination_countwitness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopeline',
            name='dev_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelope_lines', to='departments.developmentgroup'),
        ),
    ]
