# Generated by Django 5.2 on 2026-07-04 09:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0003_envelopeline_dev_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopeline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
