# Generated by Django 5.2.15 on 2026-07-10 18:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0021_alter_departmentstatuslog_department'),
        ('envelopes', '0004_alter_envelopeline_amount'),
        ('members', '0004_member_members_mem_name_8eb2d0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabbath_date', models.DateField(db_index=True, help_text='The Sabbath these envelopes were given.')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('IMPORT', 'Spreadsheet import')], default='MANUAL', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In review'), ('RETURNED', 'Returned for correction'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('import_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envelope_batches_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelope_batches_posted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelope_batches_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelope_batches_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvelopeBatchRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=0)),
                ('receipt_no', models.CharField(blank=True, max_length=20)),
                ('receipt_no_overridden', models.BooleanField(default=False, help_text="True once the cashier has hand-edited this row's receipt number — the auto-increment sequence continues FROM this value for later rows, but never rewrites it again.")),
                ('contributor_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('channel', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank / M-Pesa')], default='CASH', max_length=4)),
                ('amounts', models.JSONField(blank=True, default=dict)),
                ('manual_total', models.DecimalField(blank=True, decimal_places=2, help_text="What's written on the envelope.", max_digits=12, null=True)),
                ('computed_total', models.DecimalField(decimal_places=2, default=0, help_text='Sum of the allocation columns.', max_digits=12)),
                ('error', models.CharField(blank=True, max_length=40)),
                ('error_detail', models.CharField(blank=True, max_length=200)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='envelopes.envelopebatch')),
                ('dev_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.developmentgroup')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('posted_envelope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_batch_row', to='envelopes.envelope')),
            ],
            options={
                'ordering': ['batch_id', 'line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEnvelopeBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sabbath_date', models.DateField(db_index=True, help_text='The Sabbath these envelopes were given.')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('IMPORT', 'Spreadsheet import')], default='MANUAL', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In review'), ('RETURNED', 'Returned for correction'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('import_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical envelope batch',
                'verbose_name_plural': 'historical envelope batchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='envelopebatch',
            index=models.Index(fields=['status', 'sabbath_date'], name='envelopes_e_status_6626bc_idx'),
        ),
        migrations.AddIndex(
            model_name='envelopebatchrow',
            index=models.Index(fields=['batch', 'line_no'], name='envelopes_e_batch_i_326016_idx'),
        ),
    ]
