# Generated by Django 5.2.15 on 2026-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='receipt_bank_scope',
            field=models.CharField(choices=[('TRUST_ONLY', 'Trust funds only'), ('ALL', 'All giving (trust and local)')], default='TRUST_ONLY', help_text="Which bank giving the 'Receipt bank giving' button turns into envelopes.", max_length=12),
        ),
    ]
