# Generated by Django 5.2.15 on 2026-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_receipt_bank_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='sms_receipt_scope',
            field=models.CharField(choices=[('OFF', "Don't send receipts"), ('ALL', 'All envelope entries (with a phone)'), ('BANK', 'Bank receipts only (with a phone)')], default='OFF', help_text='When a member has a phone number, text them a receipt for these entries.', max_length=4),
        ),
    ]
