# Generated by Django 5.2.15 on 2026-06-06 06:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_periodlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='asset_depr_method',
            field=models.CharField(default='STRAIGHT', help_text='Default depreciation method for new assets.', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='asset_depr_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default annual depreciation rate (percent).', max_digits=5),
        ),
    ]
