# Generated by Django 5.2.15 on 2026-06-06 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfig_asset_depr_method_and_more'),
        ('departments', '0006_budget_budgetline_historicalbudget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearEndClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('total_carried', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='FundCarryForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('close', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.yearendclose')),
            ],
            options={
                'ordering': ['department__name'],
            },
        ),
    ]
