# Generated by Django 5.2.15 on 2026-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_yearendclose_fundcarryforward'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='trust_remit_due_day',
            field=models.PositiveSmallIntegerField(default=15, help_text='Day of the following month by which trust funds (tithe, offerings) should be remitted to the field.'),
        ),
    ]
