# Generated by Django 5.2.15 on 2026-06-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteconfig_petty_cash_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='receipt_message',
            field=models.TextField(blank=True, help_text='Footer message printed at the bottom of contribution receipts. Leave blank to use a default thank-you message.'),
        ),
    ]
