# Generated by Django 5.2.15 on 2026-06-07 06:10

import core.fields
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfig_receipt_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='dual_approval_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Expenses at or above this amount need a second treasurer's approval before they can be marked paid. 0 disables dual approval.", max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enforce_fund_balance',
            field=models.BooleanField(default=True, help_text="Block expenses that would take a fund's available balance negative. Treasurers may override with a logged note; assistants are always blocked."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='enforce_petty_float',
            field=models.BooleanField(default=True, help_text='Block petty cash disbursements that exceed the float on hand.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='require_dual_yearend',
            field=models.BooleanField(default=False, help_text='Require a second treasurer to confirm a year-end close before it is recorded.'),
        ),
        migrations.AddField(
            model_name='yearendclose',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearendclose',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Second treasurer who confirmed the close (when dual confirmation is required).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearend_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='llm_api_key',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sms_api_key',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sms_partner_id',
            field=core.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='HistoricalSiteConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('church_name', models.CharField(default='SDA Church', max_length=120)),
                ('field_name', models.CharField(default='East Nairobi Field', help_text='Where trust funds are remitted.', max_length=120)),
                ('require_expense_approval', models.BooleanField(default=True, help_text='Expenses need treasurer approval before they hit balances.')),
                ('show_mpesa_ref', models.BooleanField(default=True, help_text='Show the M-Pesa / channel reference on ledger rows.')),
                ('enable_dev_groups', models.BooleanField(default=True, help_text='Track giving against development groups.')),
                ('auto_create_members', models.BooleanField(default=True, help_text='Create a member automatically for unknown bank payers.')),
                ('envelope_auto_receipt', models.BooleanField(default=True, help_text='Issue a receipt automatically when an envelope is recorded.')),
                ('receipt_bank_scope', models.CharField(choices=[('TRUST_ONLY', 'Trust funds only'), ('ALL', 'All giving (trust and local)')], default='TRUST_ONLY', help_text="Which bank giving the 'Receipt bank giving' button turns into envelopes.", max_length=12)),
                ('sms_enabled', models.BooleanField(default=False, help_text='Send SMS receipts / notifications via Advanta.')),
                ('sms_api_url', models.CharField(default='https://quicksms.advantasms.com', help_text='Advanta API base URL (see advantasms.com/bulksms-api).', max_length=200)),
                ('sms_api_key', core.fields.EncryptedCharField(blank=True, max_length=500)),
                ('sms_partner_id', core.fields.EncryptedCharField(blank=True, max_length=500)),
                ('sms_shortcode', models.CharField(blank=True, help_text='Registered sender ID / shortcode.', max_length=40)),
                ('sms_receipt_template', models.CharField(blank=True, default='Dear {name}, we received your offering of KES {amount} (receipt {receipt}) on {date}. God bless you. - {church}', help_text='Placeholders: {name} {amount} {receipt} {date} {church}', max_length=320)),
                ('sms_receipt_scope', models.CharField(choices=[('OFF', "Don't send receipts"), ('ALL', 'All envelope entries (with a phone)'), ('BANK', 'Bank receipts only (with a phone)')], default='OFF', help_text='When a member has a phone number, text them a receipt for these entries.', max_length=4)),
                ('llm_enabled', models.BooleanField(default=False, help_text='Use an external LLM for the assistant. Off = the built-in offline assistant answers from your data.')),
                ('llm_provider', models.CharField(choices=[('ANTHROPIC', 'Anthropic (Claude)'), ('OPENAI', 'OpenAI (GPT)'), ('GEMINI', 'Google (Gemini)'), ('GROQ', 'Groq'), ('OPENROUTER', 'OpenRouter'), ('CUSTOM', 'Custom (OpenAI-compatible)')], default='ANTHROPIC', max_length=12)),
                ('llm_api_key', core.fields.EncryptedCharField(blank=True, max_length=500)),
                ('llm_model', models.CharField(blank=True, help_text='e.g. claude-3-5-sonnet, gpt-4o-mini, gemini-1.5-flash.', max_length=80)),
                ('llm_base_url', models.CharField(blank=True, help_text='Only for Custom / self-hosted OpenAI-compatible endpoints.', max_length=200)),
                ('sig_treasurer', models.CharField(blank=True, max_length=120, verbose_name='Head treasurer')),
                ('sig_pastor', models.CharField(blank=True, max_length=120, verbose_name='Pastor')),
                ('sig_elder', models.CharField(blank=True, max_length=120, verbose_name='First church elder')),
                ('asset_depr_method', models.CharField(default='STRAIGHT', help_text='Default depreciation method for new assets.', max_length=10)),
                ('trust_remit_due_day', models.PositiveSmallIntegerField(default=15, help_text='Day of the following month by which trust funds (tithe, offerings) should be remitted to the field.')),
                ('asset_depr_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Default annual depreciation rate (percent).', max_digits=5)),
                ('receipt_message', models.TextField(blank=True, help_text='Footer message printed at the bottom of contribution receipts. Leave blank to use a default thank-you message.')),
                ('petty_cash_float', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Petty cash imprest (float) — the amount the petty cash is topped back up to. Set to 0 if you don't run a fixed float.", max_digits=12)),
                ('dual_approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Expenses at or above this amount need a second treasurer's approval before they can be marked paid. 0 disables dual approval.", max_digits=12)),
                ('enforce_fund_balance', models.BooleanField(default=True, help_text="Block expenses that would take a fund's available balance negative. Treasurers may override with a logged note; assistants are always blocked.")),
                ('enforce_petty_float', models.BooleanField(default=True, help_text='Block petty cash disbursements that exceed the float on hand.')),
                ('require_dual_yearend', models.BooleanField(default=False, help_text='Require a second treasurer to confirm a year-end close before it is recorded.')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical site configuration',
                'verbose_name_plural': 'historical site configuration',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
