# Generated by Django 5.2.15 on 2026-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfig_dual_approval_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='require_import_confirmation',
            field=models.BooleanField(default=False, help_text='Hold auto-allocated statement imports for review; they only affect balances once a treasurer confirms them.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='require_import_confirmation',
            field=models.BooleanField(default=False, help_text='Hold auto-allocated statement imports for review; they only affect balances once a treasurer confirms them.'),
        ),
    ]
