# Generated by Django 5.2.15 on 2026-06-07 13:50

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicalsiteconfig_require_import_confirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='daraja_consumer_key',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='daraja_consumer_secret',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='daraja_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='daraja_env',
            field=models.CharField(blank=True, default='SANDBOX', help_text='SANDBOX or PRODUCTION.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='daraja_shortcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='notify_email_enabled',
            field=models.BooleanField(default=False, help_text='Also email treasurers when an expense needs approval, a remittance is overdue, or a budget is exceeded (requires email to be configured).'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='whatsapp_api_key',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='whatsapp_api_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='whatsapp_provider',
            field=models.CharField(blank=True, default='TWILIO', help_text='TWILIO or AFRICASTALKING.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='whatsapp_sender',
            field=models.CharField(blank=True, help_text='The WhatsApp Business sender number, e.g. +14155238886.', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daraja_consumer_key',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daraja_consumer_secret',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daraja_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daraja_env',
            field=models.CharField(blank=True, default='SANDBOX', help_text='SANDBOX or PRODUCTION.', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daraja_shortcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='notify_email_enabled',
            field=models.BooleanField(default=False, help_text='Also email treasurers when an expense needs approval, a remittance is overdue, or a budget is exceeded (requires email to be configured).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_api_key',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_api_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_provider',
            field=models.CharField(blank=True, default='TWILIO', help_text='TWILIO or AFRICASTALKING.', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp_sender',
            field=models.CharField(blank=True, help_text='The WhatsApp Business sender number, e.g. +14155238886.', max_length=40),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('APPROVAL', 'Approval needed'), ('REMITTANCE', 'Remittance'), ('BUDGET', 'Budget'), ('GENERAL', 'General')], default='GENERAL', max_length=12)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Null = visible to all treasurers.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
