# Generated by Django 5.2.15 on 2026-06-07 16:49

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historicalsiteconfig_daraja_consumer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Enable sending email (reports, receipts, notifications) via SMTP.'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_from',
            field=models.CharField(blank=True, help_text='From address, e.g. treasurer@church.org', max_length=160),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_host_password',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Enable sending email (reports, receipts, notifications) via SMTP.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_from',
            field=models.CharField(blank=True, help_text='From address, e.g. treasurer@church.org', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_host',
            field=models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_host_password',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
