# Generated by Django 5.2.15 on 2026-06-08 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicalsiteconfig_dev_group_extra_prefixes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='sabbath_cutoff',
            field=models.TimeField(default=datetime.time(16, 0), help_text='Time the Sabbath count closes (default 4:00pm). Gifts timestamped after this on the Sabbath roll to next week.'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='sabbath_cutoff_enabled',
            field=models.BooleanField(default=True, help_text='Credit imported gifts that arrive after the cutoff time on the Sabbath to the NEXT Sabbath, so a closed/counted Sabbath is never altered.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sabbath_cutoff',
            field=models.TimeField(default=datetime.time(16, 0), help_text='Time the Sabbath count closes (default 4:00pm). Gifts timestamped after this on the Sabbath roll to next week.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sabbath_cutoff_enabled',
            field=models.BooleanField(default=True, help_text='Credit imported gifts that arrive after the cutoff time on the Sabbath to the NEXT Sabbath, so a closed/counted Sabbath is never altered.'),
        ),
    ]
