# Generated by Django 5.2.15 on 2026-06-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historicalsiteconfig_sabbath_cutoff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='sabbath_cutoff',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='sabbath_cutoff',
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='sabbath_cutoff_enabled',
            field=models.BooleanField(default=True, help_text='When a Sabbath has been closed (counted & receipted), credit any later gift for that Sabbath to the next OPEN Sabbath, so a closed count is never reopened. Close a Sabbath from its cash-count page.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sabbath_cutoff_enabled',
            field=models.BooleanField(default=True, help_text='When a Sabbath has been closed (counted & receipted), credit any later gift for that Sabbath to the next OPEN Sabbath, so a closed count is never reopened. Close a Sabbath from its cash-count page.'),
        ),
        migrations.CreateModel(
            name='SabbathClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabbath', models.DateField(unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sabbath'],
            },
        ),
    ]
