# Generated by Django 5.2.15 on 2026-06-08 07:29

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_historicalsiteconfig_sabbath_cutoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='bank_feed_auth_mode',
            field=models.CharField(choices=[('BASIC', 'Basic authentication (username & password)'), ('TOKEN', 'Token / bearer authentication'), ('NONE', 'None (test environment only)')], default='BASIC', help_text='How the bank authenticates when calling the webhook. Must match what was agreed with the bank.', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='bank_feed_enabled',
            field=models.BooleanField(default=False, help_text="Accept real-time transaction notifications pushed by the bank's Core Banking System to this app's webhook endpoint."),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='bank_feed_password',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Basic-auth password the bank will present.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='bank_feed_token',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text="Shared bearer token the bank will present (sent as 'Authorization: Bearer <token>' or the 'X-Auth-Token' header).", max_length=500),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='bank_feed_username',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Basic-auth username the bank will present.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bank_feed_auth_mode',
            field=models.CharField(choices=[('BASIC', 'Basic authentication (username & password)'), ('TOKEN', 'Token / bearer authentication'), ('NONE', 'None (test environment only)')], default='BASIC', help_text='How the bank authenticates when calling the webhook. Must match what was agreed with the bank.', max_length=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bank_feed_enabled',
            field=models.BooleanField(default=False, help_text="Accept real-time transaction notifications pushed by the bank's Core Banking System to this app's webhook endpoint."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bank_feed_password',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Basic-auth password the bank will present.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bank_feed_token',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text="Shared bearer token the bank will present (sent as 'Authorization: Bearer <token>' or the 'X-Auth-Token' header).", max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bank_feed_username',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Basic-auth username the bank will present.', max_length=255),
        ),
    ]
