# Generated by Django 5.2.15 on 2026-06-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicalsiteconfig_bank_feed_auth_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('collection', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('trust_fund', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='opening_bank_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bank statement balance at the start of the year.', max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='opening_cash_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash not yet banked at the start of the year.', max_digits=14),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='opening_unremitted_trust',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Trust funds collected but not yet remitted at year start.', max_digits=14),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='opening_bank_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bank statement balance at the start of the year.', max_digits=14),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='opening_cash_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash not yet banked at the start of the year.', max_digits=14),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='opening_unremitted_trust',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Trust funds collected but not yet remitted at year start.', max_digits=14),
        ),
    ]
