# Generated by Django 5.2.15 on 2026-06-09 20:13

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_historicalmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=40, unique=True)),
                ('authenticated_until', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_bot_token',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Bot token from @BotFather on Telegram.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_pin',
            field=models.CharField(blank=True, default='1234', help_text='PIN the user must enter at the start of a chat before any data is shown or any expense is recorded.', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_session_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes a chat stays unlocked after a correct PIN.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_bot_token',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Bot token from @BotFather on Telegram.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_pin',
            field=models.CharField(blank=True, default='1234', help_text='PIN the user must enter at the start of a chat before any data is shown or any expense is recorded.', max_length=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_session_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minutes a chat stays unlocked after a correct PIN.'),
        ),
    ]
