# Generated by Django 5.2.15 on 2026-06-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_telegramsession_user_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_run_in_app',
            field=models.BooleanField(default=False, help_text='Run the Telegram bot inside this app via background polling (no separate service or public webhook needed). Turn on for simple deployments; leave off if you use the webhook URL.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_run_in_app',
            field=models.BooleanField(default=False, help_text='Run the Telegram bot inside this app via background polling (no separate service or public webhook needed). Turn on for simple deployments; leave off if you use the webhook URL.'),
        ),
    ]
