# Generated by Django 5.2.15 on 2026-06-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_historicalsiteconfig_telegram_run_in_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_match_mode',
            field=models.CharField(choices=[('OFF', 'Off — never match automatically'), ('SUGGEST', 'Suggest — flag a likely pledge for review'), ('AUTO', 'Auto — apply the match automatically')], default='SUGGEST', help_text='What happens when a new contribution arrives from a member who has an active pledge: do nothing, flag it for a treasurer to confirm, or apply the match automatically.', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_match_same_fund_only',
            field=models.BooleanField(default=True, help_text="Only auto-match a contribution to a pledge when the gift's fund matches the campaign's target fund."),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_match_window_days',
            field=models.PositiveIntegerField(default=400, help_text="How many days after a pledge's end date a contribution may still be matched to it."),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_public_form_enabled',
            field=models.BooleanField(default=False, help_text='Allow members to submit a pledge from a public link. Submissions are held as unverified drafts for a treasurer to review and approve — they never post anywhere until approved.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_match_mode',
            field=models.CharField(choices=[('OFF', 'Off — never match automatically'), ('SUGGEST', 'Suggest — flag a likely pledge for review'), ('AUTO', 'Auto — apply the match automatically')], default='SUGGEST', help_text='What happens when a new contribution arrives from a member who has an active pledge: do nothing, flag it for a treasurer to confirm, or apply the match automatically.', max_length=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_match_same_fund_only',
            field=models.BooleanField(default=True, help_text="Only auto-match a contribution to a pledge when the gift's fund matches the campaign's target fund."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_match_window_days',
            field=models.PositiveIntegerField(default=400, help_text="How many days after a pledge's end date a contribution may still be matched to it."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_public_form_enabled',
            field=models.BooleanField(default=False, help_text='Allow members to submit a pledge from a public link. Submissions are held as unverified drafts for a treasurer to review and approve — they never post anywhere until approved.'),
        ),
    ]
