# Generated by Django 5.2.15 on 2026-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_historicalsiteconfig_pledge_match_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='backup_email',
            field=models.CharField(blank=True, default='', help_text='Email address(es) to send the nightly backup to, comma-separated. Leave blank to keep backups on the server only.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='backup_email',
            field=models.CharField(blank=True, default='', help_text='Email address(es) to send the nightly backup to, comma-separated. Leave blank to keep backups on the server only.', max_length=200),
        ),
    ]
