# Generated by Django 5.2.15 on 2026-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_historicalsiteconfig_error_alert_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='numbered_fund_families',
            field=models.TextField(blank=True, default='', help_text="Route numbered narrations straight to numbered funds, one family per line as 'prefixes = NAME_TEMPLATE'. {n} is the number found. e.g. 'expense, exp, expe = CAMP_{n}' sends EXPENSE1/exp1/expe1 to the fund named CAMP_1, EXPENSE30 to CAMP_30, and so on — no need for a rule per group. Only applies when that fund exists."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='numbered_fund_families',
            field=models.TextField(blank=True, default='', help_text="Route numbered narrations straight to numbered funds, one family per line as 'prefixes = NAME_TEMPLATE'. {n} is the number found. e.g. 'expense, exp, expe = CAMP_{n}' sends EXPENSE1/exp1/expe1 to the fund named CAMP_1, EXPENSE30 to CAMP_30, and so on — no need for a rule per group. Only applies when that fund exists."),
        ),
    ]
