# Generated by Django 5.2.15 on 2026-06-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_historicalsiteconfig_numbered_fund_families_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='pledge_match_same_fund_only',
            field=models.BooleanField(default=True, help_text="Only auto-match a contribution to a pledge when the contribution's fund matches the campaign's target fund."),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='sabbath_confirm_scope',
            field=models.CharField(choices=[('RECEIPTABLE', 'Only funds we receipt (Trust + LCB)'), ('ALL', 'All bank giving')], default='RECEIPTABLE', help_text='Which late-imported contributions appear in the Sabbath confirmations queue. By default only the funds you normally receipt (Trust funds and the Local Church Budget) — others just post by date.', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='sabbath_cutoff_enabled',
            field=models.BooleanField(default=True, help_text='When a Sabbath has been closed (counted & receipted), credit any later contribution for that Sabbath to the next OPEN Sabbath, so a closed count is never reopened. Close a Sabbath from its cash-count page.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='pledge_match_same_fund_only',
            field=models.BooleanField(default=True, help_text="Only auto-match a contribution to a pledge when the contribution's fund matches the campaign's target fund."),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sabbath_confirm_scope',
            field=models.CharField(choices=[('RECEIPTABLE', 'Only funds we receipt (Trust + LCB)'), ('ALL', 'All bank giving')], default='RECEIPTABLE', help_text='Which late-imported contributions appear in the Sabbath confirmations queue. By default only the funds you normally receipt (Trust funds and the Local Church Budget) — others just post by date.', max_length=12),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='sabbath_cutoff_enabled',
            field=models.BooleanField(default=True, help_text='When a Sabbath has been closed (counted & receipted), credit any later contribution for that Sabbath to the next OPEN Sabbath, so a closed count is never reopened. Close a Sabbath from its cash-count page.'),
        ),
    ]
