# Generated by Django 5.2 on 2026-06-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_historicalsiteconfig_pledge_match_same_fund_only_and_more'),
        ('departments', '0015_budgetline_quarter_historicalbudgetline_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_allow_new_member',
            field=models.BooleanField(default=False, help_text='Let Telegram entry create a NEW member when no existing member matches the typed name. Off = assistants can only record for members already in the system (safer).'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_envelope_channel',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank / already given')], default='CASH', help_text='Default channel for envelopes recorded via Telegram.', max_length=4),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_envelope_confirm',
            field=models.BooleanField(default=True, help_text="Show a summary and require a 'yes' before saving each envelope."),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='telegram_envelope_enabled',
            field=models.BooleanField(default=True, help_text='Allow recording envelope/offering giving from Telegram (/envelope).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_allow_new_member',
            field=models.BooleanField(default=False, help_text='Let Telegram entry create a NEW member when no existing member matches the typed name. Off = assistants can only record for members already in the system (safer).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_envelope_channel',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank / already given')], default='CASH', help_text='Default channel for envelopes recorded via Telegram.', max_length=4),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_envelope_confirm',
            field=models.BooleanField(default=True, help_text="Show a summary and require a 'yes' before saving each envelope."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_envelope_enabled',
            field=models.BooleanField(default=True, help_text='Allow recording envelope/offering giving from Telegram (/envelope).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='telegram_envelope_funds',
            field=models.ManyToManyField(blank=True, help_text='Funds offered when recording an envelope on Telegram. Leave empty to use the active offering funds automatically.', related_name='telegram_envelope_configs', to='departments.department'),
        ),
    ]
