# Generated by Django 5.2 on 2026-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_historicalsiteconfig_telegram_allow_new_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='site_base_url',
            field=models.CharField(blank=True, default='', help_text='Public address of this site, e.g. https://kws.oriokie.com — used to turn report links in Telegram replies and emails into clickable URLs.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_base_url',
            field=models.CharField(blank=True, default='', help_text='Public address of this site, e.g. https://kws.oriokie.com — used to turn report links in Telegram replies and emails into clickable URLs.', max_length=200),
        ),
    ]
