# Generated by Django 5.2 on 2026-06-23 09:35

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_historicalsiteconfig_email_use_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='offsite_backup_enabled',
            field=models.BooleanField(default=False, help_text='Also upload each backup to off-site storage over HTTPS (e.g. Nextcloud/WebDAV or an object store that accepts an authenticated upload).'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='offsite_backup_password',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='offsite_backup_url',
            field=models.CharField(blank=True, default='', help_text='Destination folder/URL, e.g. https://cloud.example.com/remote.php/dav/files/treasury/backups/ — the file name is appended.', max_length=300),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='offsite_backup_user',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='offsite_backup_enabled',
            field=models.BooleanField(default=False, help_text='Also upload each backup to off-site storage over HTTPS (e.g. Nextcloud/WebDAV or an object store that accepts an authenticated upload).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='offsite_backup_password',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='offsite_backup_url',
            field=models.CharField(blank=True, default='', help_text='Destination folder/URL, e.g. https://cloud.example.com/remote.php/dav/files/treasury/backups/ — the file name is appended.', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='offsite_backup_user',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
