# Generated by Django 5.2 on 2026-06-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_historicalsiteconfig_offsite_backup_enabled_and_more'),
        ('departments', '0017_department_collection_only_department_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='lcb_departments',
            field=models.ManyToManyField(blank=True, help_text="The Local Church Budget fund and its sub-accounts. When set, reports use exactly these (plus any of their sub-accounts) as the LCB group, instead of guessing from the name. Leave empty to fall back to matching funds named 'LCB' / 'Local Church Budget'.", related_name='+', to='departments.department'),
        ),
    ]
