# Generated by Django 5.2 on 2026-06-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_siteconfig_lcb_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('SYSTEM', 'System'), ('LIGHT', 'Light'), ('DARK', 'Dark')], default='SYSTEM', max_length=8)),
                ('accent', models.CharField(default='forest', help_text="Preset key (e.g. 'forest') or 'custom'.", max_length=16)),
                ('accent_custom', models.CharField(blank=True, default='', help_text="Custom accent hex when accent='custom'.", max_length=7)),
                ('sidebar', models.CharField(choices=[('EXPANDED', 'Expanded'), ('COMPACT', 'Compact'), ('ICON', 'Icon-only')], default='EXPANDED', max_length=10)),
                ('font_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', max_length=6)),
                ('layout_width', models.CharField(choices=[('BOXED', 'Boxed'), ('FULL', 'Full width')], default='BOXED', max_length=5)),
                ('card_style', models.CharField(choices=[('ROUNDED', 'Rounded'), ('SQUARE', 'Square')], default='ROUNDED', max_length=7)),
                ('dashboard_widgets', models.JSONField(blank=True, default=list, help_text='Ordered list of {key, visible} for dashboard widgets.')),
                ('landing_page', models.CharField(default='dashboard', help_text='URL name to open after login.', max_length=40)),
                ('rows_per_page', models.PositiveSmallIntegerField(default=25)),
                ('density', models.CharField(choices=[('COMFORTABLE', 'Comfortable'), ('COMPACT', 'Compact')], default='COMFORTABLE', max_length=11)),
                ('table_state', models.JSONField(blank=True, default=dict, help_text='Per-table saved columns / sort / filters, keyed by table id.')),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('large_targets', models.BooleanField(default=False)),
                ('focus_indicators', models.BooleanField(default=True)),
                ('toasts_enabled', models.BooleanField(default=True)),
                ('toast_duration', models.PositiveSmallIntegerField(default=6, help_text='Seconds a toast stays on screen.')),
                ('desktop_notifications', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
