# Generated by Django 5.2 on 2026-06-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_historicalsiteconfig_dev_group_builder_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='font_family',
            field=models.CharField(choices=[('DEFAULT', 'Public Sans (default)'), ('SYSTEM', 'System UI'), ('SERIF', 'Serif (Georgia)'), ('LEGIBLE', 'Atkinson Hyperlegible'), ('MONO', 'Monospace')], default='DEFAULT', help_text="The typeface used across the app's body text.", max_length=8),
        ),
    ]
