# Generated by Django 5.2 on 2026-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userpreference_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='board_config',
            field=models.JSONField(blank=True, default=dict, help_text='Board report layout: ordered section visibility and options.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='board_config',
            field=models.JSONField(blank=True, default=dict, help_text='Board report layout: ordered section visibility and options.'),
        ),
    ]
