# Generated by Django 5.2 on 2026-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_historicalsiteconfig_board_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='sidebar_style',
            field=models.CharField(choices=[('FOREST', 'Forest (default)'), ('MIDNIGHT', 'Midnight'), ('BRASS', 'Brass'), ('CHARCOAL', 'Charcoal')], default='FOREST', help_text='The colour treatment of the navigation sidebar.', max_length=10),
        ),
    ]
