# Generated by Django 5.2 on 2026-07-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_userpreference_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='church_address',
            field=models.TextField(blank=True, help_text='Postal / physical address shown on report letterheads.'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='church_contact',
            field=models.CharField(blank=True, help_text='Phone and/or email shown on report letterheads.', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='currency_symbol',
            field=models.CharField(default='KSh', help_text='Currency symbol shown before amounts (e.g. KSh, USD, GHS).', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='report_footer_note',
            field=models.CharField(blank=True, help_text='Optional note printed at the foot of reports (e.g. a motto or verse).', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='church_address',
            field=models.TextField(blank=True, help_text='Postal / physical address shown on report letterheads.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='church_contact',
            field=models.CharField(blank=True, help_text='Phone and/or email shown on report letterheads.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='currency_symbol',
            field=models.CharField(default='KSh', help_text='Currency symbol shown before amounts (e.g. KSh, USD, GHS).', max_length=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='report_footer_note',
            field=models.CharField(blank=True, help_text='Optional note printed at the foot of reports (e.g. a motto or verse).', max_length=200),
        ),
    ]
