# Generated by Django 5.2 on 2026-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_historicalsiteconfig_church_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='receipt_strip_strings',
            field=models.TextField(blank=True, help_text="One phrase per line. These are removed from bank/M-Pesa receipt messages when they are saved (e.g. the 'never share your PIN' boilerplate), keeping stored receipts short and readable."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='receipt_strip_strings',
            field=models.TextField(blank=True, help_text="One phrase per line. These are removed from bank/M-Pesa receipt messages when they are saved (e.g. the 'never share your PIN' boilerplate), keeping stored receipts short and readable."),
        ),
    ]
