# Generated by Django 5.2 on 2026-07-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_historicalsiteconfig_receipt_strip_strings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='archive_replaced_ledger_entries',
            field=models.BooleanField(default=True, help_text="Keep a snapshot of a general-ledger entry's prior detail whenever a correction causes it to be replaced (e.g. editing an expense's amount after it was posted), so what the ledger said before the correction can still be reviewed. Recommended on; adds one small archive row per correction."),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='auto_lock_on_reconciliation',
            field=models.BooleanField(default=False, help_text="Automatically lock the accounting month once a bank reconciliation for it is marked reconciled, so a later edit can't silently invalidate a completed reconciliation. Off by default since it also blocks routine corrections in that month once locked; a warning is always shown when editing an entry in an already-reconciled period regardless of this setting."),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='leader_delete_window_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='A department leader may only delete their own already-posted advance expense line within this many days of entering it (afterwards only a treasurer can remove it). Leave blank for no time limit.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='require_different_approver',
            field=models.BooleanField(default=False, help_text='Block a treasurer from approving an expense they recorded themselves, for every expense (not just those above the dual-approval threshold). Leave off if there is only one active treasurer.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='archive_replaced_ledger_entries',
            field=models.BooleanField(default=True, help_text="Keep a snapshot of a general-ledger entry's prior detail whenever a correction causes it to be replaced (e.g. editing an expense's amount after it was posted), so what the ledger said before the correction can still be reviewed. Recommended on; adds one small archive row per correction."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='auto_lock_on_reconciliation',
            field=models.BooleanField(default=False, help_text="Automatically lock the accounting month once a bank reconciliation for it is marked reconciled, so a later edit can't silently invalidate a completed reconciliation. Off by default since it also blocks routine corrections in that month once locked; a warning is always shown when editing an entry in an already-reconciled period regardless of this setting."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='leader_delete_window_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='A department leader may only delete their own already-posted advance expense line within this many days of entering it (afterwards only a treasurer can remove it). Leave blank for no time limit.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='require_different_approver',
            field=models.BooleanField(default=False, help_text='Block a treasurer from approving an expense they recorded themselves, for every expense (not just those above the dual-approval threshold). Leave off if there is only one active treasurer.'),
        ),
    ]
