# Generated by Django 5.2.15 on 2026-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_insightstatus_insightstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='numbered_fund_families',
            field=models.TextField(blank=True, default='', help_text="Route numbered narrations straight to numbered funds, one family per line as 'prefixes = NAME_TEMPLATE'. {n} is the number found. e.g. 'expense, exp, expe = CAMP_{n}' sends EXPENSE1/exp1/expe1 to the fund named CAMP_1, EXPENSE30 to CAMP_30, and so on — no need for a rule per group. A prefix wrapped in slashes is a regular expression for misspellings/variations, e.g. '/expen[sc]es?/, exp = CAMP_{n}' also catches EXPENCE7 and EXPENSES7. Patterns match the lowercased reference with punctuation removed; an invalid pattern is ignored. Only applies when that fund exists."),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='numbered_fund_families',
            field=models.TextField(blank=True, default='', help_text="Route numbered narrations straight to numbered funds, one family per line as 'prefixes = NAME_TEMPLATE'. {n} is the number found. e.g. 'expense, exp, expe = CAMP_{n}' sends EXPENSE1/exp1/expe1 to the fund named CAMP_1, EXPENSE30 to CAMP_30, and so on — no need for a rule per group. A prefix wrapped in slashes is a regular expression for misspellings/variations, e.g. '/expen[sc]es?/, exp = CAMP_{n}' also catches EXPENCE7 and EXPENSES7. Patterns match the lowercased reference with punctuation removed; an invalid pattern is ignored. Only applies when that fund exists."),
        ),
    ]
