# Generated by Django 5.2.15 on 2026-07-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_historicalsiteconfig_numbered_fund_families_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='dev_group_extra_prefixes',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='dev_group_extra_prefixes',
        ),
    ]
