# Generated by Django 5.2.15 on 2026-07-14 06:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_remove_dev_group_extra_prefixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_ac_payee_only',
            field=models.BooleanField(default=True, help_text='Also print “A/C PAYEE ONLY” between the crossing lines. Most church cheques are crossed; untick if yours are pre-crossed.'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_amount_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('132.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_amount_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('48.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_date_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('120.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_date_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('14.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_font_pt',
            field=models.PositiveSmallIntegerField(default=11, help_text='Point size of the printed text.'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_height_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('80.0'), help_text='Height of the leaf, in millimetres.', max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_offset_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Nudge EVERYTHING right (+) or left (−) by this many millimetres. Use this to correct how your printer grips the paper, rather than moving every field one at a time.', max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_offset_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Nudge everything down (+) or up (−).', max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_payee_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_payee_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('28.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_width_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('180.0'), help_text="Width of your bank's cheque leaf, in millimetres. Measure one.", max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_words1_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_words1_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('39.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_words2_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='cheque_words2_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('48.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_ac_payee_only',
            field=models.BooleanField(default=True, help_text='Also print “A/C PAYEE ONLY” between the crossing lines. Most church cheques are crossed; untick if yours are pre-crossed.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_amount_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('132.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_amount_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('48.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_date_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('120.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_date_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('14.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_font_pt',
            field=models.PositiveSmallIntegerField(default=11, help_text='Point size of the printed text.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_height_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('80.0'), help_text='Height of the leaf, in millimetres.', max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_offset_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Nudge EVERYTHING right (+) or left (−) by this many millimetres. Use this to correct how your printer grips the paper, rather than moving every field one at a time.', max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_offset_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Nudge everything down (+) or up (−).', max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_payee_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_payee_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('28.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_width_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('180.0'), help_text="Width of your bank's cheque leaf, in millimetres. Measure one.", max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_words1_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('22.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_words1_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('39.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_words2_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('10.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='cheque_words2_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('48.0'), max_digits=6),
        ),
    ]
