# Generated by Django 5.2.15 on 2026-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_cheque_print_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='figure_font',
            field=models.CharField(choices=[('MONO', 'Tabular monospace (default)'), ('BODY', 'Match body text')], default='MONO', help_text='How monetary figures are set. Tabular monospace keeps columns of numbers perfectly aligned.', max_length=5),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='heading_font',
            field=models.CharField(choices=[('SERIF', 'Serif (Fraunces — default)'), ('SANS', 'Sans-serif (match body)')], default='SERIF', help_text='Typeface for page titles and section headings.', max_length=6),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='sticky_headers',
            field=models.BooleanField(default=True, help_text='Keep table headers visible while scrolling long tables.'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='table_grid',
            field=models.CharField(choices=[('ROWS', 'Row lines only'), ('GRID', 'Full grid')], default='ROWS', help_text='Row lines only (default) or a full grid with column lines.', max_length=5),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='table_stripes',
            field=models.BooleanField(default=True, help_text='Subtle alternating row shading in tables.'),
        ),
    ]
