# Generated by Django 5.2.15 on 2026-07-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='capitalisation_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Purchases below this amount are treated as running costs rather than assets, to keep small items off the register. 0 = no threshold.', max_digits=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='capitalisation_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Purchases below this amount are treated as running costs rather than assets, to keep small items off the register. 0 = no threshold.', max_digits=12),
        ),
    ]
