# Generated by Django 5.2.15 on 2026-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_historicalsiteconfig_capitalisation_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='negatives',
            field=models.CharField(choices=[('MINUS', 'Minus sign  −1,234.50'), ('PARENS', 'Parentheses  (1,234.50)')], default='MINUS', help_text='How negative figures are shown. Accounting convention puts them in parentheses; the parentheses are real characters, so they survive Word, Excel, PDF and print.', max_length=6),
        ),
    ]
