# Generated by Django 5.2.15 on 2026-08-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_userpreference_negatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='allocation_priority',
            field=models.TextField(blank=True, default='', help_text='The order allocation sources are tried in, one key per line. Blank means the built-in order. Set from the Allocation priority page rather than by hand — the keys are defined in core.services.allocation_priority, and an unknown one is ignored rather than obeyed.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='allocation_priority',
            field=models.TextField(blank=True, default='', help_text='The order allocation sources are tried in, one key per line. Blank means the built-in order. Set from the Allocation priority page rather than by hand — the keys are defined in core.services.allocation_priority, and an unknown one is ignored rather than obeyed.'),
        ),
    ]
