# Generated by Django 5.2.15 on 2026-08-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_historicalsiteconfig_allocation_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='envelope_default_funds',
            field=models.TextField(blank=True, default='', help_text='Which fund columns a new Sabbath envelope sheet opens with, one column key per line, in the order they should appear. Blank means the built-in list. Set from the Envelope columns page — a key naming a fund that no longer exists is ignored rather than leaving a blank column.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='envelope_default_funds',
            field=models.TextField(blank=True, default='', help_text='Which fund columns a new Sabbath envelope sheet opens with, one column key per line, in the order they should appear. Blank means the built-in list. Set from the Envelope columns page — a key naming a fund that no longer exists is ignored rather than leaving a blank column.'),
        ),
    ]
