# Generated by Django 5.2.15 on 2026-08-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_formsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_reminder_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you for your pledge of KES {amount} to {campaign}. So far KES {paid} received; KES {outstanding} outstanding. May God bless your faithfulness. - {church}', help_text='Sent as a reminder. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}', max_length=320),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_thanks_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you for pledging KES {amount} to {campaign}. Your promise is recorded. God bless you. - {church}', help_text='Sent when a pledge is recorded. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}', max_length=320),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_reminder_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you for your pledge of KES {amount} to {campaign}. So far KES {paid} received; KES {outstanding} outstanding. May God bless your faithfulness. - {church}', help_text='Sent as a reminder. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}', max_length=320),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_thanks_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you for pledging KES {amount} to {campaign}. Your promise is recorded. God bless you. - {church}', help_text='Sent when a pledge is recorded. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}', max_length=320),
        ),
    ]
