# Generated by Django 5.2.15 on 2026-08-16 21:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_historicalsiteconfig_pledge_reminder_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_cron_auto_match',
            field=models.BooleanField(default=False, help_text='Allow the scheduled `pledge_auto_match` management command to apply matches unattended. Off by default — turn on after you have reviewed how auto-match behaves on this church.'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_fulfilled_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you — your pledge of KES {amount} to {campaign} is fully paid. May God bless your faithfulness. - {church}', help_text='Sent automatically when a pledge is fully paid. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}. Leave blank to use the default.', max_length=320),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_match_fuzzy_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.84'), help_text='For cash/envelope receipts not linked to a member: suggest a match when the payer name is at least this similar to the pledgor (0.00–1.00). Exact name matches always count. Set to 0 to turn fuzzy suggestions off. Used by the auto-match preview; the cron job applies exact matches only unless run with --fuzzy.', max_digits=3),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_send_fulfilled_thanks',
            field=models.BooleanField(default=True, help_text='When a pledge reaches paid in full, send the fulfilled thank-you SMS (if SMS is enabled and the member has a phone).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_cron_auto_match',
            field=models.BooleanField(default=False, help_text='Allow the scheduled `pledge_auto_match` management command to apply matches unattended. Off by default — turn on after you have reviewed how auto-match behaves on this church.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_fulfilled_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you — your pledge of KES {amount} to {campaign} is fully paid. May God bless your faithfulness. - {church}', help_text='Sent automatically when a pledge is fully paid. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}. Leave blank to use the default.', max_length=320),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_match_fuzzy_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.84'), help_text='For cash/envelope receipts not linked to a member: suggest a match when the payer name is at least this similar to the pledgor (0.00–1.00). Exact name matches always count. Set to 0 to turn fuzzy suggestions off. Used by the auto-match preview; the cron job applies exact matches only unless run with --fuzzy.', max_digits=3),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_send_fulfilled_thanks',
            field=models.BooleanField(default=True, help_text='When a pledge reaches paid in full, send the fulfilled thank-you SMS (if SMS is enabled and the member has a phone).'),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='pledge_reminder_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you for your pledge of KES {amount} to {campaign}. So far KES {paid} received; KES {outstanding} outstanding. May God bless your faithfulness. - {church}', help_text='Sent as a reminder. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}. For a member with several pledges, one combined message is sent — {campaign} lists each, and the amounts are totals.', max_length=320),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='pledge_reminder_template',
            field=models.CharField(blank=True, default='Dear {name}, thank you for your pledge of KES {amount} to {campaign}. So far KES {paid} received; KES {outstanding} outstanding. May God bless your faithfulness. - {church}', help_text='Sent as a reminder. Placeholders: {name} {amount} {campaign} {church} {paid} {outstanding} {due}. For a member with several pledges, one combined message is sent — {campaign} lists each, and the amounts are totals.', max_length=320),
        ),
    ]
