# Generated by Django 5.2.15 on 2026-08-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_pledge_fuzzy_fulfilled_cron'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_public_submit_mode',
            field=models.CharField(choices=[('DRAFT', 'Hold as draft — treasurer must approve'), ('ACTIVE', 'Accept immediately — counts at once')], default='DRAFT', help_text='What happens when a member submits via the public pledge link. Draft (default) waits for approval and does not count toward the campaign until then. Accept immediately makes the pledge active as soon as it is submitted.', max_length=8),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='pledge_send_submit_thanks',
            field=models.BooleanField(default=True, help_text='When a member submits a pledge on the public link, send the thank-you-for-pledging SMS (uses the wording above; requires SMS enabled and a phone on the form).'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_public_submit_mode',
            field=models.CharField(choices=[('DRAFT', 'Hold as draft — treasurer must approve'), ('ACTIVE', 'Accept immediately — counts at once')], default='DRAFT', help_text='What happens when a member submits via the public pledge link. Draft (default) waits for approval and does not count toward the campaign until then. Accept immediately makes the pledge active as soon as it is submitted.', max_length=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='pledge_send_submit_thanks',
            field=models.BooleanField(default=True, help_text='When a member submits a pledge on the public link, send the thank-you-for-pledging SMS (uses the wording above; requires SMS enabled and a phone on the form).'),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='pledge_public_form_enabled',
            field=models.BooleanField(default=False, help_text='Allow members to submit a pledge from a public link.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='pledge_public_form_enabled',
            field=models.BooleanField(default=False, help_text='Allow members to submit a pledge from a public link.'),
        ),
    ]
