# Generated by Django 5.2.15 on 2026-10-09 11:54

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_pledge_public_submit_and_thanks_sms'),
        ('departments', '0022_developmentgroup_match_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_fund',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Gifts paid through a personal link are booked to this fund and credited to the member whose code is in the link.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_links_enabled',
            field=models.BooleanField(default=False, help_text='Let each member share a link friends can open to give by M-Pesa prompt. Off until you choose the fund below.'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_quick_amounts',
            field=models.CharField(blank=True, default='50,100,500,1000', help_text='Whole-shilling amounts offered as buttons, separated by commas.', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_sms_template',
            field=models.CharField(blank=True, default='Dear {name}, {church} has introduced a personal contribution link for you. You may use it to make your contribution and also share it with friends and family who wish to support you. All payments made through your link will be credited to your account and added to your total contribution. Your link: {link}. Your code: {code}. God bless you.', help_text='Texted to a member with their own link. Placeholders: {name} (first name) {church} {fund} {link} {code}.', max_length=600),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_tagline',
            field=models.CharField(blank=True, default="Together we build for God's glory", help_text='One line under the heading.', max_length=140),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_title',
            field=models.CharField(blank=True, default='Development Fund', help_text='Heading on the public page, under the church name.', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_verse',
            field=models.CharField(blank=True, default='Each of you should give what you have decided in your heart to give.', help_text='Short verse at the foot of the public page. Leave blank to hide it.', max_length=240),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='contrib_verse_ref',
            field=models.CharField(blank=True, default='2 Corinthians 9:7', max_length=40),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='daraja_passkey',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Lipa na M-Pesa passkey from the Daraja portal. Required for the STK prompt on a personal contribution link.', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='daraja_txn_type',
            field=models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Buy Goods (till)')], default='PAYBILL', help_text="Paybill asks the payer for an account number — the member's code. A till does not, but a gift paid through a member's link is still credited to that member.", max_length=8),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_fund',
            field=models.ForeignKey(blank=True, help_text='Gifts paid through a personal link are booked to this fund and credited to the member whose code is in the link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departments.department'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_links_enabled',
            field=models.BooleanField(default=False, help_text='Let each member share a link friends can open to give by M-Pesa prompt. Off until you choose the fund below.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_quick_amounts',
            field=models.CharField(blank=True, default='50,100,500,1000', help_text='Whole-shilling amounts offered as buttons, separated by commas.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_sms_template',
            field=models.CharField(blank=True, default='Dear {name}, {church} has introduced a personal contribution link for you. You may use it to make your contribution and also share it with friends and family who wish to support you. All payments made through your link will be credited to your account and added to your total contribution. Your link: {link}. Your code: {code}. God bless you.', help_text='Texted to a member with their own link. Placeholders: {name} (first name) {church} {fund} {link} {code}.', max_length=600),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_tagline',
            field=models.CharField(blank=True, default="Together we build for God's glory", help_text='One line under the heading.', max_length=140),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_title',
            field=models.CharField(blank=True, default='Development Fund', help_text='Heading on the public page, under the church name.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_verse',
            field=models.CharField(blank=True, default='Each of you should give what you have decided in your heart to give.', help_text='Short verse at the foot of the public page. Leave blank to hide it.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contrib_verse_ref',
            field=models.CharField(blank=True, default='2 Corinthians 9:7', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daraja_passkey',
            field=core.fields.EncryptedCharField(blank=True, default='', help_text='Lipa na M-Pesa passkey from the Daraja portal. Required for the STK prompt on a personal contribution link.', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='daraja_txn_type',
            field=models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Buy Goods (till)')], default='PAYBILL', help_text="Paybill asks the payer for an account number — the member's code. A till does not, but a gift paid through a member's link is still credited to that member.", max_length=8),
        ),
    ]
