# Generated by Django 5.2.15 on 2026-06-06 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_budget_budgetline_historicalbudget_and_more'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='departments.department'),
        ),
    ]
