# Generated by Django 5.2 on 2026-07-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_journalline_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('source_type', models.CharField(db_index=True, max_length=20)),
                ('source_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('original_entry_id', models.IntegerField(db_index=True)),
                ('original_created_at', models.DateTimeField()),
                ('lines', models.JSONField(help_text='[{account_code, account_name, department_id, debit, credit}, ...]')),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-replaced_at'],
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='ledger_jour_source__de2cab_idx')],
            },
        ),
    ]
