# Generated by Django 5.2 on 2026-07-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_journalentryarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='number',
            field=models.CharField(blank=True, help_text='Permanent journal voucher reference (e.g. JV-2026-000001), assigned once and never reused or renumbered — including when this entry is later replaced by a correction (see JournalEntryArchive, which preserves the original number).', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journalentryarchive',
            name='original_number',
            field=models.CharField(blank=True, help_text='The permanent journal reference (e.g. JV-2026-000001) this entry carried before it was replaced — preserved here since that number is never reissued to anything else.', max_length=20, null=True),
        ),
    ]
