# Generated by Django 5.2.15 on 2026-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0005_bankevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementimport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('PURGED', 'Purged')], default='PENDING', max_length=10),
        ),
    ]
