"""Generated from the church chart of accounts and the labelled
narration dataset. Accounts + opening balances, and reference rules."""

# (name, opening_balance) — standalone LOCAL funds unless mapped to existing
PASTED_ACCOUNTS = [
    ('LCB', '-6672.01'),
    ('SOCIAL_SUNDAY', '0'),
    ('CHURCH CHOIR', '73418'),
    ('KYETHANI', '12559'),
    ('YOUTH', '39129'),
    ('DEACONRY', '2280'),
    ('CHAPLAINCY', '9650'),
    ('BENEVOLENT FUND', '364951'),
    ('AWM', '16455'),
    ('ADVENTURERS', '2561'),
    ('CHILDREN MINISTRY', '19555'),
    ('PATHFINDERS', '17120'),
    ('ADVENTIST SINGLE ADULT MINISTRIES', '400'),
    ('ADVENTIST POSSIBILITY MINISTRY', '3797'),
    ('MSAMARIA', '2380'),
    ('MASTER GUIDE', '18972'),
    ('AMBASSADORS', '70869'),
    ("PASTOR'S APPRECIATION", '0'),
    ('COMMUNICATION', '10992'),
    ('CHURCH_CHOIR_LAUNCH', '337812'),
    ('MATOPENI', '1700'),
    ('EMERGENCY_FUND', '5992'),
    ('LOCAL_EVANGELISM', '2285'),
    ('CAMP EXPENSE', '1500'),
    ('AMM', '4273'),
    ('AMM_CHOIR', '70946'),
    ('UPPER_CLEANSHELF', '718'),
    ('PENDING', '75582'),
    ('AWM_BREAKFAST', '575'),
    ('SOLOMON_PLAZA', '8000'),
    ('CMA', '350'),
    ('AWM_WELFARE', '16760'),
    ('CHURCH_CHOIR_WELFARE', '37680'),
    ('VBS', '112621'),
    ('PUBLIC CAMPUS MINISTRY', '400'),
    ('DEVELOPMENT', '3047812.72'),
    ('IKONDENI', '859'),
    ('AMM_PROJECT', '500'),
    ('DISTRICT_COLLECTION', '632'),
    ('KALAANI_MISSION', '2239.8'),
    ('YOUTH_MISSION', '7334'),
    ('ADV_PF', '0'),
    ('PUBLISHING', '500'),
]

MAP_TO_EXISTING = {'LCB': 'LCB – Local Church Budget', 'DEVELOPMENT': 'Development'}
HOLDING_ACCOUNTS = ['DISTRICT_COLLECTION', 'PENDING', 'UPPER_CLEANSHELF']
DEVELOPMENT_ACCOUNTS = ['AMM_PROJECT', 'CHURCH_CHOIR_LAUNCH', 'IKONDENI', 'KALAANI_MISSION', 'KYETHANI', 'MATOPENI', 'SOLOMON_PLAZA']

# normalized reference -> fund name (SEED rules)
ACCOUNT_RULES = {
    'advreg': 'ADVENTURERS',
    'advres': 'ADVENTURERS',
    'advtrans': 'ADVENTURERS',
    'advtransport': 'ADVENTURERS',
    'ambgyd': 'YOUTH',
    'ambstshirt': 'AMBASSADORS',
    'ambtshirt': 'AMBASSADORS',
    'ambvbs': 'VBS',
    'amm': 'AMM_CHOIR',
    'ammbbs': 'VBS',
    'ammbvs': 'VBS',
    'ammchoir': 'AMM_CHOIR',
    'ammfood': 'VBS',
    'ammlaunch': 'AMM_CHOIR',
    'ammreg': 'AMM',
    'ammvbs': 'VBS',
    'amochoir': 'AMM_CHOIR',
    'apm': 'ADVENTIST POSSIBILITY MINISTRY',
    'awmreg': 'AWM',
    'awmvbs': 'VBS',
    'aygyd': 'YOUTH',
    'aymns': 'YOUTH',
    'aymse': 'YOUTH',
    'ayrtt': 'YOUTH',
    'aysvbsgr5': 'VBS',
    'aysvbsgrp5': 'VBS',
    'ayvbs': 'VBS',
    'ayvbs4': 'VBS',
    'ayvbsg2': 'VBS',
    'ayvbsgr1': 'VBS',
    'ayvbsgr3': 'VBS',
    'ayvbsgr5': 'VBS',
    'ayvbsgrp1': 'VBS',
    'ayvbsgrp3': 'VBS',
    'ayvbsgrp4': 'VBS',
    'ayvbsgrp5': 'VBS',
    'chaplaincy': 'CHAPLAINCY',
    'chaplreg': 'CHAPLAINCY',
    'chapreg': 'CHAPLAINCY',
    'chapsabbath': 'CHAPLAINCY',
    'chethani': 'KYETHANI',
    'choir': 'CHURCH_CHOIR_LAUNCH',
    'choirlauch': 'CHURCH_CHOIR_LAUNCH',
    'choirlaunc': 'CHURCH_CHOIR_LAUNCH',
    'choirlaunch': 'CHURCH_CHOIR_LAUNCH',
    'choirlaunch254': 'CHURCH_CHOIR_LAUNCH',
    'choirllaunch': 'CHURCH_CHOIR_LAUNCH',
    'choirlounch': 'CHURCH_CHOIR_LAUNCH',
    'choirwelkitty': 'CHURCH_CHOIR_WELFARE',
    'cmaccount': 'CMA',
    'cmfood': 'VBS',
    'cmrally': 'CHILDREN MINISTRY',
    'gyd': 'YOUTH',
    'gydamb': 'YOUTH',
    'gydamba': 'YOUTH',
    'gydambs': 'YOUTH',
    'hosministry': 'CHAPLAINCY',
    'ikondeni': 'IKONDENI',
    'kyethani': 'KYETHANI',
    'kythani': 'KYETHANI',
    'kytheni': 'KYETHANI',
    'launch': 'CHURCH_CHOIR_LAUNCH',
    'msamaria': 'MSAMARIA',
    'pcm': 'PUBLIC CAMPUS MINISTRY',
    'pfreg': 'PATHFINDERS',
    'portluck2': 'YOUTH',
    'potluck2': 'YOUTH',
    'potluck5': 'YOUTH',
    'sspr': 'SOCIAL_SUNDAY',
    'vbs': 'VBS',
    'vbsamb': 'VBS',
    'vbsambs': 'VBS',
    'vbsawm': 'VBS',
    'vbsfood': 'VBS',
    'vbsreg': 'VBS',
}
