# Generated by Django 5.2.15 on 2026-06-06 06:01

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0006_budget_budgetline_historicalbudget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
                ('method', models.CharField(choices=[('STRAIGHT', 'Straight-line'), ('REDUCING', 'Reducing balance'), ('NONE', 'Not depreciated')], default='STRAIGHT', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Annual depreciation rate, percent.', max_digits=5)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('LAND', 'Land'), ('BUILDING', 'Buildings'), ('FURNITURE', 'Furniture & fittings'), ('EQUIPMENT', 'Equipment'), ('VEHICLE', 'Motor vehicles'), ('IT', 'Computers & IT'), ('MUSICAL', 'Musical instruments'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('acquired_on', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(blank=True, choices=[('STRAIGHT', 'Straight-line'), ('REDUCING', 'Reducing balance'), ('NONE', 'Not depreciated')], max_length=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, help_text='Tag / serial no.', max_length=40)),
                ('disposed', models.BooleanField(default=False)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='departments.department')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDepreciationRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=20)),
                ('method', models.CharField(choices=[('STRAIGHT', 'Straight-line'), ('REDUCING', 'Reducing balance'), ('NONE', 'Not depreciated')], default='STRAIGHT', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Annual depreciation rate, percent.', max_digits=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical depreciation rule',
                'verbose_name_plural': 'historical depreciation rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFixedAsset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('LAND', 'Land'), ('BUILDING', 'Buildings'), ('FURNITURE', 'Furniture & fittings'), ('EQUIPMENT', 'Equipment'), ('VEHICLE', 'Motor vehicles'), ('IT', 'Computers & IT'), ('MUSICAL', 'Musical instruments'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('acquired_on', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('method', models.CharField(blank=True, choices=[('STRAIGHT', 'Straight-line'), ('REDUCING', 'Reducing balance'), ('NONE', 'Not depreciated')], max_length=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, help_text='Tag / serial no.', max_length=40)),
                ('disposed', models.BooleanField(default=False)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('disposal_proceeds', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fixed asset',
                'verbose_name_plural': 'historical fixed assets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
