# Generated by Django 5.2.15 on 2026-06-07 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('departments', '0006_budget_budgetline_historicalbudget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_fund',
            field=models.ForeignKey(blank=True, help_text='Fund that received the disposal proceeds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals', to='departments.department'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_gain_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proceeds less net book value at disposal (gain positive, loss negative).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_method',
            field=models.CharField(blank=True, choices=[('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped / written off'), ('DONATED', 'Donated / given away'), ('LOST', 'Lost / stolen')], max_length=10),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='disposal_fund',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Fund that received the disposal proceeds.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='disposal_gain_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proceeds less net book value at disposal (gain positive, loss negative).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='disposal_method',
            field=models.CharField(blank=True, choices=[('SOLD', 'Sold'), ('SCRAPPED', 'Scrapped / written off'), ('DONATED', 'Donated / given away'), ('LOST', 'Lost / stolen')], max_length=10),
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assets/%Y/%m/')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assets.fixedasset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
