# Generated by Django 5.2 on 2026-06-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_fixedasset_disposal_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='category',
            field=models.CharField(choices=[('LAND', 'Land'), ('CONSTRUCTION', 'Construction in progress'), ('BUILDING', 'Buildings'), ('FURNITURE', 'Furniture & fittings'), ('EQUIPMENT', 'Equipment'), ('VEHICLE', 'Motor vehicles'), ('IT', 'Computers & IT'), ('MUSICAL', 'Musical instruments'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalfixedasset',
            name='category',
            field=models.CharField(choices=[('LAND', 'Land'), ('CONSTRUCTION', 'Construction in progress'), ('BUILDING', 'Buildings'), ('FURNITURE', 'Furniture & fittings'), ('EQUIPMENT', 'Equipment'), ('VEHICLE', 'Motor vehicles'), ('IT', 'Computers & IT'), ('MUSICAL', 'Musical instruments'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
