# Generated by Django 5.2.15 on 2026-07-21 15:19

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_fixedasset_cost_alter_fixedasset_salvage_value_and_more'),
        ('core', '0054_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.organization'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_held', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='in_service_on',
            field=models.DateField(blank=True, help_text='Commissioning date — when depreciation starts (may differ from acquisition).', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_heritage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='revalued_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='serial_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ON_ORDER', 'On order'), ('IN_CWIP', 'Under construction'), ('IN_SERVICE', 'In service'), ('IDLE', 'Idle / in store'), ('MAINTENANCE', 'Under maintenance'), ('IMPAIRED', 'Impaired'), ('HELD_SALE', 'Held for disposal'), ('DISPOSED', 'Disposed'), ('ARCHIVED', 'Archived')], db_index=True, default='IN_SERVICE', max_length=12),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='Printed asset tag / QR payload.', max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='useful_life_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='church',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.organization'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='custodian',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='in_service_on',
            field=models.DateField(blank=True, help_text='Commissioning date — when depreciation starts (may differ from acquisition).', null=True),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='is_donated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='is_heritage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='revalued_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='serial_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ON_ORDER', 'On order'), ('IN_CWIP', 'Under construction'), ('IN_SERVICE', 'In service'), ('IDLE', 'Idle / in store'), ('MAINTENANCE', 'Under maintenance'), ('IMPAIRED', 'Impaired'), ('HELD_SALE', 'Held for disposal'), ('DISPOSED', 'Disposed'), ('ARCHIVED', 'Archived')], db_index=True, default='IN_SERVICE', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='Printed asset tag / QR payload.', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='useful_life_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('depreciable', models.BooleanField(default=True)),
                ('is_cwip', models.BooleanField(default=False)),
                ('default_method', models.CharField(choices=[('STRAIGHT', 'Straight-line'), ('REDUCING', 'Reducing balance'), ('NONE', 'Not depreciated')], default='STRAIGHT', max_length=10)),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('default_useful_life_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('componentised', models.BooleanField(default=False)),
                ('acct_cost_key', models.CharField(blank=True, max_length=40)),
                ('acct_accdep_key', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.assetclass')),
            ],
            options={
                'verbose_name_plural': 'asset classes',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='asset_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetclass'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='asset_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.assetclass'),
        ),
        migrations.CreateModel(
            name='HistoricalAssetClass',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=80)),
                ('depreciable', models.BooleanField(default=True)),
                ('is_cwip', models.BooleanField(default=False)),
                ('default_method', models.CharField(choices=[('STRAIGHT', 'Straight-line'), ('REDUCING', 'Reducing balance'), ('NONE', 'Not depreciated')], default='STRAIGHT', max_length=10)),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('default_useful_life_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('componentised', models.BooleanField(default=False)),
                ('acct_cost_key', models.CharField(blank=True, max_length=40)),
                ('acct_accdep_key', models.CharField(blank=True, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.assetclass')),
            ],
            options={
                'verbose_name': 'historical asset class',
                'verbose_name_plural': 'historical asset classes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='location_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.location'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='location_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.location'),
        ),
    ]
