# Generated by Django 5.2.15 on 2026-07-22 03:20

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_depreciationrun_depreciationline_and_more'),
        ('cashbook', '0038_payee_and_petty_cash_cheque'),
        ('departments', '0021_alter_departmentstatuslog_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAcquisition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source', models.CharField(choices=[('PURCHASE', 'Purchased'), ('DONATION', 'Donated (in kind)'), ('CONSTRUCTION', 'Self-constructed'), ('TRANSFER_IN', 'Transferred in'), ('OPENING', 'Opening balance (pre-system)')], db_index=True, default='PURCHASE', max_length=12)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Purchase cost, or fair value for a donation.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('donor_name', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.fixedasset')),
                ('expense', models.ForeignKey(blank=True, db_constraint=False, help_text='The payment that bought or built this asset.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense')),
                ('fund', models.ForeignKey(blank=True, db_constraint=False, help_text='Fund that paid for it, or that a donation is credited to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical acquisition',
                'verbose_name_plural': 'historical acquisitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('PURCHASE', 'Purchased'), ('DONATION', 'Donated (in kind)'), ('CONSTRUCTION', 'Self-constructed'), ('TRANSFER_IN', 'Transferred in'), ('OPENING', 'Opening balance (pre-system)')], db_index=True, default='PURCHASE', max_length=12)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Purchase cost, or fair value for a donation.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('donor_name', models.CharField(blank=True, max_length=120)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_acquisitions_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition', to='assets.fixedasset')),
                ('expense', models.ForeignKey(blank=True, help_text='The payment that bought or built this asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisitions', to='cashbook.expense')),
                ('fund', models.ForeignKey(blank=True, help_text='Fund that paid for it, or that a donation is credited to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_acquisitions', to='departments.department')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_acquisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['source', 'date'], name='assets_acqu_source_3cf962_idx')],
            },
        ),
    ]
