# Generated by Django 5.2.15 on 2026-07-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_assettransfer_historicalassetassignment_and_more'),
        ('vendors', '0002_backfill_from_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier this was purchased from, where they are on the supplier register.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='historicalfixedasset',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The supplier this was purchased from, where they are on the supplier register.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendors.vendor'),
        ),
    ]
