from django.urls import path
from . import views

urlpatterns = [
    path("", views.ReportIndexView.as_view(), name="report_index"),
    path("monthly/", views.MonthlyReportView.as_view(), name="report_monthly"),
    path("offering-summary/", views.OfferingSummaryView.as_view(), name="report_offering"),
    path("envelopes/sabbath/", views.EnvelopeSabbathView.as_view(), name="report_envelope_sabbath"),
    path("envelopes/summary/", views.EnvelopeSummaryView.as_view(), name="report_envelope_summary"),
    path("tithe/", views.TitheReportView.as_view(), name="report_tithe"),
    path("by-group/", views.GroupGivingView.as_view(), name="report_by_group"),
    path("dev-groups/", views.DevGroupProgressView.as_view(), name="report_dev_groups"),
    path("dev-groups/email-all/", views.DevGroupEmailAllView.as_view(), name="dev_groups_email_all"),
    path("dev-groups/excel/", views.DevGroupAllExcelView.as_view(), name="dev_groups_excel"),
    path("dev-groups/unassigned/", views.DevGroupUnassignedView.as_view(), name="dev_unassigned"),

    path("dev-groups/<int:pk>/members/", views.DevGroupMembersView.as_view(), name="report_dev_group_members"),
    path("expenses/", views.ExpenseReportView.as_view(), name="report_expenses"),
    path("income-expenditure/", views.IncomeExpenditureView.as_view(), name="report_ie"),
    path("fund/<int:pk>/", views.FundLedgerView.as_view(), name="report_fund"),
    path("trust/", views.TrustFundView.as_view(), name="report_trust"),
    path("remittance/", views.RemittanceView.as_view(), name="report_remittance"),
    path("remittance/remit/", views.RemitTrustView.as_view(), name="remit_trust"),
    path("member/<int:pk>/", views.MemberStatementView.as_view(), name="report_member"),
    path("cashbook/", views.CashBookView.as_view(), name="report_cashbook"),
    path("reconciliation/", views.ReconciliationView.as_view(), name="report_reconciliation"),
    path("annual/", views.AnnualSummaryView.as_view(), name="report_annual"),
    path("annual/historical/", views.HistoricalYearManageView.as_view(), name="historical_manage"),
    path("accounts-monthly/", views.MonthlyAccountsView.as_view(), name="report_accounts_monthly"),
    path("trust-monthly/", views.TrustMonthlyView.as_view(), name="report_trust_monthly"),
    path("collections-summary/", views.CollectionsSummaryView.as_view(), name="report_collections_summary"),
    path("audit/", views.AuditLogView.as_view(), name="report_audit"),
    path("trust/remittance/", views.RemittanceDashboardView.as_view(), name="remittance_dashboard"),
    path("trust/remittance/batch/new/", views.RemittanceBatchCreateView.as_view(), name="remittance_batch_create"),
    path("trust/remittance/batch/<int:pk>/", views.RemittanceBatchDetailView.as_view(), name="remittance_batch_detail"),
    path("trust/remittance/batch/<int:pk>/approve/", views.RemittanceBatchApproveView.as_view(), name="remittance_batch_approve"),
    path("trust/remittance/batch/<int:pk>/remit/", views.RemittanceBatchRemitView.as_view(), name="remittance_batch_remit"),
    path("trust/remittance/batches/", views.RemittanceBatchListView.as_view(), name="remittance_batch_list"),
    path("budget-vs-actual/", views.BudgetVsActualView.as_view(), name="report_budget_vs_actual"),
    path("budget-board/", views.BudgetBoardReportView.as_view(), name="report_budget_board"),
    path("daily/", views.DailySummaryView.as_view(), name="report_daily"),
    path("weekly/", views.WeeklySummaryView.as_view(), name="report_weekly"),
    path("cash-flow/", views.CashFlowView.as_view(), name="report_cash_flow"),
    path("board/", views.BoardReportView.as_view(), name="report_board"),
    path("pastor/", views.PastorReportView.as_view(), name="report_pastor"),
    path("conference/", views.ConferenceSubmissionView.as_view(), name="report_conference"),
    path("income-statement/", views.IncomeStatementView.as_view(), name="report_income_statement"),
    path("financial-position/", views.FinancialPositionView.as_view(), name="report_financial_position"),
    path("changes-in-net-assets/", views.ChangesInNetAssetsView.as_view(), name="report_changes_net_assets"),
    path("cash-flows/", views.StatementOfCashFlowsView.as_view(), name="report_cash_flows"),
]
