from django.urls import path
from . import views
from . import loan_reports as lr

urlpatterns = [
    path("", views.ReportIndexView.as_view(), name="report_index"),
    path("monthly/", views.MonthlyReportView.as_view(), name="report_monthly"),
    path("offering-summary/", views.OfferingSummaryView.as_view(), name="report_offering"),
    path("envelopes/sabbath/", views.EnvelopeSabbathView.as_view(), name="report_envelope_sabbath"),
    path("envelopes/summary/", views.EnvelopeSummaryView.as_view(), name="report_envelope_summary"),
    path("tithe/", views.TitheReportView.as_view(), name="report_tithe"),
    path("by-group/", views.GroupGivingView.as_view(), name="report_by_group"),
    path("dev-groups/", views.DevGroupProgressView.as_view(), name="report_dev_groups"),
    path("dev-groups/email-all/", views.DevGroupEmailAllView.as_view(), name="dev_groups_email_all"),
    path("dev-groups/excel/", views.DevGroupAllExcelView.as_view(), name="dev_groups_excel"),
    path("dev-groups/unassigned/", views.DevGroupUnassignedView.as_view(), name="dev_unassigned"),
    path("dev-groups/build/", views.DevGroupBuilderView.as_view(), name="dev_group_builder"),

    path("dev-groups/<int:pk>/members/", views.DevGroupMembersView.as_view(), name="report_dev_group_members"),
    path("expenses/", views.ExpenseReportView.as_view(), name="report_expenses"),
    path("income-expenditure/", views.IncomeExpenditureView.as_view(), name="report_ie"),
    path("fund/<int:pk>/", views.FundLedgerView.as_view(), name="report_fund"),
    path("fund/<int:pk>/members/", views.FundMembersView.as_view(), name="report_fund_members"),
    path("trust/", views.TrustFundView.as_view(), name="report_trust"),
    path("remittance/", views.RemittanceView.as_view(), name="report_remittance"),
    path("remittance/remit/", views.RemitTrustView.as_view(), name="remit_trust"),
    path("member/<int:pk>/", views.MemberStatementView.as_view(), name="report_member"),
    path("cashbook/", views.CashBookView.as_view(), name="report_cashbook"),
    path("reconciliation/", views.ReconciliationView.as_view(), name="report_reconciliation"),
    path("bank-position/", views.BankPositionView.as_view(), name="report_bank_position"),
    path("annual/", views.AnnualSummaryView.as_view(), name="report_annual"),
    path("annual/historical/", views.HistoricalYearManageView.as_view(), name="historical_manage"),
    path("accounts-monthly/", views.MonthlyAccountsView.as_view(), name="report_accounts_monthly"),
    path("trust-monthly/", views.TrustMonthlyView.as_view(), name="report_trust_monthly"),
    path("collections-summary/", views.CollectionsSummaryView.as_view(), name="report_collections_summary"),
    path("collections-detail/", views.CollectionsDetailView.as_view(), name="report_collections_detail"),
    path("audit/", views.AuditLogView.as_view(), name="report_audit"),
    path("forecast/", views.CashFlowForecastView.as_view(), name="report_forecast"),
    path("fund/<int:pk>/thank-sms/", views.FundThankSmsView.as_view(), name="fund_thank_sms"),
    path("trust/remittance/", views.RemittanceDashboardView.as_view(), name="remittance_dashboard"),
    path("trust/remittance/batch/new/", views.RemittanceBatchCreateView.as_view(), name="remittance_batch_create"),
    path("trust/remittance/batch/<int:pk>/", views.RemittanceBatchDetailView.as_view(), name="remittance_batch_detail"),
    path("trust/remittance/batch/<int:pk>/approve/", views.RemittanceBatchApproveView.as_view(), name="remittance_batch_approve"),
    path("trust/remittance/batch/<int:pk>/remit/", views.RemittanceBatchRemitView.as_view(), name="remittance_batch_remit"),
    path("trust/remittance/batch/<int:pk>/issue-payment/", views.RemittanceBatchIssuePaymentView.as_view(), name="remittance_batch_issue_payment"),
    path("trust/remittance/batches/", views.RemittanceBatchListView.as_view(), name="remittance_batch_list"),
    path("trust/remittance/calendar/", views.RemittanceCalendarView.as_view(), name="remittance_calendar"),
    path("trust/remittance/calendar/generate/", views.RemittanceCalendarGenerateView.as_view(), name="remittance_calendar_generate"),
    path("trust/remittance/calendar/<int:pk>/update/", views.RemittanceDeadlineUpdateView.as_view(), name="remittance_deadline_update"),
    path("budget-vs-actual/", views.BudgetVsActualView.as_view(), name="report_budget_vs_actual"),
    path("budget-board/", views.BudgetBoardReportView.as_view(), name="report_budget_board"),
    path("daily/", views.DailySummaryView.as_view(), name="report_daily"),
    path("weekly/", views.WeeklySummaryView.as_view(), name="report_weekly"),
    path("cash-flow/", views.CashFlowView.as_view(), name="report_cash_flow"),
    path("board/", views.MonthlyTreasurerReportView.as_view(), name="report_board"),
    path("board/export/excel/", views.MonthlyReportExcelView.as_view(), name="report_board_excel"),
    path("board/export/word/", views.MonthlyReportWordView.as_view(), name="report_board_word"),
    path("board-classic/", views.BoardReportView.as_view(), name="report_board_classic"),
    path("board-settings/", views.BoardReportSettingsView.as_view(), name="board_settings"),
    path("pastor/", views.PastorReportView.as_view(), name="report_pastor"),
    path("conference/", views.ConferenceSubmissionView.as_view(), name="report_conference"),
    path("income-statement/", views.IncomeStatementView.as_view(), name="report_income_statement"),
    path("financial-position/", views.FinancialPositionView.as_view(), name="report_financial_position"),
    path("changes-in-net-assets/", views.ChangesInNetAssetsView.as_view(), name="report_changes_net_assets"),
    path("cash-flows/", views.StatementOfCashFlowsView.as_view(), name="report_cash_flows"),
    # --- Loan liability & financing reports ---
    path("loans/", lr.LoanReportIndexView.as_view(), name="loan_reports"),
    path("loans/liability/", lr.LoanLiabilityScheduleView.as_view(), name="report_loan_liability"),
    path("loans/outstanding/", lr.OutstandingLoansView.as_view(), name="report_loans_outstanding"),
    path("loans/ageing/", lr.LoanAgeingView.as_view(), name="report_loan_ageing"),
    path("loans/maturity/", lr.LoanMaturityView.as_view(), name="report_loan_maturity"),
    path("loans/by-fund/", lr.LoansByFundView.as_view(), name="report_loans_by_fund"),
    path("loans/by-lender/", lr.LoansByLenderView.as_view(), name="report_loans_by_lender"),
    path("loans/repayments/", lr.LoanRepaymentHistoryView.as_view(), name="report_loan_repayments"),
    path("loans/interest/", lr.LoanInterestReportView.as_view(), name="report_loan_interest"),
    path("loans/converted/", lr.LoanConversionsView.as_view(), name="report_loans_converted"),
    path("loans/financing/", lr.FinancingActivitiesView.as_view(), name="report_financing"),
]