# Generated by Django 5.2.15 on 2026-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0002_historicalschememembership_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentcontribution',
            name='kind',
            field=models.CharField(choices=[('DUES', 'Periodic dues'), ('LEVY', 'Per-case levy'), ('FEE', 'Registration or renewal fee'), ('DONATION', 'Donation or gift')], db_index=True, default='DUES', help_text="What kind of money this is. It matters: only DUES count against a member's dues, so a levy paid towards someone else's bereavement — or a registration fee — can never silently clear a member's own arrears.", max_length=8),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcontribution',
            name='kind',
            field=models.CharField(choices=[('DUES', 'Periodic dues'), ('LEVY', 'Per-case levy'), ('FEE', 'Registration or renewal fee'), ('DONATION', 'Donation or gift')], db_index=True, default='DUES', help_text="What kind of money this is. It matters: only DUES count against a member's dues, so a levy paid towards someone else's bereavement — or a registration fee — can never silently clear a member's own arrears.", max_length=8),
        ),
    ]
