# Generated by Django 5.2.15 on 2026-07-11 11:21

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0003_benevolentcontribution_kind_and_more'),
        ('members', '0004_member_members_mem_name_8eb2d0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschemedependant',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Link this dependant to their church-member record where they have one, so their details are never kept in two places.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member'),
        ),
        migrations.AddField(
            model_name='historicalschemedependant',
            name='removed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='died_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='registration_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('HOUSEHOLD', 'Household')], db_index=True, default='INDIVIDUAL', help_text='An individual enrolment, or one subscription covering a household.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='standing',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Deceased'), ('CLOSED', 'Closed'), ('PENDING', 'Pending registration'), ('GOOD', 'Good standing'), ('EXEMPT', 'Exempt'), ('GRACE', 'Grace period'), ('ARREARS', 'In arrears'), ('INACTIVE', 'Inactive')], db_index=True, default='PENDING', editable=False, help_text="Where this member stands under the policy. Derived by benevolent.services.standing.assess() — a pure function of the policy and the facts. This column is a CACHE of that function, so recomputing it can never lose information, and a nightly job writing here can never overwrite a human's decision (which lives on `status`).", max_length=10),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='standing_as_of',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='standing_reason',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='succeeded_from',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The member this enrolment was inherited from, if it was. Their joining date is kept, so the years they paid in are not lost by the household.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member'),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='transferred_to',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Where this membership went, if it was passed to a successor.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.schememembership'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='allow_exemptions',
            field=models.BooleanField(default=True, help_text='Members may be formally excused from contributing (life members, the very old, genuine hardship). Turning this off means no one can be, which some constitutions do insist on.'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='allow_transfers',
            field=models.BooleanField(default=True, help_text='A membership may be passed to a successor (usually the surviving spouse) keeping its original joining date, so the years already paid in are not lost by the household.'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='exemption_age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Members at or over this age are automatically exempt from dues, with no paperwork. 0 = no automatic age exemption.'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='How long a member who has fallen behind stays in GOOD STANDING before they are counted as in arrears. A grace period is a promise that cover does not evaporate the day a payment is late — and while it lasts, the member is covered. 0 = no grace.'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='inactivity_missed_cases',
            field=models.PositiveSmallIntegerField(default=0, help_text='A member who fails to contribute to this many consecutive case levies is inactive. The measure that matters in a levy scheme, where there are no monthly dues to miss — the member who never stands with a bereaved family, and then expects the family to stand with them. 0 = do not measure this.'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='max_household_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='The most people one household registration may cover, including the principal member. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='schemedependant',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Link this dependant to their church-member record where they have one, so their details are never kept in two places.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benevolent_dependencies', to='members.member'),
        ),
        migrations.AddField(
            model_name='schemedependant',
            name='removed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='died_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='registration_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('HOUSEHOLD', 'Household')], db_index=True, default='INDIVIDUAL', help_text='An individual enrolment, or one subscription covering a household.', max_length=10),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='standing',
            field=models.CharField(choices=[('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Deceased'), ('CLOSED', 'Closed'), ('PENDING', 'Pending registration'), ('GOOD', 'Good standing'), ('EXEMPT', 'Exempt'), ('GRACE', 'Grace period'), ('ARREARS', 'In arrears'), ('INACTIVE', 'Inactive')], db_index=True, default='PENDING', editable=False, help_text="Where this member stands under the policy. Derived by benevolent.services.standing.assess() — a pure function of the policy and the facts. This column is a CACHE of that function, so recomputing it can never lose information, and a nightly job writing here can never overwrite a human's decision (which lives on `status`).", max_length=10),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='standing_as_of',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='standing_reason',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='succeeded_from',
            field=models.ForeignKey(blank=True, help_text='The member this enrolment was inherited from, if it was. Their joining date is kept, so the years they paid in are not lost by the household.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='members.member'),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='transferred_to',
            field=models.ForeignKey(blank=True, help_text='Where this membership went, if it was passed to a successor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_from', to='benevolent.schememembership'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='allow_exemptions',
            field=models.BooleanField(default=True, help_text='Members may be formally excused from contributing (life members, the very old, genuine hardship). Turning this off means no one can be, which some constitutions do insist on.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='allow_transfers',
            field=models.BooleanField(default=True, help_text='A membership may be passed to a successor (usually the surviving spouse) keeping its original joining date, so the years already paid in are not lost by the household.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='exemption_age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Members at or over this age are automatically exempt from dues, with no paperwork. 0 = no automatic age exemption.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='How long a member who has fallen behind stays in GOOD STANDING before they are counted as in arrears. A grace period is a promise that cover does not evaporate the day a payment is late — and while it lasts, the member is covered. 0 = no grace.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='inactivity_missed_cases',
            field=models.PositiveSmallIntegerField(default=0, help_text='A member who fails to contribute to this many consecutive case levies is inactive. The measure that matters in a levy scheme, where there are no monthly dues to miss — the member who never stands with a bereaved family, and then expects the family to stand with them. 0 = do not measure this.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='max_household_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='The most people one household registration may cover, including the principal member. 0 = no limit.'),
        ),
        migrations.AlterField(
            model_name='historicalschemedependant',
            name='name',
            field=models.CharField(blank=True, help_text='Only needed for a dependant who is not on the church roll.', max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalschememembership',
            name='household_name',
            field=models.CharField(blank=True, help_text="Under a household registration, the household this enrolment covers (e.g. 'the Otieno household').", max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalschememembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending registration'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Deceased'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='schemedependant',
            name='name',
            field=models.CharField(blank=True, help_text='Only needed for a dependant who is not on the church roll.', max_length=120),
        ),
        migrations.AlterField(
            model_name='schememembership',
            name='household_name',
            field=models.CharField(blank=True, help_text="Under a household registration, the household this enrolment covers (e.g. 'the Otieno household').", max_length=120),
        ),
        migrations.AlterField(
            model_name='schememembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending registration'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Deceased'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipExemption',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LIFE', 'Life member'), ('AGE', 'Age'), ('HARDSHIP', 'Hardship'), ('BEREAVEMENT', 'Recently bereaved'), ('SERVICE', 'Church service (pastor, elder)'), ('OTHER', 'Other')], max_length=12)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(blank=True, help_text='Leave blank for an exemption with no end (a life member).', null=True)),
                ('reason', models.TextField(help_text='Why. Kept on the permanent record — an exemption without a recorded reason is indistinguishable from favouritism.')),
                ('exempt_dues', models.BooleanField(default=True, help_text='Excused from periodic dues.')),
                ('exempt_levies', models.BooleanField(default=False, help_text='Excused from per-case levies too. Rarer: most schemes still ask an exempt member to stand with a bereaved family.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_on', models.DateField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, help_text='An exemption relieves someone of a financial obligation, so it is approved by someone other than whoever proposed it.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.schememembership')),
            ],
            options={
                'verbose_name': 'historical membership exemption',
                'verbose_name_plural': 'historical membership exemptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MembershipExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LIFE', 'Life member'), ('AGE', 'Age'), ('HARDSHIP', 'Hardship'), ('BEREAVEMENT', 'Recently bereaved'), ('SERVICE', 'Church service (pastor, elder)'), ('OTHER', 'Other')], max_length=12)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(blank=True, help_text='Leave blank for an exemption with no end (a life member).', null=True)),
                ('reason', models.TextField(help_text='Why. Kept on the permanent record — an exemption without a recorded reason is indistinguishable from favouritism.')),
                ('exempt_dues', models.BooleanField(default=True, help_text='Excused from periodic dues.')),
                ('exempt_levies', models.BooleanField(default=False, help_text='Excused from per-case levies too. Rarer: most schemes still ask an exempt member to stand with a bereaved family.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_on', models.DateField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='An exemption relieves someone of a financial obligation, so it is approved by someone other than whoever proposed it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='benevolent.schememembership')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('ADMITTED', 'Admitted'), ('REJECTED', 'Registration refused'), ('FEE_PAID', 'Fee paid'), ('RENEWED', 'Renewed'), ('SUSPENDED', 'Suspended'), ('REINSTATED', 'Reinstated'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Recorded as deceased'), ('CLOSED', 'Closed'), ('TRANS_OUT', 'Membership transferred away'), ('TRANS_IN', 'Membership taken over'), ('EXEMPTED', 'Exemption granted'), ('EXEMPT_END', 'Exemption ended'), ('DEP_ADD', 'Dependant registered'), ('DEP_REM', 'Dependant removed'), ('STANDING', 'Standing changed'), ('NOTE', 'Note')], db_index=True, max_length=12)),
                ('on', models.DateField(db_index=True, default=datetime.date.today, help_text='The date the thing happened (not when it was typed in).')),
                ('summary', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('from_value', models.CharField(blank=True, max_length=24)),
                ('to_value', models.CharField(blank=True, max_length=24)),
                ('automated', models.BooleanField(db_index=True, default=False, help_text='Recorded by a job rather than a person. Kept visibly distinct: a member has a right to know whether a human decided this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='benevolent.schememembership')),
            ],
            options={
                'ordering': ['-on', '-created_at'],
                'indexes': [models.Index(fields=['membership', '-on'], name='benevolent__members_fcfd68_idx')],
            },
        ),
    ]
