# Generated by Django 5.2.15 on 2026-07-11 17:22

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0007_migrate_contribution_kinds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # bereaved_exempt_own_levy is deliberately NOT removed here. It is
        # removed in 0010, after 0009 has translated every existing value into
        # the new bereaved_contribution_policy — a data migration needs the old
        # column to still exist to read it.
        migrations.AddField(
            model_name='benevolentcase',
            name='bereaved_levy_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benevolentcase',
            name='bereaved_levy_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benevolentcase',
            name='bereaved_levy_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='benevolentcase',
            name='bereaved_levy_waived',
            field=models.BooleanField(blank=True, default=None, help_text='Only meaningful under a COMMITTEE_DECIDES bereaved policy. None = not yet decided (the member is left off the levy roster while it is pending — nobody chases a grieving family on the strength of a rule nobody has actually applied yet). True = waived for this case. False = they contribute as normal.', null=True),
        ),
        migrations.AddField(
            model_name='benevolentcase',
            name='funding_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount this case is aiming to raise or receive. Optional, and separate from the assessed/approved benefit — a goal to track progress against, not a rule the policy enforces.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='benevolentcase',
            name='funding_target_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benevolentcase',
            name='funding_target_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benevolenteventtype',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text="Named documents this event needs (e.g. 'Burial permit', 'Death certificate'), one per line in the form. A case shows each as a checklist item rather than a single yes/no. Leave empty to fall back to the plain requires_document toggle above (at least one attachment of any kind)."),
        ),
        migrations.AddField(
            model_name='caseattachment',
            name='document_type',
            field=models.CharField(blank=True, help_text="Matched against the event type's required_documents checklist, where it has one. Free text otherwise.", max_length=120),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='bereaved_levy_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='bereaved_levy_decided_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='bereaved_levy_decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='bereaved_levy_waived',
            field=models.BooleanField(blank=True, default=None, help_text='Only meaningful under a COMMITTEE_DECIDES bereaved policy. None = not yet decided (the member is left off the levy roster while it is pending — nobody chases a grieving family on the strength of a rule nobody has actually applied yet). True = waived for this case. False = they contribute as normal.', null=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='funding_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount this case is aiming to raise or receive. Optional, and separate from the assessed/approved benefit — a goal to track progress against, not a rule the policy enforces.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='funding_target_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='funding_target_set_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbenevolenteventtype',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text="Named documents this event needs (e.g. 'Burial permit', 'Death certificate'), one per line in the form. A case shows each as a checklist item rather than a single yes/no. Leave empty to fall back to the plain requires_document toggle above (at least one attachment of any kind)."),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='bereaved_contribution_policy',
            field=models.CharField(choices=[('CONTRIBUTES', 'Contributes like any other member'), ('REDUCED', 'Contributes a reduced amount'), ('EXEMPT', 'Automatically exempt'), ('COMMITTEE_DECIDES', 'The committee decides, case by case')], default='EXEMPT', help_text='Whether the member a case is FOR still has to pay into it — the levy round, or their own dues. EXEMPT is what almost every real constitution says: asking a grieving family to chip in for their own benefit is the thing schemes explicitly write down that they do not do.', max_length=18),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='bereaved_reduction_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Under REDUCED, what percentage of the normal amount the bereaved member is asked for.', max_digits=5),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='bereaved_contribution_policy',
            field=models.CharField(choices=[('CONTRIBUTES', 'Contributes like any other member'), ('REDUCED', 'Contributes a reduced amount'), ('EXEMPT', 'Automatically exempt'), ('COMMITTEE_DECIDES', 'The committee decides, case by case')], default='EXEMPT', help_text='Whether the member a case is FOR still has to pay into it — the levy round, or their own dues. EXEMPT is what almost every real constitution says: asking a grieving family to chip in for their own benefit is the thing schemes explicitly write down that they do not do.', max_length=18),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='bereaved_reduction_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Under REDUCED, what percentage of the normal amount the bereaved member is asked for.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalschemepolicy',
            name='bereaved_deduct_own_levy',
            field=models.BooleanField(default=False, help_text='Where the bereaved member DOES contribute (CONTRIBUTES or REDUCED), collect it by taking it out of their own benefit rather than asking them to pay it up front like everyone else. They are then left OFF the levy roster — being asked to pay in AND having it deducted would charge them twice.'),
        ),
        migrations.AlterField(
            model_name='historicalschemepolicy',
            name='bereaved_dues_waiver_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='Months of ordinary periodic dues waived for a member after their own case — independent of the levy question above; a scheme can waive dues, exempt the levy, both, or neither. 0 = no waiver. Where this applies and the levy policy is EXEMPT, the waiver is granted as a visible, auditable exemption (see benevolent.services.registry) rather than a silent adjustment to arrears — a member has a right to see why they owe nothing, the same as for any other exemption.'),
        ),
        migrations.AlterField(
            model_name='schemepolicy',
            name='bereaved_deduct_own_levy',
            field=models.BooleanField(default=False, help_text='Where the bereaved member DOES contribute (CONTRIBUTES or REDUCED), collect it by taking it out of their own benefit rather than asking them to pay it up front like everyone else. They are then left OFF the levy roster — being asked to pay in AND having it deducted would charge them twice.'),
        ),
        migrations.AlterField(
            model_name='schemepolicy',
            name='bereaved_dues_waiver_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='Months of ordinary periodic dues waived for a member after their own case — independent of the levy question above; a scheme can waive dues, exempt the levy, both, or neither. 0 = no waiver. Where this applies and the levy policy is EXEMPT, the waiver is granted as a visible, auditable exemption (see benevolent.services.registry) rather than a silent adjustment to arrears — a member has a right to see why they owe nothing, the same as for any other exemption.'),
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RAISED', 'Case raised'), ('SUBMITTED', 'Submitted for assessment'), ('ASSESSED', 'Assessed'), ('COMM_VOTE', 'Committee decision recorded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PAY_RAISED', 'Payment voucher raised'), ('PAY_PAID', 'Payment voucher paid'), ('PAY_REV', 'Payment voucher reversed or rejected'), ('CLOSED', 'Closed'), ('DOC_ADD', 'Document attached'), ('FUND_TGT', 'Funding target set'), ('FUND_MET', 'Funding target reached'), ('BER_DEC', "Bereaved member's contribution decided"), ('EXEMPTED', 'Bereavement exemption granted'), ('NOTE', 'Note')], db_index=True, max_length=10)),
                ('on', models.DateField(db_index=True, default=datetime.date.today, help_text='The date the thing happened (not when it was typed in).')),
                ('summary', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('automated', models.BooleanField(db_index=True, default=False, help_text="Recorded by a job or a policy-driven rule rather than a person's direct action in the moment.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='benevolent.benevolentcase')),
            ],
            options={
                'ordering': ['-on', '-created_at'],
                'indexes': [models.Index(fields=['case', '-on'], name='benevolent__case_id_98b523_idx')],
            },
        ),
    ]
