# Generated by Django 5.2.15 on 2026-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0010_remove_bereaved_exempt_own_levy'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_on_funding_target_reached',
            field=models.BooleanField(default=True, help_text="Tell staff the moment a case's funding target has been fully raised — fires once per case, the first time it happens."),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_on_funding_target_reached',
            field=models.BooleanField(default=True, help_text="Tell staff the moment a case's funding target has been fully raised — fires once per case, the first time it happens."),
        ),
    ]
