# Generated by Django 5.2.15 on 2026-07-11 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0011_benevolentsettings_notify_on_funding_target_reached_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmemberadjustment',
            name='automated',
            field=models.BooleanField(db_index=True, default=False, help_text="Raised by a published policy rule (e.g. a reinstatement fee) rather than a treasurer's own discretionary judgement. A member has a right to know which."),
        ),
        migrations.AddField(
            model_name='historicalmemberadjustment',
            name='comments',
            field=models.TextField(blank=True, help_text='Anything supplementary — not a substitute for the reason above.'),
        ),
        migrations.AddField(
            model_name='historicalmemberadjustment',
            name='policy',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The policy version in force when this was raised.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.schemepolicy'),
        ),
        migrations.AddField(
            model_name='historicalmembershipexemption',
            name='comments',
            field=models.TextField(blank=True, help_text='Anything supplementary — discussion at the meeting that granted it, a minute reference. Not a substitute for the reason above; purely additional context.'),
        ),
        migrations.AddField(
            model_name='historicalmembershipexemption',
            name='policy',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The policy version in force when this was granted — so a later policy change can never retroactively make this exemption look like it was decided under rules that did not yet exist.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.schemepolicy'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='committee_requires_chair',
            field=models.BooleanField(default=False, help_text="An approval level, not just a headcount: when set, the quorum is not reached by any N approvals — one of them must be the Chair's. Only meaningful where the scheme has a committee roster with a Chair seat (see Committee membership); ignored otherwise, since there is no Chair to require."),
        ),
        migrations.AddField(
            model_name='memberadjustment',
            name='automated',
            field=models.BooleanField(db_index=True, default=False, help_text="Raised by a published policy rule (e.g. a reinstatement fee) rather than a treasurer's own discretionary judgement. A member has a right to know which."),
        ),
        migrations.AddField(
            model_name='memberadjustment',
            name='comments',
            field=models.TextField(blank=True, help_text='Anything supplementary — not a substitute for the reason above.'),
        ),
        migrations.AddField(
            model_name='memberadjustment',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='The policy version in force when this was raised.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='benevolent.schemepolicy'),
        ),
        migrations.AddField(
            model_name='membershipexemption',
            name='comments',
            field=models.TextField(blank=True, help_text='Anything supplementary — discussion at the meeting that granted it, a minute reference. Not a substitute for the reason above; purely additional context.'),
        ),
        migrations.AddField(
            model_name='membershipexemption',
            name='policy',
            field=models.ForeignKey(blank=True, help_text='The policy version in force when this was granted — so a later policy change can never retroactively make this exemption look like it was decided under rules that did not yet exist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='benevolent.schemepolicy'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='committee_requires_chair',
            field=models.BooleanField(default=False, help_text="An approval level, not just a headcount: when set, the quorum is not reached by any N approvals — one of them must be the Chair's. Only meaningful where the scheme has a committee roster with a Chair seat (see Committee membership); ignored otherwise, since there is no Chair to require."),
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CHAIR', 'Chair'), ('VICE_CHAIR', 'Vice-chair'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Committee treasurer'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, max_length=200)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='benevolent.benevolentscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benevolent_committee_seats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheme', 'role', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'user'), name='uniq_committee_seat_per_scheme')],
            },
        ),
    ]
