# Generated by Django 5.2.15 on 2026-07-11 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0012_phase6_committee_and_policy_refs'),
        ('core', '0050_alter_historicalsiteconfig_numbered_fund_families_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_committee_vote_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_arrears_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_case_decided',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_case_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_payout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_renewal_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_renewal_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='notify_member_status_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='reminder_min_gap_days',
            field=models.PositiveIntegerField(default=14, help_text='However often the automation job runs, do not send the SAME member the SAME reminder (arrears or renewal) more often than this many days apart. A nightly job with no gap would text someone in arrears every single night.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_committee_vote_needed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_arrears_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_case_decided',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_case_received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_payout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_renewal_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_renewal_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='notify_member_status_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='reminder_min_gap_days',
            field=models.PositiveIntegerField(default=14, help_text='However often the automation job runs, do not send the SAME member the SAME reminder (arrears or renewal) more often than this many days apart. A nightly job with no gap would text someone in arrears every single night.'),
        ),
        migrations.AddField(
            model_name='historicalschememembership',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. members.Member has no email field at all (the church tracks members by name and phone) — this is scoped to the benevolent module specifically, for a member who wants email notices about their own scheme membership. Blank means email notifications simply do not fire for them; SMS to their phone still does.', max_length=254),
        ),
        migrations.AddField(
            model_name='schememembership',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. members.Member has no email field at all (the church tracks members by name and phone) — this is scoped to the benevolent module specifically, for a member who wants email notices about their own scheme membership. Blank means email notifications simply do not fire for them; SMS to their phone still does.', max_length=254),
        ),
        migrations.CreateModel(
            name='BenevolentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('REGISTRATION_CONFIRMED', 'Registration confirmed'), ('RENEWAL_REMINDER', 'Renewal due soon'), ('RENEWAL_CONFIRMED', 'Renewal received'), ('ARREARS_REMINDER', 'Contribution / arrears reminder'), ('CASE_RECEIVED', 'Case received'), ('CASE_DECIDED', 'Case decided (approved or rejected)'), ('PAYOUT_MADE', 'Benefit paid'), ('MEMBERSHIP_STATUS_CHANGED', 'Membership status changed'), ('COMMITTEE_VOTE_NEEDED', 'Committee decision needed')], db_index=True, max_length=32)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=6)),
                ('recipient', models.CharField(help_text='The phone number or email address actually used.', max_length=120)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (no recipient / disabled)')], db_index=True, default='QUEUED', max_length=8)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='benevolent.benevolentcase')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='benevolent.schememembership')),
                ('sms_log', models.ForeignKey(blank=True, help_text='The authoritative SMS delivery record, where the channel is SMS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.smslog')),
                ('user', models.ForeignKey(blank=True, help_text='Set instead of membership when the recipient is a committee member, not a scheme member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='benevolent__status_6d2099_idx'), models.Index(fields=['event', '-created_at'], name='benevolent__event_058977_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('REGISTRATION_CONFIRMED', 'Registration confirmed'), ('RENEWAL_REMINDER', 'Renewal due soon'), ('RENEWAL_CONFIRMED', 'Renewal received'), ('ARREARS_REMINDER', 'Contribution / arrears reminder'), ('CASE_RECEIVED', 'Case received'), ('CASE_DECIDED', 'Case decided (approved or rejected)'), ('PAYOUT_MADE', 'Benefit paid'), ('MEMBERSHIP_STATUS_CHANGED', 'Membership status changed'), ('COMMITTEE_VOTE_NEEDED', 'Committee decision needed')], db_index=True, max_length=32)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=6)),
                ('subject', models.CharField(blank=True, help_text='Email only. SMS has no subject line.', max_length=120)),
                ('body', models.TextField()),
                ('active', models.BooleanField(default=True, help_text='Switched off, this event sends nothing on this channel — the member-facing/committee toggle in settings decides whether the event fires at all; this decides whether THIS channel does.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('event', 'channel'), name='uniq_template_per_event_channel')],
            },
        ),
    ]
