# Generated by Django 5.2.15 on 2026-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0018_remove_notify_committee_on_pending_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseevent',
            name='kind',
            field=models.CharField(choices=[('RAISED', 'Case raised'), ('SUBMITTED', 'Submitted for assessment'), ('ASSESSED', 'Assessed'), ('COMM_VOTE', 'Committee decision recorded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PAY_RAISED', 'Payment voucher raised'), ('PAY_PAID', 'Payment voucher paid'), ('PAY_REV', 'Payment voucher reversed or rejected'), ('CLOSED', 'Closed'), ('DOC_ADD', 'Document attached'), ('FUND_TGT', 'Funding target set'), ('FUND_MET', 'Funding target reached'), ('BER_DEC', "Bereaved member's contribution decided"), ('EXEMPTED', 'Bereavement exemption granted'), ('FUNDED_BAL', 'Funded from the fund balance, not a levy'), ('NOTE', 'Note')], db_index=True, max_length=10),
        ),
    ]
