# Generated by Django 5.2.15 on 2026-07-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0019_phase11_funded_from_balance_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='require_different_approver',
            field=models.BooleanField(default=True, help_text='A benefit must be approved by someone other than the person who raised the case — segregation of duties for a money decision. Switch this off only for a scheme small enough that the same person genuinely has to do both (e.g. a single treasurer with no assistant); the recommended, safer default is to leave it on. Never applies where approval is routed to the committee — a committee decision already requires more than one person by its own quorum, regardless of this setting.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='require_different_approver',
            field=models.BooleanField(default=True, help_text='A benefit must be approved by someone other than the person who raised the case — segregation of duties for a money decision. Switch this off only for a scheme small enough that the same person genuinely has to do both (e.g. a single treasurer with no assistant); the recommended, safer default is to leave it on. Never applies where approval is routed to the committee — a committee decision already requires more than one person by its own quorum, regardless of this setting.'),
        ),
    ]
