# Generated by Django 5.2.15 on 2026-07-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0020_require_different_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschemedependant',
            name='died_on',
            field=models.DateField(blank=True, help_text='Set only when this dependant is recorded as deceased — distinct from removed_on, which is set for ANY reason a dependant leaves cover (moved away, aged out, a correction). A case can still be raised for them after this; see BenevolentCase.dependant.', null=True),
        ),
        migrations.AddField(
            model_name='schemedependant',
            name='died_on',
            field=models.DateField(blank=True, help_text='Set only when this dependant is recorded as deceased — distinct from removed_on, which is set for ANY reason a dependant leaves cover (moved away, aged out, a correction). A case can still be raised for them after this; see BenevolentCase.dependant.', null=True),
        ),
        migrations.AlterField(
            model_name='membershipevent',
            name='kind',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('ADMITTED', 'Admitted'), ('REJECTED', 'Registration refused'), ('FEE_PAID', 'Fee paid'), ('RENEWED', 'Renewed'), ('SUSPENDED', 'Suspended'), ('REINSTATED', 'Reinstated'), ('WITHDRAWN', 'Withdrawn'), ('DECEASED', 'Recorded as deceased'), ('CLOSED', 'Closed'), ('TRANS_OUT', 'Membership transferred away'), ('TRANS_IN', 'Membership taken over'), ('EXEMPTED', 'Exemption granted'), ('EXEMPT_END', 'Exemption ended'), ('DEP_ADD', 'Dependant registered'), ('DEP_REM', 'Dependant removed'), ('DEP_DEC', 'Dependant recorded as deceased'), ('STANDING', 'Standing changed'), ('NOTE', 'Note')], db_index=True, max_length=12),
        ),
    ]
