# Generated by Django 5.2.15 on 2026-07-13 15:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0021_dependant_deceased'),
        ('members', '0004_member_members_mem_name_8eb2d0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentsettings',
            name='public_form_enabled',
            field=models.BooleanField(default=False, help_text='Allow people to apply to join a scheme from a public link, with no login. Submissions are held as UNVERIFIED applications for a registration officer to review — an application is not a membership, is not covered, owes nothing and can claim nothing until somebody approves it. Off by default, deliberately: a public form that could create cover would be a public form that could create liabilities.'),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='public_form_intro',
            field=models.TextField(blank=True, help_text="Shown at the top of the public form — the church's own words about what the scheme is and what joining means."),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='public_form_scheme',
            field=models.ForeignKey(blank=True, help_text='Which scheme the public form applies to. Leave blank and applicants choose from the active schemes themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='benevolent.benevolentscheme'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='public_form_enabled',
            field=models.BooleanField(default=False, help_text='Allow people to apply to join a scheme from a public link, with no login. Submissions are held as UNVERIFIED applications for a registration officer to review — an application is not a membership, is not covered, owes nothing and can claim nothing until somebody approves it. Off by default, deliberately: a public form that could create cover would be a public form that could create liabilities.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='public_form_intro',
            field=models.TextField(blank=True, help_text="Shown at the top of the public form — the church's own words about what the scheme is and what joining means."),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='public_form_scheme',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Which scheme the public form applies to. Leave blank and applicants choose from the active schemes themselves.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.benevolentscheme'),
        ),
        migrations.CreateModel(
            name='BenevolentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('standing', models.CharField(choices=[('MEMBER', 'A registered church member'), ('SABBATH_SCHOOL', 'A Sabbath School member'), ('VISITOR', 'A visitor / not yet a member')], default='VISITOR', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, help_text='Optional. Some churches ask for it; many do not, and it is not required to apply.', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Anything else the applicant wanted the church to know.')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting review'), ('APPROVED', 'Approved and registered'), ('REJECTED', 'Not accepted'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('matched_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benevolent_applications', to='members.member')),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_application', to='benevolent.schememembership')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='benevolent.benevolentscheme')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('OTHER', 'Other dependant')], max_length=8)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, help_text='Optional, and worth asking for: a spouse or grown child very often pays from their OWN line, and a number recorded here lets that payment be matched to the family automatically instead of landing in an unmatched queue.', max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='benevolent.benevolentapplication')),
            ],
            options={
                'ordering': ['relationship', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBenevolentApplication',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('standing', models.CharField(choices=[('MEMBER', 'A registered church member'), ('SABBATH_SCHOOL', 'A Sabbath School member'), ('VISITOR', 'A visitor / not yet a member')], default='VISITOR', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, help_text='Optional. Some churches ask for it; many do not, and it is not required to apply.', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Anything else the applicant wanted the church to know.')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting review'), ('APPROVED', 'Approved and registered'), ('REJECTED', 'Not accepted'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member')),
                ('membership', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.schememembership')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.benevolentscheme')),
            ],
            options={
                'verbose_name': 'historical benevolent application',
                'verbose_name_plural': 'historical benevolent applications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='benevolentapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='benevolent__status_141623_idx'),
        ),
    ]
