# Generated by Django 5.2.15 on 2026-07-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0022_public_application_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentcase',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, help_text="How the beneficiary relates to the member — 'Father to Grace', 'Husband to Zipporah'. Filled in automatically when the beneficiary is a registered dependant; typed here when they are not. This is the line the congregation actually reads on the case statement, and a church's own records have always carried it.", max_length=80),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='beneficiary_relationship',
            field=models.CharField(blank=True, help_text="How the beneficiary relates to the member — 'Father to Grace', 'Husband to Zipporah'. Filled in automatically when the beneficiary is a registered dependant; typed here when they are not. This is the line the congregation actually reads on the case statement, and a church's own records have always carried it.", max_length=80),
        ),
    ]
