# Generated by Django 5.2.15 on 2026-07-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0023_beneficiary_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolenteventtype',
            name='triggers_on_death',
            field=models.BooleanField(default=False, help_text='This is the event a death is claimed under. When a member or a registered dependant is recorded as deceased, the scheme can auto-open a draft case under this event type (see the module settings). Mark exactly one event type per scheme — the bereavement/funeral one.'),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='auto_open_case_on_death',
            field=models.CharField(choices=[('OFF', 'Do not auto-open — the treasurer raises every case by hand'), ('ON_RECORD', 'Open a draft case when a death is recorded through the register (tied to who recorded it)'), ('ALWAYS', 'Open a draft case whenever a death is recorded anywhere in the system')], default='ON_RECORD', help_text="Whether recording a death should auto-open a draft benevolent case. The draft is filled from what the scheme already knows (event type, beneficiary, relationship, the policy's fixed benefit) and left for the treasurer to review and submit — it is never auto-submitted or auto-paid. Recommended: open on record, so every death the register knows about surfaces as a case nobody has to remember to raise.", max_length=10),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='case_beneficiary_default',
            field=models.CharField(choices=[('DERIVE', 'Derive from who died — the member, or the dependant and their relationship'), ('BLANK', 'Leave the beneficiary blank for the treasurer to choose')], default='DERIVE', help_text="On an auto-opened or new case, who the benefit is presumed for. Deriving it means a dependant's death pre-selects that dependant (and fills the relationship the database already holds), and a member's own death names the member. The treasurer can always change it before submitting.", max_length=8),
        ),
        migrations.AddField(
            model_name='historicalbenevolenteventtype',
            name='triggers_on_death',
            field=models.BooleanField(default=False, help_text='This is the event a death is claimed under. When a member or a registered dependant is recorded as deceased, the scheme can auto-open a draft case under this event type (see the module settings). Mark exactly one event type per scheme — the bereavement/funeral one.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='auto_open_case_on_death',
            field=models.CharField(choices=[('OFF', 'Do not auto-open — the treasurer raises every case by hand'), ('ON_RECORD', 'Open a draft case when a death is recorded through the register (tied to who recorded it)'), ('ALWAYS', 'Open a draft case whenever a death is recorded anywhere in the system')], default='ON_RECORD', help_text="Whether recording a death should auto-open a draft benevolent case. The draft is filled from what the scheme already knows (event type, beneficiary, relationship, the policy's fixed benefit) and left for the treasurer to review and submit — it is never auto-submitted or auto-paid. Recommended: open on record, so every death the register knows about surfaces as a case nobody has to remember to raise.", max_length=10),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='case_beneficiary_default',
            field=models.CharField(choices=[('DERIVE', 'Derive from who died — the member, or the dependant and their relationship'), ('BLANK', 'Leave the beneficiary blank for the treasurer to choose')], default='DERIVE', help_text="On an auto-opened or new case, who the benefit is presumed for. Deriving it means a dependant's death pre-selects that dependant (and fills the relationship the database already holds), and a member's own death names the member. The treasurer can always change it before submitting.", max_length=8),
        ),
    ]
