# Generated by Django 5.2.15 on 2026-07-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0024_benevolenteventtype_triggers_on_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentsettings',
            name='apportion_to_obligations',
            field=models.BooleanField(default=True, help_text='When an identified member pays, apply the money to what they owe — registration first, then case levies oldest-first — splitting one payment across several obligations where it covers more than one (e.g. clearing two cases in arrears at once). With this off, a payment is recorded as a single contribution and a treasurer allocates it by hand.'),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='auto_allocate_single_open_case',
            field=models.BooleanField(default=True, help_text='When a scheme has exactly ONE open case and an identified member pays the levy amount, attach it to that case automatically — there is only one thing it can be. If that member has ALREADY paid their levy for the case, the payment goes to the review queue instead of being posted twice.'),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='review_multi_obligation_payments',
            field=models.BooleanField(default=False, help_text='Send a payment that would be split across MORE THAN ONE obligation (e.g. two cases in arrears) to the review queue for a treasurer to confirm the split, rather than applying it automatically. Off by default — the oldest-first split is usually exactly right — but some treasurers prefer to confirm.'),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='review_overpayments',
            field=models.BooleanField(default=True, help_text='Send a payment that is larger than everything the member owes to the review queue, so a treasurer decides whether the extra is a genuine voluntary gift or a misread amount, rather than it being auto-posted as a voluntary contribution.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='apportion_to_obligations',
            field=models.BooleanField(default=True, help_text='When an identified member pays, apply the money to what they owe — registration first, then case levies oldest-first — splitting one payment across several obligations where it covers more than one (e.g. clearing two cases in arrears at once). With this off, a payment is recorded as a single contribution and a treasurer allocates it by hand.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='auto_allocate_single_open_case',
            field=models.BooleanField(default=True, help_text='When a scheme has exactly ONE open case and an identified member pays the levy amount, attach it to that case automatically — there is only one thing it can be. If that member has ALREADY paid their levy for the case, the payment goes to the review queue instead of being posted twice.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='review_multi_obligation_payments',
            field=models.BooleanField(default=False, help_text='Send a payment that would be split across MORE THAN ONE obligation (e.g. two cases in arrears) to the review queue for a treasurer to confirm the split, rather than applying it automatically. Off by default — the oldest-first split is usually exactly right — but some treasurers prefer to confirm.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='review_overpayments',
            field=models.BooleanField(default=True, help_text='Send a payment that is larger than everything the member owes to the review queue, so a treasurer decides whether the extra is a genuine voluntary gift or a misread amount, rather than it being auto-posted as a voluntary contribution.'),
        ),
    ]
