# Generated by Django 5.2.15 on 2026-07-15 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0025_benevolentsettings_apportion_to_obligations_and_more'),
        ('cashbook', '0038_payee_and_petty_cash_cheque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentcase',
            name='external_reference',
            field=models.CharField(blank=True, help_text="A pre-existing reference for this case from before it was on this system — a paper file number, a spreadsheet row, a minute-book entry. Purely for a treasurer to cross-check against old records; the system's own `number` above is what everything internally refers to. Set once, on import, and not otherwise editable through the case form.", max_length=40),
        ),
        migrations.AddField(
            model_name='benevolentpayout',
            name='historical_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used when is_historical is True (no linked Expense).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='benevolentpayout',
            name='historical_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benevolentpayout',
            name='is_historical',
            field=models.BooleanField(default=False, help_text="A payment recorded from the church's pre-system records, not raised through the live expense workflow. See historical_amount."),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcase',
            name='external_reference',
            field=models.CharField(blank=True, help_text="A pre-existing reference for this case from before it was on this system — a paper file number, a spreadsheet row, a minute-book entry. Purely for a treasurer to cross-check against old records; the system's own `number` above is what everything internally refers to. Set once, on import, and not otherwise editable through the case form.", max_length=40),
        ),
        migrations.AddField(
            model_name='historicalbenevolentpayout',
            name='historical_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used when is_historical is True (no linked Expense).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentpayout',
            name='historical_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentpayout',
            name='is_historical',
            field=models.BooleanField(default=False, help_text="A payment recorded from the church's pre-system records, not raised through the live expense workflow. See historical_amount."),
        ),
        migrations.AlterField(
            model_name='benevolentpayout',
            name='expense',
            field=models.OneToOneField(blank=True, help_text='The voucher that carries the money. Authoritative for amount, approval and payment. Blank for a historical payout — see below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benevolent_payout', to='cashbook.expense'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='kind',
            field=models.CharField(choices=[('RAISED', 'Case raised'), ('SUBMITTED', 'Submitted for assessment'), ('ASSESSED', 'Assessed'), ('COMM_VOTE', 'Committee decision recorded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PAY_RAISED', 'Payment voucher raised'), ('PAY_PAID', 'Payment voucher paid'), ('PAY_REV', 'Payment voucher reversed or rejected'), ('CLOSED', 'Closed'), ('DOC_ADD', 'Document attached'), ('FUND_TGT', 'Funding target set'), ('FUND_MET', 'Funding target reached'), ('BER_DEC', "Bereaved member's contribution decided"), ('EXEMPTED', 'Bereavement exemption granted'), ('FUNDED_BAL', 'Funded from the fund balance, not a levy'), ('IMPORTED', 'Imported from historical records'), ('NOTE', 'Note')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalbenevolentpayout',
            name='expense',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The voucher that carries the money. Authoritative for amount, approval and payment. Blank for a historical payout — see below.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense'),
        ),
        migrations.AddIndex(
            model_name='benevolentcase',
            index=models.Index(fields=['scheme', 'external_reference'], name='benevolent__scheme__21221e_idx'),
        ),
    ]
