# Generated by Django 5.2.15 on 2026-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0026_benevolentcase_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='inactivity_missed_cases_window',
            field=models.CharField(choices=[('CONSECUTIVE', 'Consecutive — an unbroken run of misses, most recent first'), ('ROLLING_YEAR', 'Any within the last 12 months')], default='CONSECUTIVE', help_text="How a 'missed case' streak is counted. Consecutive (the original, and the safer default) only catches an unbroken run of misses ending at the most recent case — someone who missed three levies two years ago but has paid every one since is not flagged. Rolling year instead counts ANY missed levies in the last 12 months, even with paid ones in between — a policy that wants to catch a member who pays sporadically, not just one who has stopped paying outright.", max_length=12),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='inactivity_missed_cases_window',
            field=models.CharField(choices=[('CONSECUTIVE', 'Consecutive — an unbroken run of misses, most recent first'), ('ROLLING_YEAR', 'Any within the last 12 months')], default='CONSECUTIVE', help_text="How a 'missed case' streak is counted. Consecutive (the original, and the safer default) only catches an unbroken run of misses ending at the most recent case — someone who missed three levies two years ago but has paid every one since is not flagged. Rolling year instead counts ANY missed levies in the last 12 months, even with paid ones in between — a policy that wants to catch a member who pays sporadically, not just one who has stopped paying outright.", max_length=12),
        ),
        migrations.AlterField(
            model_name='historicalschemepolicy',
            name='inactivity_missed_cases',
            field=models.PositiveSmallIntegerField(default=0, help_text='A member who fails to contribute to this many case levies is inactive — see the window setting below for how the misses are counted. The measure that matters in a levy scheme, where there are no monthly dues to miss — the member who never stands with a bereaved family, and then expects the family to stand with them. 0 = do not measure this.'),
        ),
        migrations.AlterField(
            model_name='schemepolicy',
            name='inactivity_missed_cases',
            field=models.PositiveSmallIntegerField(default=0, help_text='A member who fails to contribute to this many case levies is inactive — see the window setting below for how the misses are counted. The measure that matters in a levy scheme, where there are no monthly dues to miss — the member who never stands with a bereaved family, and then expects the family to stand with them. 0 = do not measure this.'),
        ),
    ]
