# Generated by Django 5.2.15 on 2026-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0027_historicalschemepolicy_inactivity_missed_cases_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='catch_up_requalify_days',
            field=models.PositiveIntegerField(default=0, help_text='When catch-up does NOT restore eligibility immediately, how many days a member must remain paid-up after clearing arrears before a claim qualifies again. 0 = no re-qualification period.'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='catch_up_restores_eligibility',
            field=models.BooleanField(default=True, help_text='When a member clears their arrears, does eligibility come back immediately? On (the humane default) = yes, paying up restores cover at once. Off = clearing arrears is necessary but the member must then serve the re-qualification period below before claiming again — a guard against someone paying up only once a death has already occurred.'),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='max_arrears_periods',
            field=models.PositiveIntegerField(default=0, help_text="An alternative to the shilling threshold above, expressed in PERIODS: how many periods a member may be behind and still claim (e.g. 'up to 2 months in arrears is fine'). Easier to reason about than an amount when the dues rate changes over time. 0 = use the shilling threshold instead."),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='min_paid_months',
            field=models.PositiveIntegerField(default=0, help_text="Minimum months of PAID-UP membership before a claim qualifies — the 'you must have been paying in for N months' rule most welfare constitutions use (commonly 3, 6 or 12). Counts periods that were actually settled, unlike the waiting period (which is calendar time regardless of payment) and unlike minimum contributions (a bare count that two payments in one month would satisfy). 0 = no tenure requirement."),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='missed_contributions_allowed',
            field=models.PositiveIntegerField(default=0, help_text="When 'no missed contributions' is on, how many missed periods to tolerate before disqualifying (a little slack for the member who genuinely forgot one month). 0 = none allowed."),
        ),
        migrations.AddField(
            model_name='historicalschemepolicy',
            name='no_missed_contributions',
            field=models.BooleanField(default=False, help_text="Require an unbroken payment record — ANY missed period (beyond the grace period and the tolerance below) disqualifies, even if the member later paid it. The strictest standing rule: it is not about how much is owed today, but about never having lapsed. Leave off for the usual 'up to date now' test."),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='catch_up_requalify_days',
            field=models.PositiveIntegerField(default=0, help_text='When catch-up does NOT restore eligibility immediately, how many days a member must remain paid-up after clearing arrears before a claim qualifies again. 0 = no re-qualification period.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='catch_up_restores_eligibility',
            field=models.BooleanField(default=True, help_text='When a member clears their arrears, does eligibility come back immediately? On (the humane default) = yes, paying up restores cover at once. Off = clearing arrears is necessary but the member must then serve the re-qualification period below before claiming again — a guard against someone paying up only once a death has already occurred.'),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='max_arrears_periods',
            field=models.PositiveIntegerField(default=0, help_text="An alternative to the shilling threshold above, expressed in PERIODS: how many periods a member may be behind and still claim (e.g. 'up to 2 months in arrears is fine'). Easier to reason about than an amount when the dues rate changes over time. 0 = use the shilling threshold instead."),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='min_paid_months',
            field=models.PositiveIntegerField(default=0, help_text="Minimum months of PAID-UP membership before a claim qualifies — the 'you must have been paying in for N months' rule most welfare constitutions use (commonly 3, 6 or 12). Counts periods that were actually settled, unlike the waiting period (which is calendar time regardless of payment) and unlike minimum contributions (a bare count that two payments in one month would satisfy). 0 = no tenure requirement."),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='missed_contributions_allowed',
            field=models.PositiveIntegerField(default=0, help_text="When 'no missed contributions' is on, how many missed periods to tolerate before disqualifying (a little slack for the member who genuinely forgot one month). 0 = none allowed."),
        ),
        migrations.AddField(
            model_name='schemepolicy',
            name='no_missed_contributions',
            field=models.BooleanField(default=False, help_text="Require an unbroken payment record — ANY missed period (beyond the grace period and the tolerance below) disqualifies, even if the member later paid it. The strictest standing rule: it is not about how much is owed today, but about never having lapsed. Leave off for the usual 'up to date now' test."),
        ),
    ]
