# Generated by Django 5.2.15 on 2026-07-17 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0028_historicalschemepolicy_catch_up_requalify_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentcontribution',
            name='payer_name',
            field=models.CharField(blank=True, help_text='The name of the third party who paid, where it is not the member (e.g. the employer or sponsor). Left blank for SELF and, by choice, for a genuinely ANONYMOUS gift.', max_length=120),
        ),
        migrations.AddField(
            model_name='benevolentcontribution',
            name='payer_type',
            field=models.CharField(choices=[('SELF', 'The member themselves'), ('ANONYMOUS', 'Anonymous donor'), ('EMPLOYER', "The member's employer"), ('SPONSOR', 'A sponsor'), ('THIRD_PARTY', "Someone else on the member's behalf")], db_index=True, default='SELF', help_text="Who actually paid. SELF for the ordinary case; the others record money paid on a member's behalf (employer, sponsor, third party) or an anonymous gift, so the member's statement stays truthful about it.", max_length=12),
        ),
        migrations.AddField(
            model_name='benevolentcontribution',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='benevolentcontribution',
            name='reversed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='benevolentcontribution',
            name='reverses',
            field=models.ForeignKey(blank=True, help_text='If this row is a reversal, the original contribution it reverses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by_entry', to='benevolent.benevolentcontribution'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcontribution',
            name='payer_name',
            field=models.CharField(blank=True, help_text='The name of the third party who paid, where it is not the member (e.g. the employer or sponsor). Left blank for SELF and, by choice, for a genuinely ANONYMOUS gift.', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcontribution',
            name='payer_type',
            field=models.CharField(choices=[('SELF', 'The member themselves'), ('ANONYMOUS', 'Anonymous donor'), ('EMPLOYER', "The member's employer"), ('SPONSOR', 'A sponsor'), ('THIRD_PARTY', "Someone else on the member's behalf")], db_index=True, default='SELF', help_text="Who actually paid. SELF for the ordinary case; the others record money paid on a member's behalf (employer, sponsor, third party) or an anonymous gift, so the member's statement stays truthful about it.", max_length=12),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcontribution',
            name='reversal_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcontribution',
            name='reversed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbenevolentcontribution',
            name='reverses',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If this row is a reversal, the original contribution it reverses.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.benevolentcontribution'),
        ),
    ]
