# Generated by Django 5.2.15 on 2026-07-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0029_benevolentcontribution_payer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentsettings',
            name='block_overdrawn_payouts',
            field=models.BooleanField(default=False, help_text="Refuse a benefit payout that would push a scheme's fund past the cash available after existing approvals. Off (the default) warns but still allows it — a church may legitimately approve against a levy still being collected. Switch on for a fund that must never go negative."),
        ),
        migrations.AddField(
            model_name='benevolentsettings',
            name='reserve_open_cases',
            field=models.BooleanField(default=True, help_text="In the fund-position view, hold back a prudent reserve for open cases still working through the pipeline (draft/submitted/assessed), so 'available to commit to a new case' does not count money already spoken for. Off shows only firm approvals as claims on the balance."),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='block_overdrawn_payouts',
            field=models.BooleanField(default=False, help_text="Refuse a benefit payout that would push a scheme's fund past the cash available after existing approvals. Off (the default) warns but still allows it — a church may legitimately approve against a levy still being collected. Switch on for a fund that must never go negative."),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='reserve_open_cases',
            field=models.BooleanField(default=True, help_text="In the fund-position view, hold back a prudent reserve for open cases still working through the pipeline (draft/submitted/assessed), so 'available to commit to a new case' does not count money already spoken for. Off shows only firm approvals as claims on the balance."),
        ),
    ]
