# Generated by Django 5.2.15 on 2026-07-17 08:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0030_benevolentsettings_block_overdrawn_payouts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='benevolentsettings',
            name='auto_archive_cases',
            field=models.BooleanField(default=True, help_text='Automatically archive cases that have been settled (paid, closed, rejected or cancelled) for more than six months, so the working case list shows what is live. Archiving is a display flag only — it moves nothing and a person can unarchive at any time.'),
        ),
        migrations.AddField(
            model_name='historicalbenevolentsettings',
            name='auto_archive_cases',
            field=models.BooleanField(default=True, help_text='Automatically archive cases that have been settled (paid, closed, rejected or cancelled) for more than six months, so the working case list shows what is live. Archiving is a display flag only — it moves nothing and a person can unarchive at any time.'),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='kind',
            field=models.CharField(choices=[('RAISED', 'Case raised'), ('SUBMITTED', 'Submitted for assessment'), ('ASSESSED', 'Assessed'), ('COMM_VOTE', 'Committee decision recorded'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PAY_RAISED', 'Payment voucher raised'), ('PAY_PAID', 'Payment voucher paid'), ('PAY_REV', 'Payment voucher reversed or rejected'), ('CLOSED', 'Closed'), ('DOC_ADD', 'Document attached'), ('FUND_TGT', 'Funding target set'), ('FUND_MET', 'Funding target reached'), ('BER_DEC', "Bereaved member's contribution decided"), ('EXEMPTED', 'Bereavement exemption granted'), ('FUNDED_BAL', 'Funded from the fund balance, not a levy'), ('IMPORTED', 'Imported from historical records'), ('ARCHIVED', 'Archived (long settled)'), ('NOTE', 'Note')], db_index=True, max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalBenevolentTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUSPEND_OVERDUE', 'Consider suspending an overdue member'), ('CLOSE_INACTIVE', 'Consider closing an inactive membership'), ('DEPENDANT_AGED_OUT', 'Dependant has passed the age limit'), ('POSSIBLE_DUPLICATE', 'Possible duplicate membership'), ('WAITING_PERIOD_SERVED', 'Member has become eligible'), ('RENEWAL_DUE', 'Membership renewal is due'), ('OTHER', 'Other')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=6)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Actioned'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=40)),
                ('dedup_key', models.CharField(db_index=True, max_length=120)),
                ('created_by_automation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.benevolentcase')),
                ('dependant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.schemedependant')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.schememembership')),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='benevolent.benevolentscheme')),
            ],
            options={
                'verbose_name': 'historical benevolent task',
                'verbose_name_plural': 'historical benevolent tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BenevolentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUSPEND_OVERDUE', 'Consider suspending an overdue member'), ('CLOSE_INACTIVE', 'Consider closing an inactive membership'), ('DEPENDANT_AGED_OUT', 'Dependant has passed the age limit'), ('POSSIBLE_DUPLICATE', 'Possible duplicate membership'), ('WAITING_PERIOD_SERVED', 'Member has become eligible'), ('RENEWAL_DUE', 'Membership renewal is due'), ('OTHER', 'Other')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=6)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Actioned'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('recommended_action', models.CharField(blank=True, max_length=40)),
                ('dedup_key', models.CharField(db_index=True, max_length=120)),
                ('created_by_automation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=200)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='benevolent.benevolentcase')),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='benevolent.schemedependant')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='benevolent.schememembership')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='benevolent.benevolentscheme')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'kind'], name='benevolent__status_03b3ea_idx'), models.Index(fields=['scheme', 'status'], name='benevolent__scheme__ff5d03_idx')],
            },
        ),
    ]
