# Generated by Django 5.2.15 on 2026-07-28 04:50

from django.db import migrations, models



def backfill_household_mode(apps, schema_editor):
    """Set schemes that demonstrably cover households to say so.

    `household_mode` was stored and never enforced, so no existing value
    represents a decision anybody made — the field simply carried whatever the
    default was on the day the policy was written. Enforcing it now, unchanged,
    would refuse dependants on schemes that have been registering them happily
    for as long as they have existed: the rule would contradict the register.

    So the register is treated as the evidence. A scheme with active dependants
    or a household enrolment on its books is, whatever the field says, a scheme
    that covers households — and every one of its policies is corrected to say
    so, including superseded ones, because a backdated registration is checked
    against the policy in force on its own date.

    Schemes with no such evidence are left alone. Individual-only is a real way
    to run a scheme, and inventing household cover for a scheme that has never
    used it would be the same mistake in the other direction. Those schemes will
    refuse a dependant with a message saying exactly which setting to change.
    """
    SchemePolicy = apps.get_model("benevolent", "SchemePolicy")
    SchemeDependant = apps.get_model("benevolent", "SchemeDependant")
    SchemeMembership = apps.get_model("benevolent", "SchemeMembership")

    covering = set(SchemeDependant.objects.filter(active=True)
                   .values_list("membership__scheme_id", flat=True))
    covering |= set(SchemeMembership.objects.filter(registration_type="HOUSEHOLD")
                    .values_list("scheme_id", flat=True))
    covering.discard(None)
    if covering:
        SchemePolicy.objects.filter(
            scheme_id__in=covering, household_mode="INDIVIDUAL"
        ).update(household_mode="HOUSEHOLD")


def unbackfill(apps, schema_editor):
    """Deliberately does nothing.

    There is no record of which values were defaults and which were choices, so
    putting INDIVIDUAL back would guess — and would re-break the schemes this
    corrected. Reversing the migration leaves the corrected values in place.
    """
    return


class Migration(migrations.Migration):

    dependencies = [
        ('benevolent', '0032_portalrequestsequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschemepolicy',
            name='household_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Each member enrols individually'), ('HOUSEHOLD', 'One enrolment covers the whole household')], default='HOUSEHOLD', help_text='Whether one enrolment covers a whole household or only the member. Individual-only schemes refuse household enrolments and dependants; set this before registering anyone under a scheme that is meant to cover families.', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalschemepolicy',
            name='joining_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deprecated duplicate of the registration fee. The setup wizard asks for a joining fee and writes the answer to `registration_fee`, which is the field everything charges against; this one was left holding a number nothing read. Kept so existing policies are not silently altered, and now used as the fee where `registration_fee` is unset — see `SchemePolicy.fee_to_join`. Set the registration fee instead.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='schemepolicy',
            name='household_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Each member enrols individually'), ('HOUSEHOLD', 'One enrolment covers the whole household')], default='HOUSEHOLD', help_text='Whether one enrolment covers a whole household or only the member. Individual-only schemes refuse household enrolments and dependants; set this before registering anyone under a scheme that is meant to cover families.', max_length=10),
        ),
        migrations.AlterField(
            model_name='schemepolicy',
            name='joining_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deprecated duplicate of the registration fee. The setup wizard asks for a joining fee and writes the answer to `registration_fee`, which is the field everything charges against; this one was left holding a number nothing read. Kept so existing policies are not silently altered, and now used as the fee where `registration_fee` is unset — see `SchemePolicy.fee_to_join`. Set the registration fee instead.', max_digits=12),
        ),
        migrations.RunPython(backfill_household_mode, unbackfill),
    ]
