# Generated by Django 5.2.15 on 2026-06-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(db_index=True)),
                ('bank_balance', models.DecimalField(decimal_places=2, help_text='Closing balance as per the bank statement.', max_digits=14)),
                ('book_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Cash-book / ledger balance to reconcile against (optional).', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('UNPRESENTED', 'Unpresented cheque / payment'), ('IN_TRANSIT', 'Deposit in transit'), ('CASH_AT_HAND', 'Cash at hand (not yet banked)'), ('BANK_CHARGE', 'Bank charge not in books'), ('INTEREST', 'Bank interest not in books'), ('ERROR', 'Error / correction'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effect', models.CharField(choices=[('ADD', 'Add to bank balance'), ('SUBTRACT', 'Subtract from bank balance')], default='SUBTRACT', max_length=8)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='statements.bankreconciliation')),
            ],
        ),
    ]
