# Generated by Django 5.2.15 on 2026-06-06 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0004_historicalremittancebatch_remittancebatch_and_more'),
        ('giving', '0006_historicaltransaction_is_reversal_and_more'),
        ('statements', '0002_bankreconciliation_reconciliationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('AUTO', 'Auto-matched'), ('REVIEW', 'Review required'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='REVIEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_matches', to='cashbook.expense')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_matches', to='giving.transaction')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
    ]
