# Generated by Django 5.2.15 on 2026-06-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_reconciliationmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bank_name', models.CharField(blank=True, max_length=80)),
                ('account_number', models.CharField(blank=True, max_length=40)),
                ('kind', models.CharField(choices=[('CURRENT', 'Current / operating'), ('DEVELOPMENT', 'Development fund'), ('SAVINGS', 'Savings'), ('OTHER', 'Other')], default='CURRENT', max_length=12)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='statementimport',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='statements.bankaccount'),
        ),
    ]
