# Generated by Django 5.2.15 on 2026-06-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0012_historicaltransaction_excluded_from_income_and_more'),
        ('statements', '0004_bankaccount_statementimport_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cbs_transaction_id', models.CharField(help_text="The bank's unique TransactionId.", max_length=80, unique=True)),
                ('acct_no', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('event_type', models.CharField(blank=True, max_length=10)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('payment_ref', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('DUPLICATE', 'Duplicate (ignored)'), ('REJECTED', 'Rejected (bad/auth)'), ('FAILED', 'Failed to process')], db_index=True, default='RECEIVED', max_length=10)),
                ('payload', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_event', to='giving.transaction')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
