# Generated by Django 5.2.15 on 2026-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0006_alter_statementimport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementimport',
            name='balance_check',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='balance_detail',
            field=models.TextField(blank=True),
        ),
    ]
