# Generated by Django 5.2.15 on 2026-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0007_statementimport_balance_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementimport',
            name='stmt_closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='stmt_first_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='stmt_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statementimport',
            name='stmt_opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
