# Generated by Django 5.2 on 2026-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0008_statementimport_stmt_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationitem',
            name='auto',
            field=models.BooleanField(default=False, help_text='Auto-managed item (petty cash float / staff advances), kept in step with its computed value.'),
        ),
    ]
