# Generated by Django 5.2.15 on 2026-07-13 15:17

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0024_backfill_split_of'),
        ('statements', '0009_reconciliationitem_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bank_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('core_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mpesa_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('receipt', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('payer_name', models.CharField(blank=True, max_length=160)),
                ('payer_phone', models.CharField(blank=True, max_length=32)),
                ('raw_narration', models.TextField(blank=True)),
                ('dedup_key', models.CharField(db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_lines', to='statements.bankaccount')),
            ],
            options={
                'ordering': ['date', 'occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegisterException',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MISSING_IN_LEDGER', 'On the statement, not in our books'), ('MISSING_IN_BANK', 'In our books, not on the statement')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Accepted — no action needed')], db_index=True, default='OPEN', max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ref', models.CharField(blank=True, max_length=80)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(blank=True, editable=False)),
                ('last_seen', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statements.bankaccount')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction')),
                ('line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statements.statementline')),
            ],
            options={
                'verbose_name': 'historical register exception',
                'verbose_name_plural': 'historical register exceptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StatementRegisterImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('rows_read', models.IntegerField(default=0)),
                ('lines_added', models.IntegerField(default=0)),
                ('duplicates_skipped', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_imports', to='statements.bankaccount')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='statementline',
            name='imported_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='statements.statementregisterimport'),
        ),
        migrations.CreateModel(
            name='RegisterException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MISSING_IN_LEDGER', 'On the statement, not in our books'), ('MISSING_IN_BANK', 'In our books, not on the statement')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Accepted — no action needed')], db_index=True, default='OPEN', max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ref', models.CharField(blank=True, max_length=80)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_exceptions', to='statements.bankaccount')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_exceptions', to='giving.transaction')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='statements.statementline')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('line__isnull', False)), fields=('account', 'kind', 'line'), name='uniq_exception_per_line'), models.UniqueConstraint(condition=models.Q(('transaction__isnull', False)), fields=('account', 'kind', 'transaction'), name='uniq_exception_per_txn')],
            },
        ),
        migrations.AddIndex(
            model_name='statementline',
            index=models.Index(fields=['account', 'date'], name='statements__account_d6ab2b_idx'),
        ),
        migrations.AddIndex(
            model_name='statementline',
            index=models.Index(fields=['account', 'dedup_key'], name='statements__account_a923de_idx'),
        ),
        migrations.AddConstraint(
            model_name='statementline',
            constraint=models.UniqueConstraint(fields=('account', 'dedup_key'), name='uniq_register_line_per_account'),
        ),
    ]
