# Generated by Django 5.2.15 on 2026-07-13 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0024_backfill_split_of'),
        ('statements', '0010_bank_statement_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registerexception',
            name='uniq_exception_per_line',
        ),
        migrations.RemoveConstraint(
            model_name='registerexception',
            name='uniq_exception_per_txn',
        ),
        migrations.AddConstraint(
            model_name='registerexception',
            constraint=models.UniqueConstraint(fields=('account', 'kind', 'line'), name='uniq_exception_per_line'),
        ),
        migrations.AddConstraint(
            model_name='registerexception',
            constraint=models.UniqueConstraint(fields=('account', 'kind', 'transaction'), name='uniq_exception_per_txn'),
        ),
    ]
