# Generated by Django 5.2.15 on 2026-07-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0011_register_constraints_mariadb_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='register_opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="What this account held immediately BEFORE the register's first statement line — e.g. the closing balance on 31 December, if you start the register in January. Leave blank when your statements carry a running-balance column: the opening is then read from the bank's own figure, which is better than anything typed here.", max_digits=14, null=True, verbose_name='Register opening balance'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='register_opening_date',
            field=models.DateField(blank=True, help_text='The date that opening balance applies to. Lines on or after it accumulate on top of it.', null=True, verbose_name='…as at'),
        ),
    ]
