# Generated by Django 5.2.15 on 2026-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0012_register_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementimport',
            name='reversals_skipped',
            field=models.IntegerField(default=0, help_text='Rows the bank posted in error and then reversed. Not imported: a reversed pair is a non-event, and posting either half would put income in the books that was never received. They remain on the bank statement register, which records what the bank said.'),
        ),
    ]
