# Generated by Django 5.2.15 on 2026-07-15 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0014_normalize_register_dedup_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statementregisterimport',
            name='purged_at',
            field=models.DateTimeField(blank=True, help_text='When this upload was undone. A register import may be purged on the DAY it was uploaded — a wrong file, the wrong account — removing the lines it added. After that day it stays: the register is additive and other work may rely on its lines.', null=True),
        ),
        migrations.AddField(
            model_name='statementregisterimport',
            name='purged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
