# Generated by Django 5.2.15 on 2026-07-30 14:05

from django.db import migrations, models



def backfill_balances(apps, schema_editor):
    """Recover the balances from events already received.

    Every event the bank has ever pushed carried its balance, and the whole
    payload was kept as JSON even though nothing read the balance out of it. So
    the history is not lost — it just has to be lifted into columns that can be
    queried. A church that has been running the webhook for months gets its past
    balances back rather than starting the record from today.
    """
    import json
    import datetime as dt
    from decimal import Decimal, InvalidOperation

    BankEvent = apps.get_model("statements", "BankEvent")

    def money(raw):
        try:
            return Decimal(str(raw))
        except (InvalidOperation, TypeError, ValueError):
            return None

    def when(payload):
        for key in ("PostingDate", "ValueDate", "TransactionDate"):
            raw = (payload.get(key) or "").strip()
            if not raw:
                continue
            try:
                return dt.date.fromisoformat(raw[:10])
            except ValueError:
                continue
        return None

    batch = []
    for evt in BankEvent.objects.exclude(payload="").iterator():
        try:
            payload = json.loads(evt.payload)
        except (ValueError, TypeError):
            continue
        if not isinstance(payload, dict):
            continue
        evt.booked_balance = money(payload.get("BookedBalance"))
        evt.cleared_balance = money(payload.get("ClearedBalance"))
        evt.balance_at = when(payload)
        if evt.booked_balance is not None or evt.cleared_balance is not None:
            batch.append(evt)
        if len(batch) >= 500:
            BankEvent.objects.bulk_update(
                batch, ["booked_balance", "cleared_balance", "balance_at"])
            batch = []
    if batch:
        BankEvent.objects.bulk_update(
            batch, ["booked_balance", "cleared_balance", "balance_at"])


def unbackfill(apps, schema_editor):
    """Nothing to undo — the payload each figure came from is still there."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0015_statementregisterimport_purged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankevent',
            name='balance_at',
            field=models.DateField(blank=True, db_index=True, help_text='The date those balances applied to.', null=True),
        ),
        migrations.AddField(
            model_name='bankevent',
            name='booked_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The bank's BookedBalance at this event.", max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='bankevent',
            name='cleared_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The bank's ClearedBalance at this event.", max_digits=16, null=True),
        ),
        migrations.RunPython(backfill_balances, unbackfill),
    ]
