# Generated by Django 5.2 on 2026-06-18 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_twofactor_delivery_email_twofactor_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('rights', models.JSONField(blank=True, default=list, help_text='List of right keys from core.rights.RIGHT_KEYS.')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded default profile mirroring a role group.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
