# Generated by Django 5.2 on 2026-07-06 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_elder_default_profile'),
        ('departments', '0021_alter_departmentstatuslog_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Account created'), ('PROFILE_UPDATED', 'Profile updated'), ('ROLE_CHANGED', 'Role changed'), ('ACTIVATED', 'Account activated'), ('DEACTIVATED', 'Account deactivated'), ('LOCKED', 'Account locked (suspended)'), ('UNLOCKED', 'Account unlocked (reinstated)'), ('PASSWORD_RESET', 'Password reset by administrator'), ('PASSWORD_CHANGED', 'Password changed'), ('FORCE_PASSWORD_CHANGE_SET', 'Forced password change on next login'), ('TWO_FA_DISABLED', 'Two-factor authentication disabled by administrator'), ('LOGIN_LOCKOUT_CLEARED', 'Failed-login lockout cleared'), ('SESSIONS_TERMINATED', 'All sessions terminated'), ('PROFILE_ASSIGNED', 'Rights profile assigned'), ('PROFILE_REMOVED', 'Rights profile removed'), ('CLONED', 'Account cloned from another user')], max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('before', models.CharField(blank=True, default='', max_length=200)),
                ('after', models.CharField(blank=True, default='', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user admin log entry',
                'verbose_name_plural': 'user admin log entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('position', models.CharField(blank=True, default='', help_text='e.g. Head Deacon, Elder, Youth Leader — free text, for reference only.', max_length=80)),
                ('church_assignment', models.CharField(blank=True, default='', help_text='For a multi-church or conference deployment; leave blank for a single church.', max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal admin notes about this account — never shown to the user.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False, help_text='Force a password change the next time this user logs in.')),
                ('locked', models.BooleanField(default=False)),
                ('locked_reason', models.CharField(blank=True, default='', max_length=200)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who created this account. Blank for accounts that predate this field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text="The department/ministry this person is primarily associated with — informational only; a Leader's actual access is governed by DepartmentLeadership, set on the Edit role tab.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='departments.department')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
            },
        ),
    ]
