# Generated by Django 5.2.15 on 2026-08-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_benevolent_role_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
