from django.urls import path
from . import views

urlpatterns = [
    path("expenses/", views.ExpenseListView.as_view(), name="expense_list"),
    path("expenses/recategorize/", views.ExpenseRecategorizeView.as_view(), name="expense_recategorize"),
    path("expenses/new/", views.ExpenseCreate.as_view(), name="expense_create"),
    path("expenses/<int:pk>/edit/", views.ExpenseUpdate.as_view(), name="expense_edit"),
    path("expenses/<int:pk>/approve/", views.ExpenseApprove.as_view(), name="expense_approve"),
    path("expenses/<int:pk>/delete/", views.ExpenseDeleteView.as_view(), name="expense_delete"),
    path("transfers/", views.TransferListView.as_view(), name="transfer_list"),
    path("transfers/new/", views.TransferCreate.as_view(), name="transfer_create"),
    path("transfers/<int:pk>/reverse/", views.TransferReverseView.as_view(), name="transfer_reverse"),
    path("expenses/recurring/", views.RecurringListView.as_view(), name="recurring_list"),
    path("expenses/recurring/new/", views.RecurringCreate.as_view(), name="recurring_create"),
    path("expenses/recurring/<int:pk>/edit/", views.RecurringUpdate.as_view(), name="recurring_edit"),
    path("expenses/recurring/<int:pk>/toggle/", views.RecurringToggle.as_view(), name="recurring_toggle"),
    path("expenses/recurring/generate/", views.RecurringGenerate.as_view(), name="recurring_generate"),
    path("petty-cash/", views.PettyCashView.as_view(), name="petty_cash"),
    path("petty-cash/top-up/", views.PettyCashTopUp.as_view(), name="petty_cash_topup"),
    path("petty-cash/disburse/", views.PettyCashDisburse.as_view(), name="petty_cash_disburse"),
    path("expenses/<int:pk>/", views.ExpenseDetailView.as_view(), name="expense_detail"),
    path("expenses/<int:pk>/attach/", views.ExpenseAttachmentUpload.as_view(), name="expense_attachment_upload"),
    path("expenses/<int:pk>/attach/<int:att>/delete/", views.ExpenseAttachmentDelete.as_view(), name="expense_attachment_delete"),
    path("payables/", views.AccrualsView.as_view(), name="accruals"),
    path("payables/payable/add/", views.PayableCreate.as_view(), name="payable_create"),
    path("payables/payable/<int:pk>/settle/", views.PayableSettle.as_view(), name="payable_settle"),
    path("payables/accrual/add/", views.AccrualCreate.as_view(), name="accrual_create"),
    path("payables/accrual/<int:pk>/settle/", views.AccrualSettle.as_view(), name="accrual_settle"),
    path("payables/prepayment/add/", views.PrepaymentCreate.as_view(), name="prepayment_create"),
    path("categories/", views.ExpenseCategoryList.as_view(), name="expense_categories"),
    path("advances/", views.AdvanceListView.as_view(), name="advance_list"),
    path("advances/new/", views.AdvanceCreate.as_view(), name="advance_new"),
    path("advances/<int:pk>/", views.AdvanceDetail.as_view(), name="advance_detail"),
    path("advances/<int:pk>/expense/", views.AdvanceAddExpense.as_view(), name="advance_add_expense"),
    path("advances/<int:pk>/close/", views.AdvanceClose.as_view(), name="advance_close"),
]
