from django.urls import path
from django.views.generic import RedirectView
from . import views
from . import liabilities

urlpatterns = [
    path("reports/fund/<int:pk>/budget/", views.FundBudgetView.as_view(), name="fund_budget"),
    path("reports/fund/<int:pk>/budget/group-goals.jpg", views.GroupGoalsJpegView.as_view(), name="group_goals_jpeg"),
    path("reports/fund/<int:pk>/budget/items.jpg", views.BudgetItemsJpegView.as_view(), name="budget_items_jpeg"),
    path("expenses/budget-items/", views.BudgetItemsJSONView.as_view(), name="budget_items_json"),
    path("expenses/", views.ExpenseListView.as_view(), name="expense_list"),
    path("expenses/receipts/", views.ReceiptArchiveView.as_view(), name="receipt_archive"),
    path("expenses/missing-receipts/", views.MissingReceiptsView.as_view(), name="missing_receipts"),
    path("expenses/import/", views.ExpenseImportView.as_view(), name="expense_import"),
    path("expenses/recategorize/", views.ExpenseRecategorizeView.as_view(), name="expense_recategorize"),
    path("expenses/new/", views.ExpenseCreate.as_view(), name="expense_create"),
    path("expenses/<int:pk>/edit/", views.ExpenseUpdate.as_view(), name="expense_edit"),
    path("expenses/<int:pk>/approve/", views.ExpenseApprove.as_view(), name="expense_approve"),
    path("expenses/bulk/", views.ExpenseBulkActionView.as_view(), name="expense_bulk"),
    path("expenses/<int:pk>/delete/", views.ExpenseDeleteView.as_view(), name="expense_delete"),
    path("transfers/", views.TransferListView.as_view(), name="transfer_list"),
    path("transfers/new/", views.TransferCreate.as_view(), name="transfer_create"),
    path("transfers/<int:pk>/edit/", views.TransferEdit.as_view(), name="transfer_edit"),
    path("transfers/<int:pk>/reverse/", views.TransferReverseView.as_view(), name="transfer_reverse"),
    path("expenses/recurring/", views.RecurringListView.as_view(), name="recurring_list"),
    path("expenses/recurring/new/", views.RecurringCreate.as_view(), name="recurring_create"),
    path("expenses/recurring/<int:pk>/edit/", views.RecurringUpdate.as_view(), name="recurring_edit"),
    path("expenses/recurring/<int:pk>/toggle/", views.RecurringToggle.as_view(), name="recurring_toggle"),
    path("expenses/recurring/<int:pk>/delete/", views.RecurringDelete.as_view(), name="recurring_delete"),
    path("expenses/recurring/generate/", views.RecurringGenerate.as_view(), name="recurring_generate"),
    path("petty-cash/", views.PettyCashView.as_view(), name="petty_cash"),
    path("petty-cash/top-up/", views.PettyCashTopUp.as_view(), name="petty_cash_topup"),
    path("petty-cash/disburse/", views.PettyCashDisburse.as_view(), name="petty_cash_disburse"),
    path("expenses/<int:pk>/", views.ExpenseDetailView.as_view(), name="expense_detail"),
    path("expenses/<int:pk>/refund/", views.ExpenseRefundCreate.as_view(), name="expense_refund"),
    path("expenses/<int:pk>/refund/<int:ref>/delete/", views.ExpenseRefundDelete.as_view(), name="expense_refund_delete"),
    path("expenses/<int:pk>/attach/", views.ExpenseAttachmentUpload.as_view(), name="expense_attachment_upload"),
    path("expenses/<int:pk>/attach/<int:att>/delete/", views.ExpenseAttachmentDelete.as_view(), name="expense_attachment_delete"),
    path("payables/", views.AccrualsView.as_view(), name="accruals"),
    # Payment register (cheques, EFT, RTGS, M-Pesa, etc.)
    path("liabilities/", liabilities.LiabilityRegisterView.as_view(), name="liability_register"),
    path("payments/", views.ChequeRegisterView.as_view(), name="payment_register"),
    path("payments/outstanding/", views.ChequeOutstandingView.as_view(), name="payment_outstanding"),
    path("payments/analysis/", views.PaymentAnalysisView.as_view(), name="payment_analysis"),
    path("payments/<int:pk>/print/", views.ChequePrintView.as_view(), name="payment_print"),
    # backward-compatible permanent redirects from the old /cheques/ paths
    path("cheques/", RedirectView.as_view(pattern_name="payment_register", permanent=True), name="cheque_register"),
    path("cheques/outstanding/", RedirectView.as_view(pattern_name="payment_outstanding", permanent=True), name="cheque_outstanding"),
    path("cheques/<int:pk>/print/", RedirectView.as_view(pattern_name="payment_print", permanent=True), name="cheque_print"),
    path("payables/payable/add/", views.PayableCreate.as_view(), name="payable_create"),
    path("payables/payable/<int:pk>/settle/", views.PayableSettle.as_view(), name="payable_settle"),
    path("payables/accrual/add/", views.AccrualCreate.as_view(), name="accrual_create"),
    path("payables/accrual/<int:pk>/settle/", views.AccrualSettle.as_view(), name="accrual_settle"),
    path("payables/prepayment/add/", views.PrepaymentCreate.as_view(), name="prepayment_create"),
    path("payables/payable/<int:pk>/edit/", views.PayableEdit.as_view(), name="payable_edit"),
    path("payables/payable/<int:pk>/delete/", views.PayableDelete.as_view(), name="payable_delete"),
    path("payables/accrual/<int:pk>/edit/", views.AccrualEdit.as_view(), name="accrual_edit"),
    path("payables/accrual/<int:pk>/delete/", views.AccrualDelete.as_view(), name="accrual_delete"),
    path("payables/prepayment/<int:pk>/edit/", views.PrepaymentEdit.as_view(), name="prepayment_edit"),
    path("payables/prepayment/<int:pk>/delete/", views.PrepaymentDelete.as_view(), name="prepayment_delete"),
    path("payables/<str:kind>/<int:pk>/settle-existing/", views.SettleAgainstExpenseView.as_view(), name="settle_existing"),
    path("categories/", views.ExpenseCategoryList.as_view(), name="expense_categories"),
    path("advances/", views.AdvanceListView.as_view(), name="advance_list"),
    path("advances/new/", views.AdvanceCreate.as_view(), name="advance_new"),
    path("advances/<int:pk>/", views.AdvanceDetail.as_view(), name="advance_detail"),
    path("advances/<int:pk>/expense/", views.AdvanceAddExpense.as_view(), name="advance_add_expense"),
    path("advances/<int:pk>/close/", views.AdvanceClose.as_view(), name="advance_close"),
    path("advances/<int:pk>/topup/", views.AdvanceTopUpView.as_view(), name="advance_topup"),
    path("advances/<int:pk>/import/", views.AdvanceExpenseImportView.as_view(), name="advance_import"),
    path("advances/<int:pk>/topup/<int:topup_id>/reverse/",
         views.AdvanceTopUpReverseView.as_view(), name="advance_topup_reverse"),
    path("advances/<int:pk>/edit/", views.AdvanceEdit.as_view(), name="advance_edit"),
    path("advances/<int:pk>/delete/", views.AdvanceDelete.as_view(), name="advance_delete"),

]
