# Generated by Django 5.2.15 on 2026-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
    ]
