# Generated by Django 5.2.15 on 2026-06-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_alter_expense_category_and_more'),
        ('giving', '0003_splitfund_alter_allocationrule_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_expenses', to='giving.transaction'),
        ),
    ]
