# Generated by Django 5.2.15 on 2026-06-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('cashbook', '0004_historicalremittancebatch_remittancebatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='capitalized_asset',
            field=models.ForeignKey(blank=True, help_text='If capital: the fixed asset this expenditure created or improved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_expenses', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expenditure_type',
            field=models.CharField(choices=[('RECURRENT', 'Recurrent (running cost)'), ('CAPITAL', 'Capital (asset / development)')], db_index=True, default='RECURRENT', help_text='Recurrent = day-to-day running cost; Capital = creates or improves a fixed asset (construction, equipment, vehicles).', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='capitalized_asset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If capital: the fixed asset this expenditure created or improved.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='expenditure_type',
            field=models.CharField(choices=[('RECURRENT', 'Recurrent (running cost)'), ('CAPITAL', 'Capital (asset / development)')], db_index=True, default='RECURRENT', help_text='Recurrent = day-to-day running cost; Capital = creates or improves a fixed asset (construction, equipment, vehicles).', max_length=10),
        ),
    ]
