# Generated by Django 5.2.15 on 2026-06-07 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0008_expense_paid_from_petty_cash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='second_approved_by',
            field=models.ForeignKey(blank=True, help_text='Second treasurer who co-approved a high-value expense.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_second_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='second_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Second treasurer who co-approved a high-value expense.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
