# Generated by Django 5.2.15 on 2026-06-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0009_expense_second_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseattachment',
            name='link',
            field=models.URLField(blank=True, help_text='A link to an online/e-receipt.'),
        ),
        migrations.AddField(
            model_name='expenseattachment',
            name='text',
            field=models.TextField(blank=True, help_text='A text receipt, e.g. a pasted M-Pesa confirmation message.'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/expenses/%Y/%m/'),
        ),
    ]
