# Generated by Django 5.2.15 on 2026-06-12 10:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0012_expensecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRemittanceDeadline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(help_text='Calendar month this deadline closes (1–12).')),
                ('label', models.CharField(blank=True, help_text="e.g. 'January remittance'.", max_length=60)),
                ('deadline', models.DateField(help_text='The date the remittance is due to the field/conference.')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('remitted', models.BooleanField(default=False, help_text="Tick once this period's remittance has been sent.")),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.remittancebatch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical remittance deadline',
                'verbose_name_plural': 'historical remittance deadlines',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RemittanceDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('period_month', models.PositiveSmallIntegerField(help_text='Calendar month this deadline closes (1–12).')),
                ('label', models.CharField(blank=True, help_text="e.g. 'January remittance'.", max_length=60)),
                ('deadline', models.DateField(help_text='The date the remittance is due to the field/conference.')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('remitted', models.BooleanField(default=False, help_text="Tick once this period's remittance has been sent.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to='cashbook.remittancebatch')),
            ],
            options={
                'ordering': ['year', 'period_month', 'deadline'],
                'unique_together': {('year', 'period_month')},
            },
        ),
    ]
