# Generated by Django 5.2 on 2026-06-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0015_historicalbudgetline_budgetline'),
        ('departments', '0016_department_contribution_goal_department_year_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetline',
            options={'ordering': ['department', 'year', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_line',
            field=models.ForeignKey(blank=True, help_text='The specific budget item this expense relates to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='cashbook.budgetline'),
        ),
        migrations.AddField(
            model_name='historicalbudgetline',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='budget_line',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The specific budget item this expense relates to (optional).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.budgetline'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='category',
            field=models.CharField(blank=True, choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalbudgetline',
            name='category',
            field=models.CharField(blank=True, choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('OTHER', 'Other')], default='', max_length=14),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('department', 'year', 'name')},
        ),
    ]
