# Generated by Django 5.2 on 2026-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0016_alter_budgetline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecurringexpense',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='For monthly/quarterly/yearly schedules: day of the month the payment falls due.'),
        ),
        migrations.AlterField(
            model_name='historicalrecurringexpense',
            name='frequency',
            field=models.CharField(choices=[('SABBATH', 'Every Sabbath (weekly)'), ('MONTHLY', 'Every month'), ('QUARTERLY', 'Every quarter'), ('YEARLY', 'Every year')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='For monthly/quarterly/yearly schedules: day of the month the payment falls due.'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='frequency',
            field=models.CharField(choices=[('SABBATH', 'Every Sabbath (weekly)'), ('MONTHLY', 'Every month'), ('QUARTERLY', 'Every quarter'), ('YEARLY', 'Every year')], default='MONTHLY', max_length=10),
        ),
    ]
