# Generated by Django 5.2 on 2026-06-26 22:09

import cashbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0019_expense_rejected_by_historicalexpense_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=cashbook.models.expense_receipt_path),
        ),
    ]
