# Generated by Django 5.2 on 2026-06-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0020_alter_expenseattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstaffadvance',
            name='from_petty_cash',
            field=models.BooleanField(default=False, help_text='Issued out of the petty-cash float (reduces petty cash; the advance is a receivable until accounted for).'),
        ),
        migrations.AddField(
            model_name='historicalstaffadvance',
            name='returned_to_petty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unspent cash the staff member returned to the petty-cash box.', max_digits=12),
        ),
        migrations.AddField(
            model_name='staffadvance',
            name='from_petty_cash',
            field=models.BooleanField(default=False, help_text='Issued out of the petty-cash float (reduces petty cash; the advance is a receivable until accounted for).'),
        ),
        migrations.AddField(
            model_name='staffadvance',
            name='returned_to_petty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unspent cash the staff member returned to the petty-cash box.', max_digits=12),
        ),
    ]
