# Generated by Django 5.2 on 2026-06-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0021_historicalstaffadvance_from_petty_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstaffadvance',
            name='bank_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bank / M-Pesa transaction charge incurred to issue this advance.', max_digits=12),
        ),
        migrations.AddField(
            model_name='historicalstaffadvance',
            name='charge_expense',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The expense that records this advance's bank/M-Pesa charge.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense'),
        ),
        migrations.AddField(
            model_name='staffadvance',
            name='bank_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bank / M-Pesa transaction charge incurred to issue this advance.', max_digits=12),
        ),
        migrations.AddField(
            model_name='staffadvance',
            name='charge_expense',
            field=models.OneToOneField(blank=True, help_text="The expense that records this advance's bank/M-Pesa charge.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_charge', to='cashbook.expense'),
        ),
    ]
