# Generated by Django 5.2 on 2026-06-30 09:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0024_expenserefund_historicalexpenserefund'),
        ('statements', '0009_reconciliationitem_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaymentInstrument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('method', models.CharField(choices=[('CHEQUE', 'Cheque'), ('EFT', 'EFT (bank transfer)'), ('RTGS', 'RTGS'), ('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('OTHER', 'Other')], db_index=True, default='CHEQUE', max_length=8)),
                ('instrument_number', models.CharField(blank=True, db_index=True, help_text='Cheque number, EFT/RTGS reference, or M-Pesa code.', max_length=40)),
                ('payee', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_issued', models.DateField(blank=True, db_index=True, null=True)),
                ('date_cleared', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('OUTSTANDING', 'Outstanding'), ('CLEARED', 'Cleared'), ('VOIDED', 'Voided'), ('STOPPED', 'Stopped')], db_index=True, default='DRAFT', max_length=12)),
                ('source_kind', models.CharField(choices=[('EXPENSE', 'Expense voucher'), ('REMITTANCE', 'Trust fund remittance'), ('REFUND', 'Refund'), ('TRANSFER', 'Fund transfer'), ('SUPPLIER', 'Supplier payment'), ('MANUAL', 'Manual / standalone')], default='EXPENSE', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('signatory_1', models.CharField(blank=True, max_length=120)),
                ('signatory_2', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='statements.bankaccount')),
                ('expense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expenserefund')),
                ('remittance_batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.remittancebatch')),
                ('transfer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.fundtransfer')),
            ],
            options={
                'verbose_name': 'historical payment instrument',
                'verbose_name_plural': 'historical payment instruments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CHEQUE', 'Cheque'), ('EFT', 'EFT (bank transfer)'), ('RTGS', 'RTGS'), ('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('OTHER', 'Other')], db_index=True, default='CHEQUE', max_length=8)),
                ('instrument_number', models.CharField(blank=True, db_index=True, help_text='Cheque number, EFT/RTGS reference, or M-Pesa code.', max_length=40)),
                ('payee', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_issued', models.DateField(blank=True, db_index=True, null=True)),
                ('date_cleared', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ISSUED', 'Issued'), ('OUTSTANDING', 'Outstanding'), ('CLEARED', 'Cleared'), ('VOIDED', 'Voided'), ('STOPPED', 'Stopped')], db_index=True, default='DRAFT', max_length=12)),
                ('source_kind', models.CharField(choices=[('EXPENSE', 'Expense voucher'), ('REMITTANCE', 'Trust fund remittance'), ('REFUND', 'Refund'), ('TRANSFER', 'Fund transfer'), ('SUPPLIER', 'Supplier payment'), ('MANUAL', 'Manual / standalone')], default='EXPENSE', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('signatory_1', models.CharField(blank=True, max_length=120)),
                ('signatory_2', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_approved', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_instruments', to='statements.bankaccount')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cashbook.expense')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cashbook.expenserefund')),
                ('remittance_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cashbook.remittancebatch')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cashbook.fundtransfer')),
            ],
            options={
                'ordering': ['-date_issued', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cashbook.paymentinstrument')),
            ],
        ),
        migrations.AddIndex(
            model_name='paymentinstrument',
            index=models.Index(fields=['status', 'date_issued'], name='cashbook_pa_status_2e79b3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstrument',
            index=models.Index(fields=['method', 'status'], name='cashbook_pa_method_29f400_idx'),
        ),
    ]
