# Generated by Django 5.2 on 2026-06-30 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0026_port_cheques_to_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalremittancebatch',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.paymentinstrument'),
        ),
        migrations.AddField(
            model_name='remittancebatch',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_remittance', to='cashbook.paymentinstrument'),
        ),
    ]
