# Generated by Django 5.2 on 2026-07-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0029_backfill_legacy_remittances'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancetopup',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bank/M-Pesa charge for sending this top-up — the church's own cost, booked as an expense but not added to what the advance holder must account for.", max_digits=12),
        ),
        migrations.AddField(
            model_name='advancetopup',
            name='charge_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_charge_for', to='cashbook.expense'),
        ),
        migrations.AddField(
            model_name='historicaladvancetopup',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Bank/M-Pesa charge for sending this top-up — the church's own cost, booked as an expense but not added to what the advance holder must account for.", max_digits=12),
        ),
        migrations.AddField(
            model_name='historicaladvancetopup',
            name='charge_expense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense'),
        ),
    ]
