# Generated by Django 5.2 on 2026-07-04 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_fixedasset_cost_alter_fixedasset_salvage_value_and_more'),
        ('cashbook', '0032_alter_accrual_amount_alter_advancetopup_amount_and_more'),
        ('departments', '0020_department_income_account'),
        ('giving', '0021_allocationrule_archived_allocationrule_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'date'], name='cashbook_ex_status_48f678_idx'),
        ),
    ]
