# Generated by Django 5.2.15 on 2026-07-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0033_expense_cashbook_ex_status_48f678_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='funding_source',
            field=models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('LOAN', 'Loan'), ('GRANT', 'Grant'), ('ADVANCE', 'Advance'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('OTHER', 'Other')], db_index=True, default='CONTRIBUTION', help_text='What kind of money paid for this — contributions (the default), loan financing, a grant, etc. Informational tagging usable anywhere a payment is recorded.', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='funding_source',
            field=models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('LOAN', 'Loan'), ('GRANT', 'Grant'), ('ADVANCE', 'Advance'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('OTHER', 'Other')], db_index=True, default='CONTRIBUTION', help_text='What kind of money paid for this — contributions (the default), loan financing, a grant, etc. Informational tagging usable anywhere a payment is recorded.', max_length=12),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='category',
            field=models.CharField(blank=True, choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalaccrual',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalbudgetline',
            name='category',
            field=models.CharField(blank=True, choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalpayable',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalprepayment',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='historicalrecurringexpense',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='ALLOWANCE', max_length=14),
        ),
        migrations.AlterField(
            model_name='payable',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='prepayment',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='OTHER', max_length=14),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('ALLOWANCE', 'Allowance / honoraria'), ('TRANSPORT', 'Transport'), ('REFRESHMENTS', 'Refreshments / catering'), ('MATERIALS', 'Materials / supplies'), ('STATIONERY', 'Stationery / printing'), ('SALARIES', 'Salaries / wages'), ('LEASE', 'Lease payment'), ('UTILITIES', 'Utilities (power, water)'), ('MAINTENANCE', 'Maintenance / repairs'), ('CONSTRUCTION', 'Construction / development'), ('EVANGELISM', 'Evangelism / mission'), ('BENEVOLENCE', 'Benevolence / welfare'), ('BANK_CHARGE', 'Bank charges'), ('REMITTANCE', 'Remittance to field'), ('LOAN_REPAYMENT', 'Loan principal repayment'), ('LOAN_INTEREST', 'Loan interest'), ('OTHER', 'Other')], default='ALLOWANCE', max_length=14),
        ),
    ]
