# Generated by Django 5.2.15 on 2026-07-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0034_expense_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='doc_class',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('EXPENSE', 'Expense'), ('LIABILITY', 'Liability'), ('TRANSFER', 'Transfer'), ('JOURNAL', 'Journal'), ('ADJUSTMENT', 'Adjustment')], db_index=True, default='EXPENSE', editable=False, help_text='Derived from the category on save: liability categories (trust remittance, loan repayment, custom categories flagged as liability) file under the Liability Register, everything else under Expenses. Never affects ledger posting.', max_length=10),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_liability',
            field=models.BooleanField(default=False, help_text='Tick for liability-settlement categories (deposit refunds, advance settlements, deferred income, …). Vouchers in this category file under the Liability Register instead of Expenses — no code change needed for new liability types.'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='doc_class',
            field=models.CharField(choices=[('RECEIPT', 'Receipt'), ('EXPENSE', 'Expense'), ('LIABILITY', 'Liability'), ('TRANSFER', 'Transfer'), ('JOURNAL', 'Journal'), ('ADJUSTMENT', 'Adjustment')], db_index=True, default='EXPENSE', editable=False, help_text='Derived from the category on save: liability categories (trust remittance, loan repayment, custom categories flagged as liability) file under the Liability Register, everything else under Expenses. Never affects ledger posting.', max_length=10),
        ),
    ]
