# Generated by Django 5.2.15 on 2026-07-09 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0036_reclassify_liability_vouchers'),
        ('giving', '0022_transaction_giving_txn_dir_conf_date_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentinstrument',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction'),
        ),
        migrations.AddField(
            model_name='historicalpaymentinstrument',
            name='date_cancelled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentinstrument',
            name='date_payment',
            field=models.DateField(blank=True, help_text='Value/payment date if different from the issue date.', null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentinstrument',
            name='date_prepared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentinstrument',
            name='date_presented',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentinstrument',
            name='date_reversed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentinstrument',
            name='date_voided',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_instruments', to='giving.transaction'),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='date_cancelled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='date_payment',
            field=models.DateField(blank=True, help_text='Value/payment date if different from the issue date.', null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='date_prepared',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='date_presented',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='date_reversed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='date_voided',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentinstrument',
            name='extra_expenses',
            field=models.ManyToManyField(blank=True, related_name='covering_payments', to='cashbook.expense'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentinstrument',
            name='date_cleared',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaymentinstrument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PREPARED', 'Prepared'), ('ISSUED', 'Issued'), ('OUTSTANDING', 'Outstanding'), ('PRESENTED', 'Presented'), ('CLEARED', 'Cleared'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('VOIDED', 'Voided'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired'), ('STOPPED', 'Stopped')], db_index=True, default='DRAFT', max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentinstrument',
            name='date_cleared',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstrument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PREPARED', 'Prepared'), ('ISSUED', 'Issued'), ('OUTSTANDING', 'Outstanding'), ('PRESENTED', 'Presented'), ('CLEARED', 'Cleared'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('VOIDED', 'Voided'), ('REVERSED', 'Reversed'), ('EXPIRED', 'Expired'), ('STOPPED', 'Stopped')], db_index=True, default='DRAFT', max_length=12),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CREATE', 'Created'), ('APPROVE', 'Approved'), ('PREPARE', 'Prepared / printed'), ('ISSUE', 'Issued'), ('PRESENT', 'Presented'), ('CLEAR', 'Cleared'), ('CANCEL', 'Cancelled'), ('REJECT', 'Rejected'), ('VOID', 'Voided'), ('REVERSE', 'Reversed'), ('EXPIRE', 'Expired'), ('REISSUE', 'Re-issued')], max_length=8)),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(blank=True, max_length=12)),
                ('on', models.DateField(help_text='The business date of the event.')),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cashbook.paymentinstrument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
