# Generated by Django 5.2.15 on 2026-07-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0037_historicalpaymentinstrument_bank_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payee',
            field=models.CharField(blank=True, help_text="Who the money is actually PAID TO, if that is not the claimant — a supplier's name on a cheque, say, where the claimant is the member who requested the purchase. Left blank, the claimant is the payee.", max_length=160),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='payee',
            field=models.CharField(blank=True, help_text="Who the money is actually PAID TO, if that is not the claimant — a supplier's name on a cheque, say, where the claimant is the member who requested the purchase. Left blank, the claimant is the payee.", max_length=160),
        ),
        migrations.AddField(
            model_name='historicalpettycashtopup',
            name='instrument',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The cheque or transfer that funded this top-up, if any.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.paymentinstrument'),
        ),
        migrations.AddField(
            model_name='pettycashtopup',
            name='instrument',
            field=models.OneToOneField(blank=True, help_text='The cheque or transfer that funded this top-up, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_topup', to='cashbook.paymentinstrument'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='claimant',
            field=models.CharField(blank=True, help_text='Who incurred or requested this — the person the church is answerable to for the claim.', max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='claimant',
            field=models.CharField(blank=True, help_text='Who incurred or requested this — the person the church is answerable to for the claim.', max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalpaymentinstrument',
            name='source_kind',
            field=models.CharField(choices=[('EXPENSE', 'Expense voucher'), ('REMITTANCE', 'Trust fund remittance'), ('REFUND', 'Refund'), ('TRANSFER', 'Fund transfer'), ('SUPPLIER', 'Supplier payment'), ('PETTY_CASH', 'Petty cash replenishment'), ('MANUAL', 'Manual / standalone')], default='EXPENSE', max_length=12),
        ),
        migrations.AlterField(
            model_name='paymentinstrument',
            name='source_kind',
            field=models.CharField(choices=[('EXPENSE', 'Expense voucher'), ('REMITTANCE', 'Trust fund remittance'), ('REFUND', 'Refund'), ('TRANSFER', 'Fund transfer'), ('SUPPLIER', 'Supplier payment'), ('PETTY_CASH', 'Petty cash replenishment'), ('MANUAL', 'Manual / standalone')], default='EXPENSE', max_length=12),
        ),
    ]
