# Generated by Django 5.2.15 on 2026-07-23 16:16

import django.db.models.deletion
from django.db import migrations, models


def carry_existing_settlements_forward(apps, schema_editor):
    """Re-point every payable already settled at its settling expense.

    Without this the migration would silently orphan the link: `settled_expense`
    is dropped and `Expense.payable` starts empty, so every historically settled
    payable would read as fully unpaid and reappear on the balance sheet as a
    liability the church has already discharged. Copied first, removed after.
    """
    Payable = apps.get_model("cashbook", "Payable")
    Expense = apps.get_model("cashbook", "Expense")
    for payable in Payable.objects.exclude(settled_expense__isnull=True).iterator():
        Expense.objects.filter(pk=payable.settled_expense_id).update(payable=payable.pk)


def unpick_settlements(apps, schema_editor):
    """Reverse: put the link back on the payable, keeping the last instalment.

    A payable paid in several instalments cannot round-trip through a field that
    holds one expense, so the reverse keeps the final payment — enough for the
    old code to see the payable as settled, which is the invariant that matters
    going backwards.
    """
    Payable = apps.get_model("cashbook", "Payable")
    Expense = apps.get_model("cashbook", "Expense")
    for payable in Payable.objects.iterator():
        last = (Expense.objects.filter(payable=payable.pk)
                .order_by("date", "id").last())
        if last is not None:
            payable.settled_expense_id = last.pk
            payable.save(update_fields=["settled_expense"])


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0038_payee_and_petty_cash_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payable',
            field=models.ForeignKey(blank=True, help_text='The payable this payment settles, in whole or in part. A payable may be paid over several instalments, so this is a ForeignKey and not a OneToOne — see Payable.paid_total.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cashbook.payable'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='payable',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The payable this payment settles, in whole or in part. A payable may be paid over several instalments, so this is a ForeignKey and not a OneToOne — see Payable.paid_total.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.payable'),
        ),
        migrations.RunPython(carry_existing_settlements_forward,
                             unpick_settlements),
        migrations.RemoveField(
            model_name='historicalpayable',
            name='settled_expense',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='settled_expense',
        ),
        migrations.AlterField(
            model_name='historicalpayable',
            name='settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalpayable',
            name='settled_on',
            field=models.DateField(blank=True, help_text='The date the FINAL instalment cleared the balance.', null=True),
        ),
        migrations.AlterField(
            model_name='payable',
            name='settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='payable',
            name='settled_on',
            field=models.DateField(blank=True, help_text='The date the FINAL instalment cleared the balance.', null=True),
        ),
    ]
