# Generated by Django 5.2.15 on 2026-07-23 17:40

import django.db.models.deletion
from django.db import migrations, models


def carry_existing_settlements_forward(apps, schema_editor):
    """Re-point every accrual already settled at its settling expense.

    Same reasoning as the payable migration before it: `settled_expense` is
    dropped and `Expense.accrual` starts empty, so without this every accrual
    settled to date would read as unpaid and reappear on the balance sheet as a
    liability the church has already discharged.
    """
    Accrual = apps.get_model("cashbook", "Accrual")
    Expense = apps.get_model("cashbook", "Expense")
    for accrual in Accrual.objects.exclude(settled_expense__isnull=True).iterator():
        Expense.objects.filter(pk=accrual.settled_expense_id).update(accrual=accrual.pk)


def unpick_settlements(apps, schema_editor):
    """Reverse: put the link back, keeping the final instalment."""
    Accrual = apps.get_model("cashbook", "Accrual")
    Expense = apps.get_model("cashbook", "Expense")
    for accrual in Accrual.objects.iterator():
        last = (Expense.objects.filter(accrual=accrual.pk)
                .order_by("date", "id").last())
        if last is not None:
            accrual.settled_expense_id = last.pk
            accrual.save(update_fields=["settled_expense"])


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0039_remove_historicalpayable_settled_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accrual',
            field=models.ForeignKey(blank=True, help_text='The accrual this payment settles, in whole or in part.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='cashbook.accrual'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='accrual',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The accrual this payment settles, in whole or in part.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.accrual'),
        ),
        migrations.RunPython(carry_existing_settlements_forward,
                             unpick_settlements),
        migrations.RemoveField(
            model_name='accrual',
            name='settled_expense',
        ),
        migrations.RemoveField(
            model_name='historicalaccrual',
            name='settled_expense',
        ),
        migrations.AlterField(
            model_name='accrual',
            name='settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='settled_on',
            field=models.DateField(blank=True, help_text='The date the FINAL instalment cleared the balance.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccrual',
            name='settled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicalaccrual',
            name='settled_on',
            field=models.DateField(blank=True, help_text='The date the FINAL instalment cleared the balance.', null=True),
        ),
    ]
