# Generated by Django 5.2.15 on 2026-07-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0040_remove_accrual_settled_expense_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='The supplier this was paid to, where they are on the supplier register. Optional: `payee` still records what the voucher said, and a one-off payment needs no register entry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The supplier this was paid to, where they are on the supplier register. Optional: `payee` still records what the voucher said, and a one-off payment needs no register entry.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='historicalpayable',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The supplier register entry, where there is one.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='payable',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The supplier register entry, where there is one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='historicalpayable',
            name='vendor',
            field=models.CharField(help_text="The supplier's name as it appears on the invoice. Kept even when `supplier` is set — it is what the document said.", max_length=120),
        ),
        migrations.AlterField(
            model_name='payable',
            name='vendor',
            field=models.CharField(help_text="The supplier's name as it appears on the invoice. Kept even when `supplier` is set — it is what the document said.", max_length=120),
        ),
    ]
