# Generated by Django 5.2.15 on 2026-07-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0041_expense_vendor_historicalexpense_vendor_and_more'),
        ('vendors', '0002_backfill_from_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecurringexpense',
            name='budget_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.budgetline'),
        ),
        migrations.AddField(
            model_name='historicalrecurringexpense',
            name='expenditure_type',
            field=models.CharField(choices=[('RECURRENT', 'Recurrent (running cost)'), ('CAPITAL', 'Capital (asset / development)')], default='RECURRENT', help_text='A scheduled cost is recurrent by nature, but a monthly instalment on a capital purchase is not.', max_length=12),
        ),
        migrations.AddField(
            model_name='historicalrecurringexpense',
            name='paid_from_petty_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalrecurringexpense',
            name='payee',
            field=models.CharField(blank=True, default='', help_text='Filled from the supplier if left blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='historicalrecurringexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The supplier, where they are on the register. Every payment this schedule generates lands on their account.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='historicalrecurringexpense',
            name='voucher_no',
            field=models.CharField(blank=True, default='', help_text='A fixed reference, e.g. a standing order number. Left blank for most schedules, since each payment gets its own.', max_length=30),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='cashbook.budgetline'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='expenditure_type',
            field=models.CharField(choices=[('RECURRENT', 'Recurrent (running cost)'), ('CAPITAL', 'Capital (asset / development)')], default='RECURRENT', help_text='A scheduled cost is recurrent by nature, but a monthly instalment on a capital purchase is not.', max_length=12),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='paid_from_petty_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='payee',
            field=models.CharField(blank=True, default='', help_text='Filled from the supplier if left blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='The supplier, where they are on the register. Every payment this schedule generates lands on their account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='recurringexpense',
            name='voucher_no',
            field=models.CharField(blank=True, default='', help_text='A fixed reference, e.g. a standing order number. Left blank for most schedules, since each payment gets its own.', max_length=30),
        ),
    ]
