# Generated by Django 5.2.15 on 2026-07-25 17:52

from django.db import migrations, models



def backfill_due_dates(apps, schema_editor):
    """Existing generated rows were created on their due date, so that is the
    instalment they settle. Setting it explicitly keeps the new dedup key
    identical in meaning to the old one for everything already recorded."""
    Expense = apps.get_model("cashbook", "Expense")
    Expense.objects.filter(recurring__isnull=False,
                           recurring_due_date__isnull=True
                           ).update(recurring_due_date=models.F("date"))


def unbackfill(apps, schema_editor):
    Expense = apps.get_model("cashbook", "Expense")
    Expense.objects.update(recurring_due_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0042_historicalrecurringexpense_budget_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='recurring_due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Which scheduled instalment this row settles. Normally the same as the date; different when the payment was made early.', null=True),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='recurring_due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Which scheduled instalment this row settles. Normally the same as the date; different when the payment was made early.', null=True),
        ),
        migrations.RunPython(backfill_due_dates, unbackfill),
    ]
