# Generated by Django 5.2.15 on 2026-08-26 08:21

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0043_expense_recurring_due_date'),
        ('giving', '0028_campaignmessage_intended_count_campaignmessage_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPettyCashBankDeposit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_transaction', models.ForeignKey(blank=True, db_constraint=False, help_text='The bank credit that is this deposit of float cash.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Petty cash bank deposit',
                'verbose_name_plural': 'historical Petty cash bank deposits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PettyCashBankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.OneToOneField(blank=True, help_text='The bank credit that is this deposit of float cash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_bank_deposit', to='giving.transaction')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_bank_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty cash bank deposit',
                'verbose_name_plural': 'Petty cash bank deposits',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
