# Generated by Django 5.2.15 on 2026-07-10 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(db_index=True, max_length=100)),
                ('report_title', models.CharField(max_length=200)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, db_index=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report_version', models.CharField(default='', help_text='Application VERSION at generation time.', max_length=20)),
                ('template_version', models.CharField(default='', help_text="Report/engine template version — bump when a report's structure changes so snapshots are comparable within a version.", max_length=40)),
                ('schema_version', models.PositiveSmallIntegerField(default=1, help_text='Snapshot payload schema version.')),
                ('payload', models.JSONField(default=dict, help_text='The rendered report as structured data (sections → rows).')),
                ('checksums', models.JSONField(default=dict, help_text="Per-format export checksums, e.g. {'csv': '…', 'xlsx': '…'}.")),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('metrics_used', models.JSONField(blank=True, default=list)),
                ('component_keys', models.JSONField(blank=True, default=list)),
                ('render_meta', models.JSONField(blank=True, default=dict)),
                ('finalised', models.BooleanField(default=False, help_text='Once true, the snapshot is immutable and cannot be re-saved.')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_key', 'period_end'], name='reports_rep_report__339740_idx'), models.Index(fields=['report_key', 'generated_at'], name='reports_rep_report__ace1c7_idx')],
            },
        ),
    ]
