# Generated by Django 5.2.15 on 2026-07-10 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('church_name', models.CharField(blank=True, max_length=200)),
                ('conference', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('contact_details', models.CharField(blank=True, max_length=300)),
                ('logo_url', models.URLField(blank=True)),
                ('primary_colour', models.CharField(default='#1f5f4f', max_length=7)),
                ('accent_colour', models.CharField(default='#b08d57', max_length=7)),
                ('font_family', models.CharField(default='Calibri, Arial, sans-serif', max_length=120)),
                ('header_text', models.CharField(blank=True, max_length=300)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('watermark_text', models.CharField(blank=True, max_length=60)),
                ('certification_statement', models.TextField(blank=True)),
                ('page_size', models.CharField(default='A4', max_length=10)),
                ('page_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('show_page_numbers', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='URL-safe id; the report renders at /reports/d/<key>/.', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Custom', max_length=80)),
                ('sections', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('page_settings', models.JSONField(blank=True, default=dict)),
                ('permission', models.CharField(choices=[('reports', 'Anyone with report access'), ('treasurer', 'Treasurer only'), ('admin', 'Administrators only')], default='reports', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('report_key', models.CharField(help_text='Engine report key (code-defined or def__<key>).', max_length=100)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('MANUAL', 'Manual only')], default='MONTHLY', max_length=10)),
                ('formats', models.JSONField(default=list, help_text="Export formats to snapshot, e.g. ['csv'].")),
                ('period_policy', models.CharField(choices=[('prev_month', 'Previous month'), ('prev_quarter', 'Previous quarter'), ('ytd', 'Year to date'), ('prev_year', 'Previous year'), ('all', 'All time')], default='prev_month', max_length=20)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('next_run', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('recipients', models.JSONField(blank=True, default=list, help_text='Email addresses to notify when a snapshot is generated.')),
                ('require_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reports.reportschedule')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportsnapshot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_key'],
                'unique_together': {('report_key', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ReportUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(db_index=True, max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('render_ms', models.PositiveIntegerField(default=0)),
                ('export_format', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['report_key', 'viewed_at'], name='reports_rep_report__b2498b_idx')],
            },
        ),
    ]
