# Generated by Django 5.2.15 on 2026-07-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportbranding_reportdefinition_reportschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdefinition',
            name='key',
            field=models.SlugField(help_text='URL-safe id; the report renders at /reports/r/def__<key>/.', max_length=100, unique=True),
        ),
    ]
