# Generated by Django 5.2.15 on 2026-08-01 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportdefinition_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(db_index=True, max_length=100)),
                ('section_key', models.CharField(max_length=100)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('AUTO', 'Generated from the figures'), ('AI', 'Written by the AI assistant'), ('MANUAL', 'Edited by the treasurer')], default='MANUAL', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_narratives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_key', 'section_key'],
                'indexes': [models.Index(fields=['report_key', 'period_end'], name='reports_rep_report__a5529c_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_key', 'section_key', 'period_start', 'period_end'), name='uniq_report_narrative_period')],
            },
        ),
    ]
