# Generated by Django 5.2.15 on 2026-06-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_parent'),
        ('giving', '0002_historicaltransaction_dev_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='allocationrule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.CreateModel(
            name='SplitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, help_text='e.g. 50.00 for 50%.', max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('split_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='giving.splitfund')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='allocationrule',
            name='split_fund',
            field=models.ForeignKey(blank=True, help_text='If set, the reference splits across funds.', null=True, on_delete=django.db.models.deletion.CASCADE, to='giving.splitfund'),
        ),
    ]
