# Generated by Django 5.2.15 on 2026-06-07 06:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0006_historicaltransaction_is_reversal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Always positive; reversals create an explicit contra entry via reverse().', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Always positive; reversals create an explicit contra entry via reverse().', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
