# Generated by Django 5.2.15 on 2026-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0012_historicaltransaction_excluded_from_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='sabbath_confirm_pending',
            field=models.BooleanField(db_index=True, default=False, help_text="Set by the statement importer when the gift's service Sabbath had already passed on the day of import; the treasurer confirms whether it stays on that Sabbath or moves to the next."),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sabbath_confirm_pending',
            field=models.BooleanField(db_index=True, default=False, help_text="Set by the statement importer when the gift's service Sabbath had already passed on the day of import; the treasurer confirms whether it stays on that Sabbath or moves to the next."),
        ),
    ]
