# Generated by Django 5.2 on 2026-06-30 07:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giving', '0018_historicaltransaction_campaign_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevGroupPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="A short name for this pattern, e.g. 'dev/grp + number'.", max_length=60)),
                ('pattern', models.CharField(help_text='Python regex, matched against the normalised reference (lowercase, no spaces). NUMBERED patterns need one (…) group for the number.', max_length=200)),
                ('kind', models.CharField(choices=[('NUMBERED', 'Captures a group number'), ('WORD', 'Development marker (no number)')], default='NUMBERED', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers are tried first.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDevGroupPattern',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(help_text="A short name for this pattern, e.g. 'dev/grp + number'.", max_length=60)),
                ('pattern', models.CharField(help_text='Python regex, matched against the normalised reference (lowercase, no spaces). NUMBERED patterns need one (…) group for the number.', max_length=200)),
                ('kind', models.CharField(choices=[('NUMBERED', 'Captures a group number'), ('WORD', 'Development marker (no number)')], default='NUMBERED', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers are tried first.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dev group pattern',
                'verbose_name_plural': 'historical dev group patterns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
