# Generated by Django 5.2.15 on 2026-06-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='SDA Church', max_length=120)),
                ('field_name', models.CharField(default='East Nairobi Field', help_text='Where trust funds are remitted.', max_length=120)),
                ('require_expense_approval', models.BooleanField(default=True, help_text='Expenses need treasurer approval before they hit balances.')),
                ('show_mpesa_ref', models.BooleanField(default=True, help_text='Show the M-Pesa / channel reference on ledger rows.')),
                ('enable_dev_groups', models.BooleanField(default=True, help_text='Track giving against development groups.')),
                ('auto_create_members', models.BooleanField(default=True, help_text='Create a member automatically for unknown bank payers.')),
                ('envelope_auto_receipt', models.BooleanField(default=True, help_text='Issue a receipt automatically when an envelope is recorded.')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Send SMS receipts / notifications via Advanta.')),
                ('sms_api_url', models.CharField(default='https://quicksms.advantasms.com', help_text='Advanta API base URL (see advantasms.com/bulksms-api).', max_length=200)),
                ('sms_api_key', models.CharField(blank=True, max_length=200)),
                ('sms_partner_id', models.CharField(blank=True, max_length=40)),
                ('sms_shortcode', models.CharField(blank=True, help_text='Registered sender ID / shortcode.', max_length=40)),
                ('sms_receipt_template', models.CharField(blank=True, default='Dear {name}, we received your offering of KES {amount} (receipt {receipt}) on {date}. God bless you. - {church}', help_text='Placeholders: {name} {amount} {receipt} {date} {church}', max_length=320)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configuration',
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DISABLED', 'SMS disabled')], default='QUEUED', max_length=8)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
