# Generated by Django 5.2.15 on 2026-06-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_sms_receipt_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='llm_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='llm_base_url',
            field=models.CharField(blank=True, help_text='Only for Custom / self-hosted OpenAI-compatible endpoints.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='llm_enabled',
            field=models.BooleanField(default=False, help_text='Use an external LLM for the assistant. Off = the built-in offline assistant answers from your data.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='llm_model',
            field=models.CharField(blank=True, help_text='e.g. claude-3-5-sonnet, gpt-4o-mini, gemini-1.5-flash.', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='llm_provider',
            field=models.CharField(choices=[('ANTHROPIC', 'Anthropic (Claude)'), ('OPENAI', 'OpenAI (GPT)'), ('GEMINI', 'Google (Gemini)'), ('GROQ', 'Groq'), ('OPENROUTER', 'OpenRouter'), ('CUSTOM', 'Custom (OpenAI-compatible)')], default='ANTHROPIC', max_length=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sig_elder',
            field=models.CharField(blank=True, max_length=120, verbose_name='First church elder'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sig_pastor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Pastor'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sig_treasurer',
            field=models.CharField(blank=True, max_length=120, verbose_name='Head treasurer'),
        ),
    ]
