# Generated by Django 5.2.15 on 2026-06-06 17:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfig_trust_remit_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='petty_cash_float',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Petty cash imprest (float) — the amount the petty cash is topped back up to. Set to 0 if you don't run a fixed float.", max_digits=12),
        ),
    ]
