# Generated by Django 5.2.15 on 2026-06-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalsiteconfig_email_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='dev_group_extra_prefixes',
            field=models.CharField(blank=True, help_text="Extra words (comma-separated) that mean a development group in bank references, e.g. 'project, phase'. The common 'grp/devgroup' spellings are always recognised.", max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='dev_group_extra_prefixes',
            field=models.CharField(blank=True, help_text="Extra words (comma-separated) that mean a development group in bank references, e.g. 'project, phase'. The common 'grp/devgroup' spellings are always recognised.", max_length=200),
        ),
    ]
