# Generated by Django 5.2.15 on 2026-06-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_historicalyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('collection', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('trust_fund', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'ordering': ['year', 'month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uniq_hist_year_month')],
            },
        ),
    ]
