# Generated by Django 5.2.15 on 2026-06-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_telegramsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='sabbath_confirm_scope',
            field=models.CharField(choices=[('RECEIPTABLE', 'Only funds we receipt (Trust + LCB)'), ('ALL', 'All bank giving')], default='RECEIPTABLE', help_text='Which late-imported gifts appear in the Sabbath confirmations queue. By default only the funds you normally receipt (Trust funds and the Local Church Budget) — others just post by date.', max_length=12),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='sabbath_confirm_scope',
            field=models.CharField(choices=[('RECEIPTABLE', 'Only funds we receipt (Trust + LCB)'), ('ALL', 'All bank giving')], default='RECEIPTABLE', help_text='Which late-imported gifts appear in the Sabbath confirmations queue. By default only the funds you normally receipt (Trust funds and the Local Church Budget) — others just post by date.', max_length=12),
        ),
    ]
