# Generated by Django 5.2.15 on 2026-06-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_historicalsiteconfig_backup_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='require_2fa_for_treasurers',
            field=models.BooleanField(default=False, help_text='Require treasurers to set up two-factor authentication. They will be prompted to enrol at next login and cannot skip it.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='require_2fa_for_treasurers',
            field=models.BooleanField(default=False, help_text='Require treasurers to set up two-factor authentication. They will be prompted to enrol at next login and cannot skip it.'),
        ),
    ]
