# Generated by Django 5.2.15 on 2026-06-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_historicalsiteconfig_require_2fa_for_treasurers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='error_alert_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number to receive SMS / WhatsApp error alerts (uses the SMS and WhatsApp settings already configured).', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='error_alerts_enabled',
            field=models.BooleanField(default=False, help_text='If on, the admin is alerted when an unexpected error occurs, via whichever of email / SMS / WhatsApp are enabled.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='error_alert_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number to receive SMS / WhatsApp error alerts (uses the SMS and WhatsApp settings already configured).', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='error_alerts_enabled',
            field=models.BooleanField(default=False, help_text='If on, the admin is alerted when an unexpected error occurs, via whichever of email / SMS / WhatsApp are enabled.'),
        ),
    ]
