# Generated by Django 5.2 on 2026-06-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_historicalsiteconfig_site_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Implicit SSL — required for port 465. (Auto-enabled for port 465.)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Implicit SSL — required for port 465. (Auto-enabled for port 465.)'),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='STARTTLS — use for port 587. Turn OFF for port 465.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='STARTTLS — use for port 587. Turn OFF for port 465.'),
        ),
    ]
