# Generated by Django 5.2 on 2026-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='dev_group_builder_apply',
            field=models.BooleanField(default=False, help_text='Allow the development-group builder to actually create groups and reassign members in the system. Off = the builder only produces a downloadable Excel/CSV proposal and never changes any data.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='dev_group_builder_apply',
            field=models.BooleanField(default=False, help_text='Allow the development-group builder to actually create groups and reassign members in the system. Off = the builder only produces a downloadable Excel/CSV proposal and never changes any data.'),
        ),
    ]
