# Generated by Django 5.2 on 2026-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_userpreference_sidebar_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='font_family',
            field=models.CharField(choices=[('DEFAULT', 'Public Sans (default)'), ('SYSTEM', 'System UI'), ('SERIF', 'Serif (Georgia)'), ('LEGIBLE', 'Atkinson Hyperlegible'), ('MONO', 'Monospace')], default='SYSTEM', help_text="The typeface used across the app's body text.", max_length=8),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=8),
        ),
    ]
