# Generated by Django 5.2 on 2026-07-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_historicalsiteconfig_receipt_strip_strings_and_more'),
        ('departments', '0019_department_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='camp_offering_fund',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The Trust fund collecting the Camp Meeting offering.', limit_choices_to={'fund_type': 'TRUST'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='camp_offering_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="This year's Camp Meeting Offering goal.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='camp_offering_fund',
            field=models.ForeignKey(blank=True, help_text='The Trust fund collecting the Camp Meeting offering.', limit_choices_to={'fund_type': 'TRUST'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='departments.department'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='camp_offering_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="This year's Camp Meeting Offering goal.", max_digits=12, null=True),
        ),
    ]
