# Generated by Django 5.2 on 2026-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_migrate_camp_offering_goal_to_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='receipt_strip_strings',
            field=models.TextField(blank=True, help_text="One phrase per line. These are removed from bank/M-Pesa receipt messages when they are saved (e.g. the 'never share your PIN' boilerplate), keeping stored receipts short and readable. Use * as a wildcard for parts that change each time, e.g. an amount: 'New M-PESA balance is Ksh*.' strips that whole sentence whatever the figure is."),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='receipt_strip_strings',
            field=models.TextField(blank=True, help_text="One phrase per line. These are removed from bank/M-Pesa receipt messages when they are saved (e.g. the 'never share your PIN' boilerplate), keeping stored receipts short and readable. Use * as a wildcard for parts that change each time, e.g. an amount: 'New M-PESA balance is Ksh*.' strips that whole sentence whatever the figure is."),
        ),
    ]
