# Generated by Django 5.2 on 2026-07-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_historicalsiteconfig_archive_replaced_ledger_entries_and_more'),
        ('departments', '0021_alter_departmentstatuslog_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcarryforward',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department'),
        ),
    ]
