# Generated by Django 5.2.15 on 2026-06-04 05:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_developmentgroup_alter_department_options_and_more'),
        ('giving', '0002_historicaltransaction_dev_group_and_more'),
        ('members', '0002_remove_historicalmember_envelope_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The Sabbath (Saturday) the envelope was given.')),
                ('sabbath_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receipt_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('contributor_name', models.CharField(help_text='As written on the envelope (may be a group or visitor).', max_length=120)),
                ('channel', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank / M-Pesa')], default='CASH', max_length=4)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelope', to='giving.transaction')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelopes', to='members.member')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envelopes_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'receipt_no'],
            },
        ),
        migrations.CreateModel(
            name='EnvelopeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='envelopes.envelope')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelope_lines', to='giving.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEnvelope',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The Sabbath (Saturday) the envelope was given.')),
                ('sabbath_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receipt_no', models.CharField(db_index=True, max_length=20)),
                ('contributor_name', models.CharField(help_text='As written on the envelope (may be a group or visitor).', max_length=120)),
                ('channel', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank / M-Pesa')], default='CASH', max_length=4)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical envelope',
                'verbose_name_plural': 'historical envelopes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='envelope',
            index=models.Index(fields=['date'], name='envelopes_e_date_55da15_idx'),
        ),
    ]
