# Generated by Django 5.2.15 on 2026-06-04 03:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMember',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('group', models.CharField(blank=True, choices=[('YOUTH', 'Youth'), ('AMM', "Adventist Men's Ministries"), ('AWM', "Adventist Women's Ministries"), ('AMBASSADORS', 'Ambassadors'), ('CHILDREN', 'Children')], max_length=12, null=True)),
                ('envelope_no', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered manually'), ('AUTO_BANK', 'Created from bank statement')], default='MANUAL', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dev_group', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'category': 'DEV_GROUP'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical member',
                'verbose_name_plural': 'historical members',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=12, null=True)),
                ('group', models.CharField(blank=True, choices=[('YOUTH', 'Youth'), ('AMM', "Adventist Men's Ministries"), ('AWM', "Adventist Women's Ministries"), ('AMBASSADORS', 'Ambassadors'), ('CHILDREN', 'Children')], max_length=12, null=True)),
                ('envelope_no', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered manually'), ('AUTO_BANK', 'Created from bank statement')], default='MANUAL', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev_group', models.ForeignKey(blank=True, limit_choices_to={'category': 'DEV_GROUP'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_group_members', to='departments.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MemberAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'member aliases',
            },
        ),
        migrations.CreateModel(
            name='PossibleDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flag', to='members.member')),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name_key'], name='members_mem_name_ke_e1d3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone'], name='members_mem_phone_94f004_idx'),
        ),
    ]
