# Generated by Django 5.2.15 on 2026-07-09 14:16

import django.core.validators
import django.db.models.deletion
import loans.models
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0034_expense_funding_source_and_more'),
        ('departments', '0021_alter_departmentstatuslog_department'),
        ('giving', '0022_transaction_giving_txn_dir_conf_date_idx'),
        ('members', '0004_member_members_mem_name_8eb2d0_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLoanNarrationPattern',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Compared against the normalised reference (lowercased, no spaces).', max_length=60)),
                ('match_type', models.CharField(choices=[('EXACT', 'Matches exactly'), ('STARTS', 'Starts with'), ('ENDS', 'Ends with'), ('CONTAINS', 'Contains'), ('REGEX', 'Matches a pattern (regex)')], default='CONTAINS', max_length=8)),
                ('kind', models.CharField(choices=[('RECEIPT', 'Loan receipt (money in)'), ('REPAYMENT', 'Loan repayment (money out)'), ('INTEREST', 'Loan interest (money out)'), ('CONVERSION', 'Loan converted to donation')], db_index=True, default='RECEIPT', max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('seeded', models.BooleanField(default=False, editable=False, help_text='Installed by the system (may be edited or deactivated freely).')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fund', models.ForeignKey(blank=True, db_constraint=False, help_text='For receipts: the fund the loan finances. Blank = fund unknown, item goes to the review queue.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical loan narration pattern',
                'verbose_name_plural': 'historical loan narration patterns',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=8)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered manually'), ('AUTO_BANK', 'Created from bank statement')], default='MANUAL', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, help_text='The church member this lender is, if any. Never created automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lender_records', to='members.member')),
                ('merged_into', models.ForeignKey(blank=True, help_text='If set: this duplicate was merged into that lender (kept for the audit trail, no longer used).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='loans.lender')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLoan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(db_index=True, editable=False, help_text='Permanent loan reference (e.g. LN-2026-0001); assigned once, never reused.', max_length=20)),
                ('loan_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization / institution'), ('CHURCH', 'Another church'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=12)),
                ('project', models.CharField(blank=True, help_text='Optional project this loan finances.', max_length=120)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The agreed principal (optional). Money actually received is tracked by receipt transactions; the outstanding balance is always computed from transactions, never from this figure.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate in percent. 0 for interest-free.', max_digits=5)),
                ('interest_method', models.CharField(choices=[('NONE', 'Interest-free'), ('SIMPLE', 'Simple interest (p.a. on outstanding)'), ('FLAT', 'Flat (p.a. on agreed principal)')], default='NONE', max_length=8)),
                ('loan_date', models.DateField(db_index=True)),
                ('maturity_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CONVERTED', 'Converted to donation'), ('WRITTEN_OFF', 'Written off')], db_index=True, default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, db_constraint=False, help_text="The local fund this loan finances. Loan money raises this fund's available cash but never its income.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.lender')),
            ],
            options={
                'verbose_name': 'historical loan',
                'verbose_name_plural': 'historical loans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLender',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=8)),
                ('source', models.CharField(choices=[('MANUAL', 'Entered manually'), ('AUTO_BANK', 'Created from bank statement')], default='MANUAL', max_length=12)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, db_constraint=False, help_text='The church member this lender is, if any. Never created automatically.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='members.member')),
                ('merged_into', models.ForeignKey(blank=True, db_constraint=False, help_text='If set: this duplicate was merged into that lender (kept for the audit trail, no longer used).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.lender')),
            ],
            options={
                'verbose_name': 'historical lender',
                'verbose_name_plural': 'historical lenders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='Permanent loan reference (e.g. LN-2026-0001); assigned once, never reused.', max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization / institution'), ('CHURCH', 'Another church'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=12)),
                ('project', models.CharField(blank=True, help_text='Optional project this loan finances.', max_length=120)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The agreed principal (optional). Money actually received is tracked by receipt transactions; the outstanding balance is always computed from transactions, never from this figure.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate in percent. 0 for interest-free.', max_digits=5)),
                ('interest_method', models.CharField(choices=[('NONE', 'Interest-free'), ('SIMPLE', 'Simple interest (p.a. on outstanding)'), ('FLAT', 'Flat (p.a. on agreed principal)')], default='NONE', max_length=8)),
                ('loan_date', models.DateField(db_index=True)),
                ('maturity_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CONVERTED', 'Converted to donation'), ('WRITTEN_OFF', 'Written off')], db_index=True, default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(help_text="The local fund this loan finances. Loan money raises this fund's available cash but never its income.", on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='departments.department')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.lender')),
            ],
            options={
                'ordering': ['-loan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLoanTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIPT', 'Loan receipt'), ('PRINCIPAL', 'Principal repayment'), ('INTEREST', 'Interest payment'), ('CONVERSION', 'Converted to donation'), ('WRITE_OFF', 'Write off')], db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.expense')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('income_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction')),
                ('receipt_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='giving.transaction')),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan')),
            ],
            options={
                'verbose_name': 'historical loan transaction',
                'verbose_name_plural': 'historical loan transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=loans.models.loan_attachment_path)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='loans.loan')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanNarrationPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Compared against the normalised reference (lowercased, no spaces).', max_length=60)),
                ('match_type', models.CharField(choices=[('EXACT', 'Matches exactly'), ('STARTS', 'Starts with'), ('ENDS', 'Ends with'), ('CONTAINS', 'Contains'), ('REGEX', 'Matches a pattern (regex)')], default='CONTAINS', max_length=8)),
                ('kind', models.CharField(choices=[('RECEIPT', 'Loan receipt (money in)'), ('REPAYMENT', 'Loan repayment (money out)'), ('INTEREST', 'Loan interest (money out)'), ('CONVERSION', 'Loan converted to donation')], db_index=True, default='RECEIPT', max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('seeded', models.BooleanField(default=False, editable=False, help_text='Installed by the system (may be edited or deactivated freely).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(blank=True, help_text='For receipts: the fund the loan finances. Blank = fund unknown, item goes to the review queue.', null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'ordering': ['kind', '-active', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECEIPT', 'Loan receipt'), ('PRINCIPAL', 'Principal repayment'), ('INTEREST', 'Interest payment'), ('CONVERSION', 'Converted to donation'), ('WRITE_OFF', 'Write off')], db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_transaction', to='cashbook.expense')),
                ('income_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_retirement_income', to='giving.transaction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='loans.loan')),
                ('receipt_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_receipt', to='giving.transaction')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lender',
            index=models.Index(fields=['name_key'], name='loans_lende_name_ke_a5b2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='lender',
            index=models.Index(fields=['phone'], name='loans_lende_phone_b0b7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'fund'], name='loans_loan_status_11eb11_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['maturity_date'], name='loans_loan_maturit_814b20_idx'),
        ),
        migrations.AddIndex(
            model_name='loantransaction',
            index=models.Index(fields=['loan', 'kind'], name='loans_loant_loan_id_c2cdbc_idx'),
        ),
        migrations.AddIndex(
            model_name='loantransaction',
            index=models.Index(fields=['date'], name='loans_loant_date_48e71f_idx'),
        ),
    ]
