# Generated by Django 5.2.15 on 2026-07-09 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0034_expense_funding_source_and_more'),
        ('loans', '0002_seed_patterns_and_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloantransaction',
            name='petty_topup',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cashbook.pettycashtopup'),
        ),
        migrations.AddField(
            model_name='loantransaction',
            name='petty_topup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_transaction', to='cashbook.pettycashtopup'),
        ),
    ]
