# Generated by Django 5.2.15 on 2026-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_trust', models.BooleanField(default=False, help_text='True = remit to the conference (a trust fund).')),
                ('category', models.CharField(choices=[('OFFERING', 'Offering'), ('MINISTRY', 'Ministry'), ('DEV_GROUP', 'Development group'), ('HOLDING', 'Holding (e.g. Envelopes)'), ('TRUST', 'Trust')], max_length=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Brought-forward balance.', max_digits=12)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, help_text='Fund-raising target, mainly for development groups.', max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
