# Generated by Django 5.2.15 on 2026-06-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='children_in_expenses',
            field=models.BooleanField(default=False, help_text='For a parent fund: if on, its sub-accounts can be charged expenses individually; if off, expenses use the parent fund only (sub-accounts are for collections).'),
        ),
    ]
