# Generated by Django 5.2.15 on 2026-06-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_budget_budgetline_historicalbudget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='annual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
