# Generated by Django 5.2.15 on 2026-06-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_migrate_annual_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='source_fund',
            field=models.ForeignKey(blank=True, help_text="Where the money comes from. Leave blank to fund it from the department's own funds; or choose the Local Church Budget or another fund.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_budget_lines', to='departments.department'),
        ),
        migrations.AddField(
            model_name='historicalbudgetline',
            name='source_fund',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Where the money comes from. Leave blank to fund it from the department's own funds; or choose the Local Church Budget or another fund.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.department'),
        ),
    ]
