# Generated by Django 5.2.15 on 2026-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_budgetline_source_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentgroup',
            name='leader_email',
            field=models.EmailField(blank=True, help_text="If set, the group's contribution report can be emailed here.", max_length=254),
        ),
        migrations.AddField(
            model_name='developmentgroup',
            name='leader_name',
            field=models.CharField(blank=True, help_text='Group leader, for reconciliation reports.', max_length=120),
        ),
    ]
