# Generated by Django 5.2.15 on 2026-06-11 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_developmentgroup_leader_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_split',
            field=models.BooleanField(default=False, help_text='This fund divides into several funds when money is allocated to it (e.g. Combined Offering → 50% Trust + 50% Local).'),
        ),
        migrations.AddField(
            model_name='department',
            name='selectable',
            field=models.BooleanField(default=True, help_text='Show this fund in allocation pickers (review queue, cash entry, envelopes). Turn off for the internal halves of a split fund.'),
        ),
        migrations.CreateModel(
            name='SplitTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=4, help_text='e.g. 0.5000 for 50%', max_digits=5)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_targets', to='departments.department')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_sources', to='departments.department')),
            ],
            options={
                'ordering': ['-fraction', 'target__name'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
