# Generated by Django 5.2.15 on 2026-06-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_department_is_split_department_selectable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_split',
        ),
        migrations.DeleteModel(
            name='SplitTarget',
        ),
    ]
