# Generated by Django 5.2.15 on 2026-06-13 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_remove_department_is_split_delete_splittarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Department leaderships',
                'constraints': [models.UniqueConstraint(fields=('user', 'department'), name='uniq_user_department_lead')],
            },
        ),
    ]
