# Generated by Django 5.2 on 2026-06-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_resync_is_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetline',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 (Jan–Mar)'), ('Q2', 'Q2 (Apr–Jun)'), ('Q3', 'Q3 (Jul–Sep)'), ('Q4', 'Q4 (Oct–Dec)')], help_text='Optional: the quarter the fund expects to spend this line, for planning insight. Leave blank for spread across the year.', max_length=2),
        ),
        migrations.AddField(
            model_name='historicalbudgetline',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1 (Jan–Mar)'), ('Q2', 'Q2 (Apr–Jun)'), ('Q3', 'Q3 (Jul–Sep)'), ('Q4', 'Q4 (Oct–Dec)')], help_text='Optional: the quarter the fund expects to spend this line, for planning insight. Leave blank for spread across the year.', max_length=2),
        ),
    ]
