# Generated by Django 5.2 on 2026-06-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_budgetline_quarter_historicalbudgetline_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contribution_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Collection goal that groups contribute towards (e.g. a camp expenses goal).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='year_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual goal for this fund (e.g. the Camp Meeting goal for the year).', max_digits=12, null=True),
        ),
    ]
