# Generated by Django 5.2 on 2026-06-30 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0017_department_collection_only_department_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='offering_fund',
            field=models.ForeignKey(blank=True, help_text='For an expense fund (e.g. Camp Meeting Expense, a Local fund): the separate Trust offering fund it is paired with (e.g. Camp Meeting Offering). Lets both goals be tracked on one budget page without ever merging their totals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_counterpart', to='departments.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='offering_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Annual goal for the paired Trust offering fund — tracked independently of this fund's expense goal.", max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='year_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual goal for this fund (e.g. the Camp Meeting Expense goal for the year).', max_digits=12, null=True),
        ),
    ]
