# Generated by Django 5.2 on 2026-07-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0020_department_income_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstatuslog',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='departments.department'),
        ),
    ]
