# Generated by Django 5.2.15 on 2026-06-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactor',
            name='delivery_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='method',
            field=models.CharField(choices=[('TOTP', 'Authenticator app'), ('SMS', 'Text message (SMS)'), ('EMAIL', 'Email')], default='TOTP', max_length=6),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='otp_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
