# Generated by Django 5.2.15 on 2026-06-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['fund_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='target',
        ),
        migrations.AddField(
            model_name='department',
            name='fund_type',
            field=models.CharField(choices=[('TRUST', 'Trust fund (remitted to field)'), ('LOCAL', 'Local fund (church department)')], default='LOCAL', help_text='Trust funds are remitted to the field; local funds stay with the church.', max_length=8),
        ),
        migrations.AlterField(
            model_name='department',
            name='category',
            field=models.CharField(choices=[('OFFERING', 'Offering'), ('MINISTRY', 'Ministry'), ('DEVELOPMENT', 'Development'), ('HOLDING', 'Holding'), ('TRUST', 'Trust')], default='OFFERING', max_length=12),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_trust',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
