# Generated by Django 5.2.15 on 2026-06-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_developmentgroup_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional. Set this to make the fund a sub-account (e.g. Youth → Potluck, Choir, Mission).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgroups', to='departments.department'),
        ),
    ]
