# Generated by Django 5.2.15 on 2026-06-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_children_in_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='show_in_expenses',
            field=models.BooleanField(default=True, help_text='Show this fund in the expense department picker. Turn off for collection-only funds that are never spent directly.'),
        ),
    ]
