# Generated by Django 5.2 on 2026-06-25 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_department_contribution_goal_department_year_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='collection_only',
            field=models.BooleanField(default=False, help_text='A collection account that only receives contributions (e.g. a camp fundraising group). It can receive income but is never selectable for expenses or payments.'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', help_text='Closed/archived accounts stay in historical reports but accept no new transactions. An account can only be closed at a zero balance.', max_length=8),
        ),
        migrations.CreateModel(
            name='DepartmentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=8)),
                ('to_status', models.CharField(max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='departments.department')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
