# Generated by Django 5.2 on 2026-06-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_department_offering_fund_department_offering_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='goal_type',
            field=models.CharField(choices=[('NONE', 'General annual goal'), ('CAMP_EXPENSE', 'Camp Meeting Expense goal')], db_index=True, default='NONE', help_text="Classifies what this fund's annual goal represents, so reports label and pair it correctly regardless of the fund's name.", max_length=20),
        ),
    ]
