# Generated by Django 5.2 on 2026-07-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0019_department_goal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='income_account',
            field=models.CharField(blank=True, choices=[('', "Guess from the fund's name (default)"), ('INC_TITHE', 'Tithe'), ('INC_OFFERINGS', 'Offerings & general income'), ('INC_DEVELOPMENT', 'Development & projects'), ('INC_INTEREST', 'Interest & investment income'), ('INC_FUNDRAISING', 'Fundraising & camp meeting'), ('INC_DONATIONS', 'Donations & gifts in kind'), ('INC_OTHER', 'Other income')], help_text="Which income account a local (unrestricted) fund's receipts post to in the general ledger. Leave blank to classify automatically from the fund's name (matches most funds); set this explicitly for a fund whose name doesn't clearly say what it is, or after renaming a fund, so its income keeps reporting under the same account as before.", max_length=20),
        ),
    ]
