# Generated by Django 5.2.15 on 2026-06-04 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_developmentgroup_alter_department_options_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmember',
            name='envelope_no',
        ),
        migrations.RemoveField(
            model_name='member',
            name='envelope_no',
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='member_type',
            field=models.CharField(blank=True, choices=[('MEMBER', 'Church member'), ('SS_MEMBER', 'Sabbath School member')], help_text='Optional: church member or Sabbath School member.', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, choices=[('MEMBER', 'Church member'), ('SS_MEMBER', 'Sabbath School member')], help_text='Optional: church member or Sabbath School member.', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmember',
            name='dev_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departments.developmentgroup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dev_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='departments.developmentgroup'),
        ),
    ]
