# Generated by Django 5.2.15 on 2026-06-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_historicalmember_envelope_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=12)),
                ('is_primary', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, help_text="e.g. 'M-Pesa', 'work'", max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='members.member')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
                'unique_together': {('member', 'number')},
            },
        ),
    ]
