# Generated by Django 5.2 on 2026-06-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_budgetline_quarter_historicalbudgetline_quarter'),
        ('members', '0003_memberphone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['name'], name='members_mem_name_8eb2d0_idx'),
        ),
    ]
