# Generated by Django 5.2.17 on 2026-09-06 05:42

from django.db import migrations, models

from core.codes import generate_match_code


def backfill_member_codes(apps, schema_editor):
    Member = apps.get_model("members", "Member")
    used = set(Member.objects.exclude(match_code__isnull=True)
               .exclude(match_code="")
               .values_list("match_code", flat=True))
    for m in Member.objects.filter(
            models.Q(match_code__isnull=True) | models.Q(match_code="")):
        for _ in range(40):
            code = generate_match_code("MB")
            if code not in used:
                used.add(code)
                m.match_code = code
                m.save(update_fields=["match_code"])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_membertag_member_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmember",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code others put in a bank reference to credit this "
                          "member and their development group.",
                max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code others put in a bank reference to credit this "
                          "member and their development group.",
                max_length=16, null=True),
        ),
        migrations.RunPython(backfill_member_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="member",
            name="match_code",
            field=models.CharField(
                blank=True, db_index=True,
                help_text="Code others put in a bank reference to credit this "
                          "member and their development group.",
                max_length=16, null=True, unique=True),
        ),
    ]
